### ISSUE TITLE
Custom merge driver support

### ISSUE THREAD

**Issue by jacquesg** [libgit2/libgit2#2180]
There are quite a number of use cases where having support for custom merge drivers would be useful.

The simplest example is probably a change log. Two branches are created, starting at the same commit. Both branches insert an entry at the top of the change log file. The first one merges without problems, the second requires a rebase.

It would be nice if both branches could merge without the need for a rebase.

**Comment by eukreign** [comment]
Has there been any more thought on this feature? I'm curious if there are plans to actually implement it in libgit2?

**Comment by ljmatkins** [comment]
+1 from me !

**Comment by stanhu** [comment]
+1

**Comment by stanhu** [comment]
The issue here is the using a blanket `favor` call doesn't do the right thing if you have a commit that includes other things that you don't want to merge with that flag.

Would it be easier to implement this in such a way that the merge routine uses the `.gitattributes` file and decides what favor to use on a file-by-file basis as git does?
