### ISSUE TITLE
Warn when a repository contains files that differ only in case on a case-insensitive filesystem

### ISSUE THREAD

**Issue by jspahrsummers** [libgit2/libgit2#2254]
It's possible to create a repository (on a case-sensitive filesystem, or through some manual Git manipulation) that contains two tree entries for the “same” file that differ only in case. For example, you could have `foobar.txt` and `FOOBAR.txt` in the same repository.

When checking this repository out on a case-insensitive filesystem, Git's behavior is “last write wins.” This can result in an incorrect diff being shown when the files differ in content.

libgit2's current behavior is to represent one of the two entries as “deleted” in the WD upon checkout. This is logical from a technical standpoint, but still confusing for users.

I'd propose that libgit2 notifies the caller about this case somehow, so we can inform users that their repository is screwy, instead of silently doing weird things with the diff.

/cc @arrbee

**Comment by ethomson** [comment]
My inclination here is to close this issue as is.  We've done a lot of work since this issue was opened to match git *exactly* in its checkout behavior, so that we produce identical diffs.

Sadly, it's not as simple as merely comparing file paths case insensitively to determine whether you have a collision between two paths.  Different filesystems handle things like Unicode empty characters differently and do weird things like map `FOOBAR~1.TXT` to `foobarlongpath.txt`.  We really can't know about these things to warn the user in advance.

So I'm going to say "matching git" is the best that we can realistically do here and close the issue as such.
