### ISSUE TITLE
Stack overflow when calling fs_iterator__advance_over()

### ISSUE THREAD

**Issue by linquize** [libgit2/libgit2#2541]
`fs_iterator__update_entry(fs_iterator * fi)` Line 1208
`fs_iterator__advance_over(const git_index_entry ** entry, git_iterator * self)` Line 1102
............
`fs_iterator__update_entry(fs_iterator * fi)` Line 1208
`fs_iterator__advance_over(const git_index_entry ** entry, git_iterator * self)` Line 1102

**Comment by ethomson** [comment]
I'm afraid that it's very difficult to proceed here without further information, and it appears that this is not reproducible.  I have a hunch that a stray cosmic ray zapped the machine and flipped a bit in the stack that caused this.

Well, no, not really, but I'm afraid that I am going to close this issue since there's not enough data to proceed.  Please reopen if there is additional information to aide investigation.  Thanks!
