### ISSUE TITLE
git_index_add_all() and git_index_update_all() are about 25X slower than git CLT

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2687]
I have a test repo with 800+ files. Running `git_index_add_all()` or `git_index_update_all()` with only 1 file modified takes 0.5s on my MacBook Pro with SSD. Doing the same with `git -A` takes 0.02s.

Looking at the implementation it appears that both functions re-import all the files as blobs into the database, ignoring which files have actually changed.

**Comment by maxkorp** [comment]
Is this in the pipeline for fixes anywhere? I've implemented the workaround like @swisspol described for nodegit, but it would be nice to avoid workarounds if it can be fixed in the underlying code. I'd be happy to help, but while I've taken a look around in there my C-fu is far from great and I'm not really sure where to start.
