### ISSUE TITLE
fips compliance 140-2

### ISSUE THREAD

**Issue by cmgmaggie** [libgit2/libgit2#2769]
Right now, libgit2 libraries are not fips compliant.   They make use of the SHA1* family of functions in openssl, which are not fips-compliant.  We would like to see a resolution of this issue.  In particular, we would prefer a patch to v0.19, since there is not a lot of stability between different versions of libgit2. If possible, please response to email cedric_guss@silanis.com when you have an answer.
Thank you.

**Comment by ethomson** [comment]
I think that since none of the contributors have access to any FIPS compliant libraries, and indeed perhaps not the one that other users would be interested in, we're going to close this in the hopes that you would provide a pull request that conditionally enables the FIPS compliant library that you're interested in using.  We would be eager to merge such a contribution.

Thanks again!
