### ISSUE TITLE
Transports and custom data

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#2790]
I've been tackling a few things with custom transports recently, and I've run into a few issues here and there:

* When I call `git_transport_register`, I hand off my `void*`, but there doesn't seem to be a point where I get it back? If it is an allocated block it's tough to free it at some point unless I store it personally and free it after a call to `git_transport_unregister`.
  
  One concrete instance of this issue is that when using `git_smart_subtransport_definition`, if it's an allocated block, it's tough to get it back out to deallocate it.
* When using `git_smart_subtransport_definition`, there's no way to provide custom data to the stored `git_smart_subtransport_cb`. This is the same as #2500, but it seems that it was closed with no resolution?

I would personally be looking for something along the lines of:

* `git_transport_unregister` takes a `*mut *mut c_void` parameter (optionally `NULL`) which receives the data pointer of the unregistered callback.
* `git_smart_subtransport_definition` gains a `free` callback like the other `git_smart` structures.
* `git_smart_subtransport_cb` also receives the `git_smart_subtransport_definition` as an argument.

All that being said, I may have missed something!

**Comment by carlosmn** [comment]
The internal structure is just that, a structure we use internally to keep track of data. If you're writing code outside of the library, you'd have your own structure in which you keep data.

The remote will call one of the methods in your object to tell you what the callbacks are. Since it's the same for all libgit2-implemented transports, we use a common function for that, but it doesn't get any special treatment just because it's in the codebase: https://github.com/libgit2/libgit2/blob/master/src/transports/smart.c#L52-L67

**Comment by alexcrichton** [comment]
Aha yes, that solves that problem, thanks!

**Comment by ethomson** [comment]
Glad to hear that this was solved.  Thanks!
