### ISSUE TITLE
Update git_merge APIs documentation to indicate what type of merge strategy is used

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2796]
I think it's important enough to know :)

**Comment by ethomson** [comment]
See #2799 - we don't really have a "merge strategy" quite like git core does, since some of the merge strategies (like "ours") don't *do* a merge, but do produce a *merge commit*.  I was a little reluctant to document this since I would prefer to see us support `git-merge-recursive`-like ancestor tree production, but I simply have not gotten around to it lately.  (I think the bigger advantage to `merge-recursive` is its rename support, not criss-cross merge support.  And we do support renames in our implementation as-is.)

**Comment by swisspol** [comment]
Got it thanks!
