### ISSUE TITLE
fips compliance 140-2 (in regard to closed ticket #2769)

### ISSUE THREAD

**Issue by cmgmaggie** [libgit2/libgit2#2822]
Thanks for the comments to the closed ticket 2769 with regard to fips compliance.  Sorry that I didn't keep up with the thread the last several days.   The problem is the following:  libgit2 calls a series of SHA1 functions in openssl that are not fips-compliant.   The equivalent set of SHA2 functions in openssl are fips-compliant; and my question is if there is a way to replace to those calls using SHA1 with the equivalent set of calls to SHA2, perhaps with a patch.   Yes it's true, we're using an older version of libgit2; but the request should be applicable to all versions.   Actually, the offending functions are only 3: SHA1_Init, SHA1_Update, and SHA1_Final, all used in libgit2's  hash_openssl.h module.
Thanks

**Comment by ethomson** [comment]
No, you cannot simply replace SHA-1 with SHA-2: this would preclude compatibility with git.git.  If you replaced libgit2's SHA-1 functions with SHA-2 functions (or any other hash) then you would no longer be able to communicate with the git command-line client, any other clients, or any git servers.  You could no longer push or pull from (say) GitHub because you would have no common idea of what an object was, since every other Git implementation uses SHA-1 to identify an object.

You are welcome to do this yourself, but the result would no longer be Git, it would be another system.

This is not a change that we would consider.

If there exists a FIPS-compatible library that uses SHA-1, then we *would* consider an optional (and off by default) linking against that library.  However, I'm afraid that FIPS is not my strong suit, so if SHA-1 is simply never FIPS compliant, then I realize that this is not an option.

However, I do want to point out again that Git does not use SHA-1 for security, but for data integrity.  Many security guidelines consider the intent of a hash function and if you are using a hash *for integrity checks* and not for security, then they would not be covered by FIPS.

(To reduce this to the absurd:  do you need to change your instances of Josh Bloch's `hashCode` function to SHA-512 for FIPS compliance?)

**Comment by cmgmaggie** [comment]
No we don't need SHA-512.  SHA-256 would be good enough.   However, yes I am aware that we cannot simply swap the SHA1 functions with SHA2; if we could, we could be fips-compliant.   In any case, we are not doing anything special in git (eg for security) to access SHA1; git is doing it itself for integrity checking; so we have no control on that.   And unfortunately, one thing about fips-compliance: once one item is not fips-compliant, then the entire package becomes non-fips-compliant.   So I guess we have a problem here.  
In any case, it sounds like git is using SHA-1 throughout for everything.   And I doubt there are plans for making SHA1 fips-compliant, not that it makes sense to do so.  But it does lead to a question - at some point, SHA-1 algorithms are going to become inadequate and obsolete, as online security increasingly becomes an issue;  so I would think that github needs to consider plans for SHA2 or SHA512, because this issue will increasingly become a problem for git users/developers going forward.  regards....

**Comment by adrienthebo** [comment]
SHA-1 has been deprecated, but only as a cryptographic hashing algorithm. SHA-1 is perfectly fine for verifying data integrity which is how it's being used by Git. By itself SHA-1 provides sufficient protection against hash collisions and can continue to be used for data integrity; it's not like SHA-1 will become less effective over time at verifying that objects on disk have not changed. Because SHA-1 provides these guarantees and isn't being used in the manner that would make it obsolete, I personally don't see SHA-1 being removed from Git at all. This does have some nasty implications for FIPS though, since it's assuming that SHA-1 is always being used in a cryptographic manner.

**Comment by ethomson** [comment]
Like I said earlier, we will follow Git core here for interoperability.  If they move to SHA-3 then we would follow suit.  Until that point, though, we will stay with SHA-1 for interop.

If that means that you evaluate your application using libgit2 to not meet FIPS, then I regret that, but given the decision between Git compatibility and FIPS compliance, we simply must err towards Git compatibility.  I trust that if you require both Git compatibility *and* FIPS compliance that you will be able to get some sort of exemption.

Sorry if this decision disappoints.  However, I am closing this issue as well, since I feel that this has been adequately discussed at this point until such time as Git changes its behavior.
