### ISSUE TITLE
Documentation for v0.21.4 isn't live

### ISSUE THREAD

**Issue by johnhaley81** [libgit2/libgit2#2825]
The final release on the 0.21 branch doesn't have any docs up. (i.e. [v0.21.4](https://libgit2.github.com/libgit2/v0.21.4.json) returns a 404).

Are there no API changes between 0.21.3 and 0.21.4?

**Comment by maxkorp** [comment]
tag.h and refs.h were added for sure, otherwise it seems relatively the same. I've tried generating the docs, but no matter how i configure things (or what version of docurium i grab) i get varying results from what seems typical of a "generated docs" commit on the gh-pages branch. I'm grabbing the json that generates for us to use, but having this live would be nice, since we refer to it regularly. 

I'd be happy to help with normalizing the docs, if needed.

**Comment by carlosmn** [comment]
`sys/refs.h` was fixed for inclusion in C++, but no changes to any function signature was made. The tag header was definitely not touched.

As has happened for the rest of the maintenance releases, and as is good form and required to keep the same SOVERSION, there are no changes other than bug fixes. Docurium generates documentation for each one individually because it doesn't know any better, the same reason why the release candidate also show up. In the future it will simply not show the different maintenance releases, since the whole point is that nothing changes.

**Comment by johnhaley81** [comment]
Thank you carlosmn! I was mostly concerned with the changes to `sys/refs.h` and if that actually changed the API at all.
