### ISSUE TITLE
0.22.1 fails to build with MinGW-w64 when OpenSSL is found

### ISSUE THREAD

**Issue by tkelman** [libgit2/libgit2#2850]
Full build log is here: https://gist.github.com/tkelman/4344811daaeee55aefbc
This is cross-compiled from openSUSE to Win64 (same errors for Win32 though) using this spec file: https://build.opensuse.org/package/view_file/home:kelman:branches:windows:mingw:win64/mingw64-libgit2/mingw64-libgit2.spec?expand=1

Lots of errors from `openssl_stream.c`, largely due to something funny going on with the `X509_NAME` define in the openssl (1.0.1k) headers. I tried libressl, but that had similar-looking issues having to do with X509 defines much earlier in the build. Should this work? It did in 0.21.

**Comment by kkutsner** [comment]
@tkelman I just tried to comment out the including openssl.h header file and it worked in my case.

**Comment by carlosmn** [comment]
It *should* work, but I don't know if anybody does test that particular combination. Those errors come from the openssl headers themselves, so I don't know if there's anything we can do about it.

**Comment by jeroenooms** [comment]
I ran into the same problem using msys2.

**Comment by akikoskinen** [comment]
I ran into something similar. The root cause seems to be conflicting names in Windows and openssl headers. Openssl uses the name X509_NAME in a typedef and Windows #defines the same name to 7 (in wincrypt.h).

Openssl circumvents this in many places by first #undefing X509_NAME (and other conflicting names) before using the name: http://rt.openssl.org/Ticket/Display.html?id=1749&user=guest&pass=guest

The solution is to not include wincrypt.h after any openssl headers have been included.

I got libgit2 (tag v0.22.1 to be exact) compiled with the following modifications:
- In `src/openssl_stream.c` move all openssl includes as the last includes
- The `struct in6_addr` seemed to also not be found when compiling `src/openssl_stream.c`. I added  `#include <in6addr.h>` to `src/common.h`. I placed it after the windows.h include. It worked for me there but another location (even some other file) could be used too I guess if more appropriate.

PS. if this fix gets applied, I hope it gets cherry-picked to the maint/v0.22 branch too :)

**Comment by ethomson** [comment]
Sounds reasonable - would you mind opening a pull request with this change?  Thanks!

**Comment by kkutsner** [comment]
The suggested changes should be really cool because I was running into the same issue on Windows using Visual Studio 2013 Update 3. I did pretty similar changes, but I thought that my issue is somehow related to using my custom makefiles which I generated using premake4 tool...

**Comment by akikoskinen** [comment]
Check [comment in pull request](https://github.com/libgit2/libgit2/pull/2930#issuecomment-76359648)!
