### ISSUE TITLE
No git_index_add_frombuffer

### ISSUE THREAD

**Issue by dprofeta** [libgit2/libgit2#2876]
It is possible to create an in-memory index and to create a blob from a buffer, but I don't see any way to add the buffer to the index.
Today, we are using the treebuilder to update the repository, but the index seems more convenient to use.

Do you think it would make sense to add the ability to manipulate index only from memory object?

**Comment by ethomson** [comment]
There is no API to do this directly, at the moment, though it would be pretty straightforward.  You would need to put a blob into the object database, then call `git_index_add` to add this for you.

But this has come up a few times, and it seems like a nice API to have.  This would be a great way to contribute to the library if you were interested in opening a pull request so that we can all benefit from this!

**Comment by dprofeta** [comment]
#2879 merged
