### ISSUE TITLE
Update Travis build to also target Mac OS X on x86

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2#2920]
-DCMAKE_OSX_ARCHITECTURES=i386;x86_64

cf. https://github.com/libgit2/libgit2/pull/2917

**Comment by jeffhostetler** [comment]
It might be better to make a 386-only build and a x86_64-only build.  Then you can be guaranteed that test runs are actually testing the (only) executable in the exe.  (Since the OS will probably try to always run the 64-bit one (unless there's a magic incantation to force it to run the 32-bit one).)

**Comment by nulltoken** [comment]
:+1: Makes sense indeed

**Comment by carlosmn** [comment]
There is indeed a magic incantation to run it, given a fat binary

    arch -32 ./libgit2_clar
    arch -64 ./libgit2_clar

will run the appropriate version. We may however not be able to build clar in this situation as it would also need its dependencies to be fat, which libssh2 as built by brew is not (I'm not sure whether this is configurable)

Regarding the size mismatches which show up, it looks like clang is being overly caution there, since it just checks that the names don't match, but we have checked that the sizes do (and a simple program with a bunch of `sizeof` and printing of `X_MAX` confirms this) and clang is getting hunged up on this.

We may want to cast the arguments here to the name which we know clang will like.

**Comment by Therzok** [comment]
Since this is mostly related to lg2s, I want to mention that Mono has no out of the box 64bit support yet.

@carlosmn Supporting fat binary libssh2 would be as simple as mimicking this PR for the libssh2 keg. https://github.com/Homebrew/homebrew/pull/35271/files

**Comment by ethomson** [comment]
We've been doing some housekeeping, so I want to make sure that this remains a valuable issue.  Does anybody care about the brief window of 32-bit Intel machines that Apple produced?  If not, we should just close this and continue on, especially as our Travis builds are already slow.

**Comment by carlosmn** [comment]
It's not about 32-bit machines but 32-bit software. As @Therzok mentioned, mono and the rest of the Xamarin libraries are 32-bit, so they need to use a 32-bit libgit2. The fat binary is also the default build for the libgit2sharp build script so this build configuration is what a mac user gets out of the box. Even if we don't test a 32-bit clar, it'd be nice to compile this way to see what a lg2s user would see on their terminal.

**Comment by ethomson** [comment]
Haven’t seen any additional interest in 32 bit over the last few years; closing this.
