### ISSUE TITLE
How to clone --single-branch 

### ISSUE THREAD

**Issue by onetwopunch** [libgit2/libgit2#2924]
I can clone a branch using something like:

    git_repository *repo = NULL;
    git_clone_options opts = GIT_CLONE_OPTIONS_INIT;
    opts.checkout_branch = branch;
    err = git_clone(&repo, url, path, &opts);
    git_repository_free(repo);

But is there a way to clone the branch with only the tags from that branch's history like:

    git clone -b development https://github.com/libgit2/libgit2 --single-branch

I'd be willing to write something like this but I'd like to see if there's already a way to do this in libgit2.

**Comment by carlosmn** [comment]
Are you interested in `--single-branch` behaviour os cloning of specific tags? Those are quite different things.

You'd implement `--single-branch` the same way git does. When creating the remote (in your factory callback), you override which refspec the remote does by calling `git_remote_create_with_fetchspec()` and returning that remote to be used instead of the default one.

As for the tags, the default autotag setting is to download those tags which point to objects being downloaded, so you don't need to do anything extra, assuming that the server heeds the request. Otherwise you'd have to perform the calculation by hand.

On a more meta level, we prefer to keep issues for discussion of bugs. Questions of usage should go to StackOverflow, which is more suited for Q&A.

**Comment by onetwopunch** [comment]
Thanks for the advice, and I wasn't sure it was a usage question til now, still getting into it but enjoying the work so far! I'll make sure to ask future questions on SO.
