### ISSUE TITLE
Building for Windows Phone

### ISSUE THREAD

**Issue by jyrkij** [libgit2/libgit2#2925]
I'm interested in using [libgit2sharp](https://github.com/libgit2/libgit2sharp) for a Windows Phone / Windows application. There's an [issue](https://github.com/libgit2/libgit2sharp/issues/874) in libgit2sharp about not being able to pull in the code for .NETCore project.

If I wanted to give building libgit2 directly for Windows Phone a go how would I do that?

**Comment by ethomson** [comment]
I'm afraid that you would be the first person to try it   I think that some people have wanted to talk   I've never compiled anything for Windows Phone (or a Windows Store App) native *or* managed.

Feel free to inquire if you get stuck.  But if you get somewhere, I would love to know the steps you took to get things going!

**Comment by jeremywyman** [comment]
I'm not an expert but as I understand it it's not possible to load arbitrary native code from the Windows Phone CLR. Since libgit2sharp is a managed wrapper for the naive libgit2 binary the runtime won't load it. To make matters worse, Windows Phone and the Modern Runtimes don't expose the win32 API making a recompile of libgit2 prohibitive.

**Comment by jyrkij** [comment]
Sorry for the delayed response, it's been quite a busy time here... So do I understand @jaiwai's comment correctly? That recompiling libgit2 for Windows Phone withouth major changes is practically impossible?

**Comment by galich** [comment]
I suspect the way libgit2 handles files/network is not supported on Windows RT. It will take noticeable effort to get it compiled on the Phone or modern Windows 8.

**Comment by whoisj** [comment]
The Windows Phone and Windows Modern API are designed around giving the OS control over IO to optimize power utilization and user experience. These API are not compatible with the Win32 API.

As I understand it libgit2 only binds against the win32 API for Windows and only Phone and Modern App binaries signed by Microsoft can load the win32 API. Libgit2 isn't signed by Microsoft and therefore cannot load win32 binaries.

Therefore even if your app could load libgit2sharp and it could load libgit2, libgit2 would fail to load the necissary win32 binaries. It is very likely the Modern compiler/linker/packager is preventing you from building your app because it would fail to load at run time anyways.

**Comment by ethomson** [comment]
It seems like this is - at present - an impossible situation unless Microsoft allows p/invokes of arbitrary native code. 

However, since this seems like a reasonable step for them at some point (their competitors allow this), please do reopen this if the situation changes.
