### ISSUE TITLE
libgit2 ignores "force" refspec parameter when fetching

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2957]
I can only assume Git CLT does support `+` in a fetch refspec since that's used in the default remote refspec. However but libgit2 in `git_remote_update_tips()` and specifically in `update_tips_for_spec()` does not check the force parameter of the refspec and always force-updates the ref.

The fix is pretty easy but before sending a PR, I want to make sure this behavior is not done on-purpose.

**Comment by FintanH** [comment]
Hey @swisspol :wave: 

We just ran into this issue as well, where references were getting updated to old commits. We have a reproducible case, however, it uses `git2` (the Rust wrapper).

We're definitely be interested in seeing if this is intentional as well. Looking around we couldn't see if `refspec->force` was used anywhere else in the codebase other than the `refspec` file itself.
