### ISSUE TITLE
git_diff_tree_to_workdir with pathspec set to .cpp file iterates over invalid path

### ISSUE THREAD

**Issue by shiftkey** [libgit2/libgit2#3020]
Had a couple of GHfW users encounter this issue (also reproducible against `HEAD`, haven't checked the most recent release). Working through the root cause at the moment, I figure reporting it early doesn't hurt.

- Repository with modified `.cpp` file
- Set the file's relative path in `opts.pathspec`
- :boom: 

```
  1) Failure:
diff::workdir::cpp_file_changed [C:\code\libgit2\tests\diff\workdir.c:1725]
  Function call failed: (git_diff_tree_to_workdir(&diff, _repo, a, &opts))
  error -1 - Failed to open directory 'C:/Dev/Repos/GitHub/HashCheck/MD5FileHash./':
```

Why it's trying the filename without the extension here causes the diff generation to break. I'll bundle up this failing test and repo into a PR next, but here's the important stuff:

```
	const char *a_commit = "1107ceab8176a";
	static char *str0 [] = { "MD5FileHash.cpp" };
       
        // other setup noise 
 
	int err = git_repository_open(&_repo, "C:\\path\to\repo\");
	cl_git_pass(git_repository_index(&idx, _repo));

	a = resolve_commit_oid_to_tree(_repo, a_commit);

	git_diff_options opts = GIT_DIFF_OPTIONS_INIT;

	opts.pathspec.strings = str0; opts.pathspec.count = ARRAY_SIZE(str0);

	opts.flags = GIT_DIFF_INCLUDE_UNTRACKED
		| GIT_DIFF_RECURSE_UNTRACKED_DIRS;

        // this errors out 
	cl_git_pass(git_diff_tree_to_workdir(&diff, _repo, a, &opts));

	cl_git_pass(git_diff_foreach(
		diff, diff_file_cb, diff_hunk_cb, diff_line_cb, &exp));

	cl_assert_equal_i(1, exp.files);
```

**Comment by ethomson** [comment]
That's interesting.  Is there a `MD5FileHash.` (with the trailing dot) in the folder or is that totally bogus?

**Comment by shiftkey** [comment]
>  Is there a MD5FileHash. (with the trailing dot) in the folder or is that totally bogus?

Totally bogus - here's the failing test: https://github.com/libgit2/libgit2/compare/diff-fails-with-cpp-file

**Comment by carlosmn** [comment]
This only seems to happen on Windows. I just tried on Debian and it passes (once I initialize `exp` so there's no wild pointers).

**Comment by carlosmn** [comment]
I've been tracking down where the bad string comes from, `git_diff__from_iterators()` gets the right strings from `git_interator_current()` and it then calls `handle_matched_entries()` which advances the iterators. After the "new" iterator has advanced, we can read the bad string from there.

AFAICT this comes from whatever `fs_iterator__advance_over()` does (that's as far as I've tracked the change) but I've stopped trailing it for now. There seem to be three possible sources of data here, so one of them is bound to have had the bad path put into it.

**Comment by shiftkey** [comment]
@carlosmn I've been able to step into this failing test on Windows, I just haven't made time to go down the entirety of the rabbit hole. I'll focus on `fs_iterator__advance_over next - thanks for taking time out to dig into it.

**Comment by ethomson** [comment]
@shiftkey have you seen any more reports of this?  Did you have a failing repository that we can use to investigate this further?

**Comment by ethomson** [comment]
This is resolved in master.

It turns out that this was an interesting wrinkle in the previous implementation of directory iterators, in [`git_path_dirload_with_stat`](https://github.com/libgit2/libgit2/blob/2a06976165cd6b5d4d217f479f099112991e9cf4/src/path.c#L1184).

This function would call `git_path_dirload`, but ask it to set up a vector of members of size `git_path_with_stat` instead of *just* strings.  The idea being that it could then go back through that list and fill in the `struct stat` data associated with each path and you only need to `malloc` once.

Except that when you gave it a path filter, it only filled in the `struct stat` data for *the one path* you were interested in, as an optimization.  So all the other entries were full of garbage in their stat data.

Somehow, the directory bits were flipped on the garbage in that stat bit for `MD5FileHash.h`, so it was getting treated as [*a submodule*](https://github.com/libgit2/libgit2/blob/f7fcb18f8a7541bfc0228967fcbd916a9f515638/src/iterator.c#L1373) since it was both a directory on disk and existent in the index (which directories never are otherwise).

We've gutted the `git_path_dirload_with_stat` handling completely in the meantime, so this doesn't occur anymore.

I'm surprised that this was consistently occurring, but I did *not* dig in to figure out what random trash was consistently making `MD5FileHash.h` be treated as a directory, and while I bet it's interesting, I'm going to leave it as an exercise for the reader.

**Comment by shiftkey** [comment]
@ethomson apologies for not coming back to this. Thanks for following up.

I had a branch locally with a failing repo, and thought I opened a PR to call it out, but I guess not. Anyway, I had a new report of this come through from a user so I checked against the latest tip of `libgit2sharp` - no error. Checked the original repro - no error.
