### ISSUE TITLE
A born of a new contribution - libgit and C++Builder (and Total Commander)

### ISSUE THREAD

**Issue by Darthholi** [libgit2/libgit2#3044]
Dear guys! THank you wery much for making libgit2.

I would like to make a branch for compilation using Borland C++ builder in the future, but now I have only a testing project - Git incorporation into Total Commander on Windows.

Would you please add the link https://github.com/Darthholi/WDX_GitCommander into set of existing projects and maybe a hint in between the compilation hints? (I will do new branch stuff later.)

I dont want to propagate myself, but I would love to make the life (of possible future somebody trying to compile it using C++Builder) easier and thats why the project is there and why I write you.

Thanks (because my extension is working like charm! :) )

**Comment by carlosmn** [comment]
I don't know which "existing projects" list you mean. We keep a list of bindings for different languages, but not of tools which provide Git integration via libgit2.

**Comment by Darthholi** [comment]
In that case Iam mistaken and I apologize (maybe I have seen it somewhere else than on Github).

If you have somewhere to put it (i mean a link), put it there, otherwise leave it please :) (my only point is to make it a bit easier for somebody trying to achieve the same. If only it would be like someone asking you in one year to compile it and you can tell him, try these sources there and it would spare you and the person some time, it is success!)

Have a nice day :)

**Comment by ethomson** [comment]
Hi - I hope that you are finding libgit2 useful in your project.

At present, we have decided to support *only* CMake to build libgit2.  CMake *does* support "Borland Makefiles" but does not support "Borland C++ Builder" project files.

I'm embarrassed to say that I'm not very familiar with Borland, so I'm not sure what the difference is.  However I do understand that using Borland C++ Builder project files may be very beneficial to you.

If CMake cannot produce these project files *and* having them as part of the libgit2 project would be beneficial to you, we may be able to manage a mechanism by which they are technically not supported (we really only want to support CMake, which is already an expensive proposition).  But we may be able to keep them in a `contrib` directory inside the repository that might make it helpful for you (and others).

If this seems like a reasonable solution, it might be worth discussing this in a pull request instead of an issue.  However this is not something that we have the expertise or resources to work on, so I'm going to close this issue.

Thanks!
