### ISSUE TITLE
Is it possible to copy code from libgit2?

### ISSUE THREAD

**Issue by tony** [libgit2/libgit2#3050]
Thank you for the project, I'm using it to study C programming and am very impressed with the code.

It says on the homepage a main feature of libgit2 is permissively licensed. I am to understand normal git is a pure GPL project and I can't copy code from it (https://github.com/libgit2/libgit2/blob/master/CONTRIBUTING.md#porting-code-from-other-open-source-projects).

Before I get too invested (I program python where GPL seldom comes up), does libgit2's license allow porting pieces of code from libgit2 into commercial software? What about other open source projects? Hobby projects? Web tutorials?

**Comment by arthurschreiber** [comment]
`libgit2` is licensed under the GPL as well, but with the additional linking exception, so all the same restrictions apply as with any other software licensed under the GPL, except that software that links to libgit2 does not have to be GPL itself. I am not a lawyer, so you probably should do more extensive  research on this.

**Comment by tony** [comment]
So copying the code is not allowed, just like with normal git?

If permissiveness if one of the goals of libgit2, has the project considered a more liberal license that could allow that? What could be the disadvantage if someone were to copy code from libgit2? Is it too late to consider changing  the license, or to make further contributions dual-licensed?

**Comment by arthurschreiber** [comment]
Why would you want to copy code instead of just using the library directly?

Switching to a more liberal license would require contacting all the people that contributed to libgit2 and ask them to agree to relicensing their contribution, which I doubt will happen.

**Comment by ethomson** [comment]
Disclaimers:

1. I am not a lawyer
2. Even if I was, I am not *your* lawyer.

So do not consider this a legal opinion.

However, the goal of the linking exception is that you are allowed to use libgit2 in an application, even if that application is closed source or proprietary.

Many people do include libgit2 in their proprietary, closed source application.

If, however, you do choose to do this, you need to follow the requirements set forth by the license, for example, making any changes available to others.

It seems to me that it would be much, much easier to comply with this license if you do not break portions out and intermingle it with your own code.  Then you may be expected to provide that aforementioned "your own code".

You mentioned "hobby code", without a stronger definition it will be difficult to judge what you mean by that.  However do note that the GPL requires you to distribute the source to those people to whom you distribute your binaries.  If that group is merely yourself then you have satisfied the conditions.

There has been no previous talk of a different or second license.  Since we want to retain the ability to share code with git core where possible, a different license would make this very difficult.

**Comment by carlosmn** [comment]
> So copying the code is not allowed, just like with normal git?

Copying the code is explicitly allowed the license of both of these projects; but you still have to obey the rules, some of which depend on your jurisdiction.

This is not a good place to discuss the relative merits of the GPL. There are places dedicated to clearing questions about it like the [FSF's FAQ](https://www.gnu.org/licenses/gpl-faq.html). We use the GPL with the linking exception so it's easier to copy and modify code from git.

**Comment by tony** [comment]
@carlosmn :

Please don't take me the wrong way. I don't doubt your knowledge of the license, you seem familiar with it. However, at work, some manager's are suspicious kind of license. In one case, we spent the past year of our life to writing a game, when there was an LGPL project that would have saved us a week of time borrowing code from, we couldn't simply *copy* code we wanted to incorporate and give attribution to it, we could only link it.  We had to write it from scratch.

But coming from a commercial project, MIT, Apache or BSD licensed application could *only* link this application as a library. They couldn't actually copy-paste out data structures or code. For instance, if a C application for a commercial game, or a permissively licensed software project wanted to pull apart parts of libgit2 to save time writing something from scratch, we can't, boss / lawyers will say no.

**Comment by carlosmn** [comment]
This is nothing specific about the library. Especially if you're doing this in a commercial setting, talk to your lawyers about what's possible, as copyright (and in particular the GPL) depends on the jurisdiction in which you operate and how it defines "derived work".

If you're not trying to deal with git repositories but extract utility functions, as it sounds you're trying to do, I would recommend looking at klib which provides generic data structures you can use in your code (which we have also included in libgit2). Though my first recommendation is always to avoid using C as much as possible.

**Comment by tony** [comment]
Thanks for that klib advice, Carlos!  I think it'd be even permissive and less open to legal interpretation, if the license was Apache / BSD / MIT. From this conversation it seems libgit2 is staying GPL + linking exception, I respect your choice.
