### ISSUE TITLE
How to support HTTP Digest Authentication?

### ISSUE THREAD

**Issue by shinningstar** [libgit2/libgit2#3067]
It seems that libgit2 does not support HTTP Digest Authentication, is that true? Or is there a way to work around?

**Comment by ethomson** [comment]
That is true, it is not supported.  It's not really... something that anybody has ever cared about before.

Adding it should be relatively straightforward, though it raises questions like:  are you happy with only auth?  Or do you want auth with integrity?  What does your compatibility matrix look like, since nobody really seems to implement Digest fully and there are presumably effort vs completeness tradeoffs to be made.

I presume that your interest here is that you have some server that speaks Digest and you simply want to auth to it.  I think that this is a fine level of compatibility, since - again - not a super hot issue.

You should add a new auth "factory" for digest at https://github.com/libgit2/libgit2/blob/master/src/transports/http.c#L21 - presumably `git_http_auth_digest`, which would create a new authentication context for digest auth.

You should be able to look at the [Basic implementation](https://github.com/libgit2/libgit2/blob/master/src/transports/auth.c) to get an idea of how to implement a very simple auth context.  (Auth contexts are important for crazy stateful mechanisms like NTLM and Negotiate, so they're overengineered for something more simple like Basic and Digest.  So I would study the Basic implementation.)

Now, I did say that it would be straightforward, but I suspect it would be far more straightforward to just change your server to do Basic over SSL or Kerberos or something more (with apologies to @jeffhostetler ) modern.

Another alternative is that you can think about trying to use libcurl as a connection backend for HTTP(S) connections.  Since we have a pluggable transport layer, you could plug libcurl in to do all this work for you.  This isn't what *I* would advise doing, but (at the risk of speaking for him) I think that one of the other core contributors would suggest that you consider this direction.  You can plug in a new smart subtransport for HTTP(S) by following along at [`https://github.com/libgit2/libgit2/blob/master/include/git2/sys/transport.h`](https://github.com/libgit2/libgit2/blob/master/include/git2/sys/transport.h).  But again, I would put this in the way more work for the reward category just to get Digest working.

**Comment by shinningstar** [comment]
@ethomson Yes, we just have a Gerrit service which is using Digest auth. I would like to change to SSH method to access this server since I don't need to change any code. If I have time, I would try the methods you've mentioned. Thank you.

**Comment by ethomson** [comment]
That makes sense.  I'm going to reopen this (and add the handy "up for grabs" label) in case somebody else has an inkling to support this.

**Comment by carlosmn** [comment]
Having a libcurl transport is something we will likely want to have anyway, as people insist on using proxies, and there's no way we're going to include proxy support in our own transport.

**Comment by carlosmn** [comment]
There's also #2555 which is somewhat related in that it asks for capabilities it's probably not worth supporting in our won HTTP layer but which are available externally.

**Comment by ethomson** [comment]
We hit a year on this issue without it moving forward.  I'm going to close it as I think that most people really aren't looking for Digest in 2016, but please correct me if I'm wrong.
