### ISSUE TITLE
Double remote connection

### ISSUE THREAD

**Issue by Therzok** [libgit2/libgit2#3096]
Exposed through: https://github.com/libgit2/libgit2sharp/pull/1038

It seems as though `git_remote_push`, does not verify that the remote is already connected [here](https://github.com/libgit2/libgit2/blob/master/src/remote.c#L2381-L2397).

`git_remote_upload` does check for [that](https://github.com/libgit2/libgit2/blob/master/src/remote.c#L2328-L2330).

**Comment by carlosmn** [comment]
Which transport are you seeing this with?

**Comment by Therzok** [comment]
Both `https` and `ssh+scp` aka `git@github` using that specific way of pushing with libgit2sharp.

**Comment by carlosmn** [comment]
There is no such thing as `ssh+scp`, using `git@github.com:blah/bleh` is ssh.

**Comment by Therzok** [comment]
I had the remote callback called twice, so I guessed it was doing a double connection.

**Comment by nulltoken** [comment]
#3156 is slightly related

**Comment by MrHacky** [comment]
i've ran into this as well using the pure C api to push to 'ssh://' urls.

Due to the way my code is structured it would be convenient to be able to only supply credentials in the git_remote_connect call, and have git_remote_push reuse the authenticated connection.

However this doesn't work and git_remote_push fails. I've worked around it by removing the git_remote_connect call and passing the credentials in git_remote_push.

**Comment by carlosmn** [comment]
If you do need to split out the individual steps, then do that, but then don use `git_remote_push()`. This issue only happens when you cross  the layers for a single fetch.
