### ISSUE TITLE
How to unpack a pack file into commits?

### ISSUE THREAD

**Issue by yongthecoder** [libgit2/libgit2#3098]
An odb backend needs to implement "writepack" in order to be able to fetch remotes.
 
However, currently there is no API that can be used to read a pack file stream and read all objects that need to be saved to the object database.

It seems "indexer" reads and processes pack file stream, but it contains other stuff and cannot be directly used by an odb backend that doesn't understand pack file.

It would be nice to have a utility writepack implementation for odb backends to use.

Is anyone working on a similar plan? Or any suggestion about how to do this efficiently?

**Comment by carlosmn** [comment]
You *have* to understand packv2 in order to perform a fetch, and this is what the indexer gives you. The way I've performed fetches into custom databases in the past is to store the index in a temporary location (which let us reuse the indexer with its thin pack support and error checking) and then use `git_odb_backend_one_pack()` and `git_repository_wrap_odb()` to go through the objects stored in the packfile and insert them into the custom database.

If you have custom needs and cannot put your data through the indexer, then you have very custom needs and it doesn't seem likely that a general solution would serve you.

**Comment by yongthecoder** [comment]
@carlosmn Thanks a lot for the hint.
"The way I've performed fetches into custom databases in the past". Would you mind sharing the code if you still have it?
Also,   will indexer do any indexing/hashing job that is not necessary for a custom database?

**Comment by carlosmn** [comment]
That code is not public, but you can see the technique in the [tests for this feature](https://github.com/libgit2/libgit2/blob/master/tests/odb/packed_one.c) which I built for this. After indexing the file, you can simple access it like any other odb and use a foreach or similar to insert objects into your database.

There is technically some work you could avoid if you were writing your own purpose-built version, such as writing out the index file, but if you didn't do that, you'd have to handle the offsets manually instead of taking advantage of the code to read packfiles that's already written and tested.

You might also be able to get away with not injecting the missing bases on a thin pack in a purpose-built indexer, but then you still have to have your own packfile reading code which would know how to read packfiles which are technically invalid.

**Comment by yongthecoder** [comment]
@carlosmn thank you so much!

**Comment by yongthecoder** [comment]
@carlosmn excuse me for another question. do you think it is doable to only save the pack file and then use git_pack_foreach_entry to list all the objects and insert to the custom database?

**Comment by carlosmn** [comment]
You need the index file in order to know what's in the pack, which goes back to my last post.

**Comment by yongthecoder** [comment]
I hacked the indexer, and made it not do CRC nor write to .idx file (nor rename the pack file). It worked basically in my test. But I'm not sure if it is correct or right. In my testing, the downloaded packs are small, so this doesn't show any performance gain. So I sort of think it is unnecessary. Just post here just in case it is useful for anyone.

https://github.com/yongthecoder/libgit2/commit/c7b2d482be82ece13ac157d523bce9cd38d9e4fa
