### ISSUE TITLE
libgit2 returned: 'htdocs/.../foundation.css' appears as both a file and a directory

### ISSUE THREAD

**Issue by andig** [libgit2/libgit2#3114]
Error happens when trying to add new files using TortoiseGit. I'm lost as to why this error happens. `foundation.css` is a file, platform is Win64. Trying to clean any remnants from index via

	>git rm htdocs/frontend/vendor/foundation/css/foundation.css
	fatal: pathspec 'htdocs/frontend/vendor/foundation/css/foundation.css' did not match any files

is unsuccessful.

**Comment by carlosmn** [comment]
If you're having issues with TortoiseGit, I would recommend that you report issues to them. They would know what code they're running through libgit2 and if it does turn out to be a libgit2 error they can report it to us.

That said, since you're here, it would be useful to know which files you're trying to add, and what the current state of your index is. If you run `git ls-files -s` you should see `foundation.css` as a directory if my assumptions are correct. But it's just an assumption, as we don't know what code TortoiseGit is running, or even what files you were trying to add or how you were trying to add them.

**Comment by andig** [comment]
It turns out I've caused the problem. The branch is quite old. I didn't realize that I had added a git submodule for `htdocs/frontend/vendor/foundation` ages ago.

I've noticed I got `git submodule` warnings similar to http://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule.

Fixed those using http://stackoverflow.com/questions/4161022/git-how-to-track-untracked-content/4162672#4162672.

After that, the `git add` error is gone as well. It seems the problem was caused by a gitlink.

Thanks a lot for your quick reply, much appreciated!
