### ISSUE TITLE
small memory leaks in testsuite on Windows because cl_getenv allocates return value

### ISSUE THREAD

**Issue by jeffhostetler** [libgit2/libgit2#3164]
I just noticed that cl_getenv() on Windows allocates a buffer and returns it, whereas the other platforms just return the const pointer from the system.  There are lots of calls in the testsuite that don't conditionally free the string.

We should probably add a comment to the prototype for cl_getenv() to explain that.

**Comment by ethomson** [comment]
Interesting.  I wonder why we're doing that at all and not just calling the POSIXy `getenv`?  I suppose so that people with funny characters in the directories can set a temp path...  (This seems like a reasonable thing for us to support.)

Another option is to keep `cl_getenv` POSIXy and return some static TLS buffer.  Obviously it could only be so big, and we'd have to crash or something if that assumption ever went unsatisfied, which is terribly disappointing.  This would only be preferable if we assume that people writing tests will forget that `cl_getenv` is funny and the return value needs to be freed.

Obviously that would be caught quickly by valgrind and friends, though.

I'm really just thinking out loud.  I have almost no preference at all, but I think `cl_getenv` data needing `free`d is probably the right approach.  @carlosmn ?

**Comment by carlosmn** [comment]
You have to assume that the POSIXy version of `getenv` re-uses the same static buffer, so we should be able to reimplement that in our Windows version just by having a global `git_buf`and have nothing break.

IIRC Windows' own `getenv()` has odd semantics when combined with the setter which we use.

**Comment by carlosmn** [comment]
This brings up that our clone tests assume that you can keep a reference to the `getenv`-returned buffer, which is not quite right, so doing a `strdup` on the returned buffer (assuming it's non-`NULL`) would make sense.

But I think it might be worth taking the opposite approach and assume the returned buffer is a single static one, so we should `strdup` when we need to and leave it alone otherwise.

**Comment by ethomson** [comment]
I'm inclined to drop `cl_getenv` entirely and create `p_getenv` in libgit2 itself that returns a heap allocated string from TLS.  `git_libgit2_shutdown` can clean them up easily enough.

**Comment by carlosmn** [comment]
Sure, that works.

**Comment by jeffhostetler** [comment]
Or maybe have cl_getenv take a git_buf* argument and return an int error code instead.  That would give it a common usage pattern with other lg2 routines. Although it would deviate from the usual libc pattern.

**Comment by ethomson** [comment]
I think we should drop `cl_getenv` entirely and use a `p_getenv` that does UTF16 -> UTF8.  That we haven't been bitten by using the ANSI version yet in the library itself is fortunate (we don't operate on paths or the like).

I think that there's a good chance that we would eventually get bit by this - I didn't remember that our getenv is deficient on Windows.  So if we're doing work, I think that we should combine these into a single function.

We could make this posixy or not.  I lean toward something posixy only to fit the existing pattern but either way is reasonable I think.

-ed

**Comment by jeffhostetler** [comment]
I'm OK with either approach.  Good point about core (rather than just tests) needing UTF16 treatment.

**Comment by jeffhostetler** [comment]
I think this has been addressed by #3288 so I'm going to close this.
