### ISSUE TITLE
path_repository and custom backend

### ISSUE THREAD

**Issue by leoyanggit** [libgit2/libgit2#3266]
Per my understanding `path_repository` is required for the index file and some other stuff like `rebase-merge` dir etc. But I can't find a way to set repository path for a custom backend unless I create a filesystem backend repository with `git_repository_init()` or something like that and then call `git_repository_set_odb()` with my custom backend. The drawback of this way is that it creates a lot of useless files/dirs inside `.git` dir, which is really confusing. I found we have `git_repository_path()` but I can't find `git_repository_set_path()` or something like that. I did find `git_repository_workdir()` and `git_repository_set_workdir()`, which is good. Is there a cleaner way to set the repository path for a custom backend or am I missing something?

**Comment by carlosmn** [comment]
The repository's path belongs solely to the repository. A backend should have no way to tell the repository to change where it thinks it lives. A backend cannot change this idea.

**Comment by ethomson** [comment]
So it sounds to me like you're trying to set custom backends and invoke some functionality that expects to be able to write into the repository directory...  You mention rebase explicitly, so let's use that as an example:  rebase is really aimed at being compatible with core git and writing to the repository directory in a wholly compatible way.  If you don't require that compatibility (and it sounds like you don't, since you're using custom backends) then I think that the best thing to do would be to just use one of the mechanisms that can work in a completely in-memory scenario.

For example: rebase is really just a sequence of cherry-picks, you can simply drive `git_cherrypick_commit`.

If you describe better what you're trying to do, we might be able to provide some better advice.

**Comment by leoyanggit** [comment]
>The repository's path belongs solely to the repository. A backend should have no way to tell the repository to change where it thinks it lives. A backend cannot change this idea.

Agreed.  But I'm not saying that a backend API should take the repository path. There should be a clean way to specify the repository path for a repository with custom backend to make the current implementation of rebase work cleanly. The workaround I mentioned is not a clean way though.

**Comment by leoyanggit** [comment]
> I think that the best thing to do would be to just use one of the mechanisms that can work in a completely in-memory scenario.

I really wish we had in-memory implementation, as in merge, of rebase. The merge API is really cool because I can choose to do merge in an in-memory index.

> For example: rebase is really just a sequence of cherry-picks, you can simply drive git_cherrypick_commit.

I could. It means writing part of the rebase logic (although just walking in the tree) in the user's code. Since we already have rebase, I wonder why rewrite part of its logic in stead of making rebase work with custom backends.

> If you describe better what you're trying to do, we might be able to provide some better advice.

Basically I wish rebase worked with a custom backend by either not requiring a repository path (a likely implementation is in-memory) or at lest enabling the user specify a repository path in a clean way.

**Comment by carlosmn** [comment]
>Basically I wish rebase worked with a custom backend by either not requiring a repository path

There seems to be some confusion here about how the backends work. Having your own odb backend doesn't mean that you can't have a repository path. If you *do* have a Git repository on disk, you should still open it with `git_repository_open()` and if you have a custom odb, you can replace it via `git_repository_set_odb()`.

The rebase functionality will then behave as normal and will ask your object db for the objects instead of using the default disk-based one.

**Comment by ethomson** [comment]
> I really wish we had in-memory implementation, as in merge, of rebase. The merge API is really cool because I can choose to do merge in an in-memory index.

As I mentioned, that's just cherry-pick isn't it?  Rebase is mostly just a mechanized cherry-picker, and we do have in-memory cherry-pick.

There are various implementation details about rebase (like detaching `HEAD`) that are important for working with a workdir, but don't seem to make much sense when you're not.

**Comment by leoyanggit** [comment]
> If you do have a Git repository on disk, you should still open it with git_repository_open() and if you have a custom odb, you can replace it via git_repository_set_odb().

I don't want a regular Git repository in the first place. I want start my repository with my custom backend in the first place.

**Comment by ethomson** [comment]
> I don't want a regular Git repository in the first place because a regular one means having useless files/dirs created by git_repository_init or whatever. I want start my repository with my custom backend in the first place.

They're not useless...  they're the files that make an on-disk repository a repository.  You're proposing a function that sets the repository path, but then *doesn't make that a repository*.

It sounds to me like what you really want is to set some temporary directory where things like rebase can drop their files, because you don't want to deal with them.  In fact you don't want them at all, right?  You just want them to go some place where you can clean them up and never have to worry about them, is that roughly accurate?

Except that these files are all implementation details *of rebase*.  Rebase's sole existence is to be able to run from the command-line and be continuable, and that's what those files allow for.

If you don't want this (and it sounds like you don't) then you should be using cherry-pick instead.  Plus if you're building some automation component (which is the general case for database-backed repositories) then doing things the rebase-way of detaching HEAD sounds like the sort of thing that you *don't* want to do (though I concede that your ODB backend could be smart enough to not propagate this change, but still, ugh.)

Is there some reason that cherry-pick *won't* work for you?

Are there other places where this is causing problems?

**Comment by leoyanggit** [comment]
I've already switched to cherry-pick although I could live with the downstream fork with the patch. It's cleaner and less code in my use case. I thought it might be useful to make rebase work with a custom backend that way and benefits others. But seems like nobody is using libgit2 that way. Thanks for the responses guys.
