### ISSUE TITLE
Git Smart HTTP with HTTP/2.0

### ISSUE THREAD

**Issue by fcharlie** [libgit2/libgit2#3295]
As we known, HTTP/2.0 has been released.   All Git-Smart-HTTP are currently implemented using HTTP/1.1.  
Frequently used Git developers often feel Git HTTP protocol is not satisfactory, slow and unstable.This is because the HTTP protocol itself decides  

When HTTP/2.0 is published. We might be able to git developers jointly, based on HTTP/2.0 Git-Smart-HTTP service and client support.

HTTP/2.0: [https://tools.ietf.org/html/rfc7540](https://tools.ietf.org/html/rfc7540)
Github Mirror: https://httpwg.github.io/specs/rfc7540.html

HTTP/2.0 has *Flow Controller*  like SSH, 
HTTP/2.0 has *Server Push* POST upload-pack can download large more  object-pack   
......

libcurl now has begun to support HTTP/2.0, git is also using curl, as well libgit2 may use libcurl

I suggest the libgit2 of developer joint developer of git and jgit developers discussion based on HTTP/2.0 Git-Smart-HTTP

Now Subversion developer begin write a New HTTP Protocol for svn ("HTTP v2"):      http://svn.apache.org/repos/asf/subversion/trunk/notes/http-and-webdav/http-protocol-v2.txt

What about git ?

**Comment by linquize** [comment]
does anyone open the discussion about HTTP2 in git's mailing list? git@vger.kernel.org

**Comment by fcharlie** [comment]
@linquize I post email to git@vger.kernel.org  failed

**Comment by carlosmn** [comment]
There aren't many features of HTTP2 that the Git Smart Protocol can make use of. The multiple streams could be useful, but Git already does that in the protocol. You cannot use the server-push feature because the server doesn't know what the client is going to ask for, that's why there may be multiple rounds of negotiation.

The one feature which I believe could be of use is the two-way communication, which would let us do away with the stateless workarounds, though that largely does away with the HTTP semantics.

While libgit2 can use curl, we do not use it to speak HTTP as it does not present certificates reliably across crypto backends and its "easy" interface works quite exactly opposite to how our I/O is set up. If the Git protocol gets specified over HTTP2 we will have to revisit how we deal with curl, but until then we'll keep talking HTTP1.

The second version of the Git protocol is being discussed right now, and there was some talk of making it HTTP2-aware, so it can make use of the escape hatch and talk directly to the client in a stateful manner. But the place to discuss these things is the git mailing list, not this issue tracker.

If the mailing-list server doesn't let your email through, it's likely that you're sending it using HTML. The list only accepts plain-text email.

**Comment by fcharlie** [comment]
@carlosmn Thanks
