### ISSUE TITLE
libgit2 build failing on Mac OS X 10.10.4 with XCode 6.4

### ISSUE THREAD

**Issue by odysseus9672** [libgit2/libgit2#3296]
I'm building the julia programming language, which depends on libgit2, on a Mac OS X 10.10.4 machine with XCode 6.4 installed. I also have a current, and freshly compiled from scratch, install of fink that supplies the cmake libgit2 needs. The commit of libgit2 that julia is trying to build is 159061a8ce206b694448313a84387600408f6029. The build fails at the linking stage with:

Linking C shared library libgit2.dylib
/sw/bin/cmake -E cmake_link_script CMakeFiles/git2.dir/link.txt --verbose=1
/usr/bin/clang -m64 -D_GNU_SOURCE -Wall -Wextra  -fvisibility=hidden -fPIC -Wno-missing-field-initializers -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-const-variable -Wno-unused-function -Wno-deprecated-declarations -O3 -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 23.0.0 -current_version 0.23.0 -o libgit2.0.23.0.dylib -install_name /Users/sean/juliaLang/julia/deps/libgit2/build/libgit2.23.dylib CMakeFiles/git2.dir/src/annotated_commit.c.o CMakeFiles/git2.dir/src/attr.c.o CMakeFiles/git2.dir/src/attr_file.c.o CMakeFiles/git2.dir/src/attrcache.c.o CMakeFiles/git2.dir/src/blame.c.o CMakeFiles/git2.dir/src/blame_git.c.o CMakeFiles/git2.dir/src/blob.c.o CMakeFiles/git2.dir/src/branch.c.o CMakeFiles/git2.dir/src/buf_text.c.o CMakeFiles/git2.dir/src/buffer.c.o CMakeFiles/git2.dir/src/cache.c.o CMakeFiles/git2.dir/src/checkout.c.o CMakeFiles/git2.dir/src/cherrypick.c.o CMakeFiles/git2.dir/src/clone.c.o CMakeFiles/git2.dir/src/commit.c.o CMakeFiles/git2.dir/src/commit_list.c.o CMakeFiles/git2.dir/src/config.c.o CMakeFiles/git2.dir/src/config_cache.c.o CMakeFiles/git2.dir/src/config_file.c.o CMakeFiles/git2.dir/src/crlf.c.o CMakeFiles/git2.dir/src/curl_stream.c.o CMakeFiles/git2.dir/src/date.c.o CMakeFiles/git2.dir/src/delta-apply.c.o CMakeFiles/git2.dir/src/delta.c.o CMakeFiles/git2.dir/src/describe.c.o CMakeFiles/git2.dir/src/diff.c.o CMakeFiles/git2.dir/src/diff_driver.c.o CMakeFiles/git2.dir/src/diff_file.c.o CMakeFiles/git2.dir/src/diff_patch.c.o CMakeFiles/git2.dir/src/diff_print.c.o CMakeFiles/git2.dir/src/diff_stats.c.o CMakeFiles/git2.dir/src/diff_tform.c.o CMakeFiles/git2.dir/src/diff_xdiff.c.o CMakeFiles/git2.dir/src/errors.c.o CMakeFiles/git2.dir/src/fetch.c.o CMakeFiles/git2.dir/src/fetchhead.c.o CMakeFiles/git2.dir/src/filebuf.c.o CMakeFiles/git2.dir/src/fileops.c.o CMakeFiles/git2.dir/src/filter.c.o CMakeFiles/git2.dir/src/fnmatch.c.o CMakeFiles/git2.dir/src/global.c.o CMakeFiles/git2.dir/src/graph.c.o CMakeFiles/git2.dir/src/hash.c.o CMakeFiles/git2.dir/src/hashsig.c.o CMakeFiles/git2.dir/src/ident.c.o CMakeFiles/git2.dir/src/ignore.c.o CMakeFiles/git2.dir/src/index.c.o CMakeFiles/git2.dir/src/indexer.c.o CMakeFiles/git2.dir/src/iterator.c.o CMakeFiles/git2.dir/src/merge.c.o CMakeFiles/git2.dir/src/merge_file.c.o CMakeFiles/git2.dir/src/message.c.o CMakeFiles/git2.dir/src/mwindow.c.o CMakeFiles/git2.dir/src/netops.c.o CMakeFiles/git2.dir/src/notes.c.o CMakeFiles/git2.dir/src/object.c.o CMakeFiles/git2.dir/src/object_api.c.o CMakeFiles/git2.dir/src/odb.c.o CMakeFiles/git2.dir/src/odb_loose.c.o CMakeFiles/git2.dir/src/odb_mempack.c.o CMakeFiles/git2.dir/src/odb_pack.c.o CMakeFiles/git2.dir/src/oid.c.o CMakeFiles/git2.dir/src/oidarray.c.o CMakeFiles/git2.dir/src/openssl_stream.c.o CMakeFiles/git2.dir/src/pack-objects.c.o CMakeFiles/git2.dir/src/pack.c.o CMakeFiles/git2.dir/src/path.c.o CMakeFiles/git2.dir/src/pathspec.c.o CMakeFiles/git2.dir/src/pool.c.o CMakeFiles/git2.dir/src/posix.c.o CMakeFiles/git2.dir/src/pqueue.c.o CMakeFiles/git2.dir/src/push.c.o CMakeFiles/git2.dir/src/rebase.c.o CMakeFiles/git2.dir/src/refdb.c.o CMakeFiles/git2.dir/src/refdb_fs.c.o CMakeFiles/git2.dir/src/reflog.c.o CMakeFiles/git2.dir/src/refs.c.o CMakeFiles/git2.dir/src/refspec.c.o CMakeFiles/git2.dir/src/remote.c.o CMakeFiles/git2.dir/src/repository.c.o CMakeFiles/git2.dir/src/reset.c.o CMakeFiles/git2.dir/src/revert.c.o CMakeFiles/git2.dir/src/revparse.c.o CMakeFiles/git2.dir/src/revwalk.c.o CMakeFiles/git2.dir/src/settings.c.o CMakeFiles/git2.dir/src/sha1_lookup.c.o CMakeFiles/git2.dir/src/signature.c.o CMakeFiles/git2.dir/src/socket_stream.c.o CMakeFiles/git2.dir/src/sortedcache.c.o CMakeFiles/git2.dir/src/stash.c.o CMakeFiles/git2.dir/src/status.c.o CMakeFiles/git2.dir/src/stransport_stream.c.o CMakeFiles/git2.dir/src/strmap.c.o CMakeFiles/git2.dir/src/submodule.c.o CMakeFiles/git2.dir/src/sysdir.c.o CMakeFiles/git2.dir/src/tag.c.o CMakeFiles/git2.dir/src/thread-utils.c.o CMakeFiles/git2.dir/src/tls_stream.c.o CMakeFiles/git2.dir/src/trace.c.o CMakeFiles/git2.dir/src/transaction.c.o CMakeFiles/git2.dir/src/transport.c.o CMakeFiles/git2.dir/src/tree-cache.c.o CMakeFiles/git2.dir/src/tree.c.o CMakeFiles/git2.dir/src/tsort.c.o CMakeFiles/git2.dir/src/util.c.o CMakeFiles/git2.dir/src/vector.c.o CMakeFiles/git2.dir/src/zstream.c.o CMakeFiles/git2.dir/src/transports/auth.c.o CMakeFiles/git2.dir/src/transports/auth_negotiate.c.o CMakeFiles/git2.dir/src/transports/cred.c.o CMakeFiles/git2.dir/src/transports/cred_helpers.c.o CMakeFiles/git2.dir/src/transports/git.c.o CMakeFiles/git2.dir/src/transports/http.c.o CMakeFiles/git2.dir/src/transports/local.c.o CMakeFiles/git2.dir/src/transports/smart.c.o CMakeFiles/git2.dir/src/transports/smart_pkt.c.o CMakeFiles/git2.dir/src/transports/smart_protocol.c.o CMakeFiles/git2.dir/src/transports/ssh.c.o CMakeFiles/git2.dir/src/transports/winhttp.c.o CMakeFiles/git2.dir/src/xdiff/xdiffi.c.o CMakeFiles/git2.dir/src/xdiff/xemit.c.o CMakeFiles/git2.dir/src/xdiff/xhistogram.c.o CMakeFiles/git2.dir/src/xdiff/xmerge.c.o CMakeFiles/git2.dir/src/xdiff/xpatience.c.o CMakeFiles/git2.dir/src/xdiff/xprepare.c.o CMakeFiles/git2.dir/src/xdiff/xutils.c.o CMakeFiles/git2.dir/src/unix/map.c.o CMakeFiles/git2.dir/src/unix/realpath.c.o CMakeFiles/git2.dir/deps/http-parser/http_parser.c.o -lcurl /usr/lib/libz.dylib -framework Security -framework CoreFoundation -L/usr/lib -liconv 
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in path.c.o
  "_libiconv_close", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_clear in path.c.o
      _git_path_diriter_free in path.c.o
      _git_path_dirload in path.c.o
  "_libiconv_open", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_init_precompose in path.c.o
      _git_path_diriter_init in path.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/git2.dir/build.make:3289: recipe for target 'libgit2.0.23.0.dylib' failed

**Comment by carlosmn** [comment]
```
"_libiconv", referenced from:
_git_path_iconv in path.c.o
"_libiconv_close", referenced from:
_git_path_direach in path.c.o
_git_path_iconv_clear in path.c.o
_git_path_diriter_free in path.c.o
_git_path_dirload in path.c.o
"_libiconv_open", referenced from:
_git_path_direach in path.c.o
_git_path_iconv_init_precompose in path.c.o
_git_path_diriter_init in path.c.o
ld: symbol(s) not found for architecture x86_64
```

This error message is rather suspect. We don't use functions called `libcionv_open` but `iconv_open`, and the linker is receiving the right message. Is it possible that you have another version of libiconv installed where the C compiler would search for its headers?

**Comment by tkelman** [comment]
A full build log including all current cmake arguments that were used is posted here https://gist.github.com/anonymous/4338f1a8c3ebf8dbf470

We saw something very similar once before in https://github.com/JuliaLang/julia/issues/8937 that turned out to be something having to do with an outdated copy of fink. @odysseus9672 mentioned that he has fink on his machine, but apparently all up to date.

**Comment by odysseus9672** [comment]
Yes, that is entirely possible. I have a Fink libiconv, but it's entirely in the /sw/ directory tree. I don't know how that can be creeping in unless the Fink cmake is adding it automatically. I can tell you the content of any environment variable that gets set in the terminal, if you tell me what variables are relevant.

**Comment by carlosmn** [comment]
The compiler arguments from the gist include `-I/sw/include` in each invocation, so if there's `/sw/include/iconv.h` it would pick that instead of the Apple-provided one, but the linker is still apparently choosing the iconv from `/usr/lib`

This extra include directives used to come from the OpenSSL dependency but we don't have that naymore, so I don't know where it's coming from. If you look for `/sw/include` in `CMakeCache.txt`, it should say what caused the inclusion of that search path.

**Comment by odysseus9672** [comment]
Here's another gist of the CMakeCache.txt: https://gist.github.com/odysseus9672/7d99e43676d30d8725fb

The only lines that mention /sw/include are Curl related. Not sure why it's going for the Fink Curl and not the builtin one. OSX still comes with Curl, right?

**Comment by carlosmn** [comment]
I'm only on 10.9 but I'm pretty sure it does still come with curl. The reason it does is likely because we're relying on `pkg-config` to find it, and yours seems to come from Fink so its likely that it's set to read the files found in `/sw/lib/pkgconfig` before those in `/usr/lib/pkgconfig`.

**Comment by odysseus9672** [comment]
Ok, it looks like the only workaround is to is to remove Fink related stuff from my PATH, and in order to do that I'm going to have to install cmake outside of Fink.

**Comment by tkelman** [comment]
Is there a way to tell cmake not to use pkg-config to find things? We have a similar problem (https://github.com/JuliaLang/julia/issues/10010) with multi-arch builds on debbuntu using `-m32` to compile 32 bit libgit2 from 64 bit linux, where the root cause was pkg-config picking up the 64 bit openssl even though cmake on its own would have been smart enough to do the right thing.

**Comment by odysseus9672** [comment]
I can now rule out my Fink install as a cause of the problem. I installed the current cmake into /usr/local, and set my PATH as:
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

Here's a new gist that shows basically the same error crops up: https://gist.github.com/odysseus9672/24083f472ac83192b269

And a gist showing the new CMakeLists.txt: https://gist.github.com/odysseus9672/ffc9648f731e3e5c0a46

**Comment by odysseus9672** [comment]
Ok, I've removed the Fink setup script from my .profile, and I still get the error. Moving /sw fixes the issue, and the libgit2 build succeeds. I can't understand why, because I did the configure; make; sudo make install for cmake in a session without the fink configure script, too. So I cannot fathom how or why it's reaching into the /sw directory when it shouldn't even know it exists.

Does this mean we need to push this issue upstream to cmake? It would be nice to have an EXCLUDE directive where any include or lib directive (-L/path, -I/path) that matches the EXCLUDE directive gets removed.

**Comment by odysseus9672** [comment]
Ok, I've searched around for libiconv and libgit2 and it appears this this is a resurfacing of an old issue libgit2 had. Here are a couple of relevant links:

https://github.com/libgit2/libgit2/issues/2918
https://github.com/libgit2/libgit2/pull/3092

Perhaps it's time to close this and reopen one of those old issues? Or re-title this one.

**Comment by carlosmn** [comment]
The CMake installation wouldn't be an issue, it would be it using the `pkg-config`. There have indeed been issues related to iconv, because some port systems install their own version in a default search path instead of putting it in a place where you have to ask for it. To boot those didn't work correctly (at least for what we need iconv to do). The build system then picks those up instead of the one which ships with the OS. That's the reason for specifying iconv directly on OS X instead using pkg-config to look for it.

It should build if you disable looking for libcurl until we figure out what to do there. We might have to specify the library directly on OS X as well instead of relying on pkg-config to tell us cross-platform. But this doesn't solve the problem of a pkg-config existing which expects to be used by a different environment. If you install a libssh2 via Fink, we'd likely end up with the same problem. The only system I've seen which handles this correctly is homebrew, which installs libraries in their own prefix, making `-I` directives only apply for a single library, instead of assuming everything is part of the same alternate system.

**Comment by odysseus9672** [comment]
Thanks for the info. I'll suggest such a feature for fink, but I don't know how realistic it is given their reliance on Debian and apt-get. I also looked at the packages homebrew has available, and there are too many recipes missing that are essential to what I do to switch.

**Comment by howarthjw** [comment]
Are you sure that you don't have something setting CPATH or C_INCLUDE_PATH to point at fink's includes? Stock fink won't be forcing its headers on anyone.

**Comment by tkelman** [comment]
@odysseus9672 just curious, which kinds of libraries are you looking for that fink has but homebrew doesn't? For homebrew, a fair number of them might be out in "taps" like homebrew-science.

It looks like part of the problem here comes from trying to mix and match libraries from different sources, perhaps some cmake logic saying to only use libraries from fink (or other sources like macports or homebrew) if every external library comes from the same source could help?

**Comment by odysseus9672** [comment]
@howarthjw, I'm sure that those particular variables are not set, even when I run the fink init script. I looked through the environment variables that are set, and none of them have an include dir in them. When I disable the fink init script, both to build and install a non-fink cmake and then to build libgit2, I still get the problems outlined. So there is something weird outside of fink that is dragging it in. Specifically, it looks like cmake is at fault. This is the first occurance of /sw in the build process when I perform a "no fink init script" clean install from front to back.

Re-run cmake no build system arguments
-- The C compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /sw/bin/pkg-config (found version "0.28") 

If I move Fink's directory to a different location after all of this the build succeeds. Avoiding that much rigamarole is why I use package managers in the first place. 

Thanks to a suggestion by Alexander Hansen on the fink-users mailing list, I uninstalled the package that represents the libiconv headers, and that fixed the problem.

**Comment by nieder** [comment]
The problem lies someplace in cmake/Modules/FindIconv.cmake (or maybe the cmake search methods called by FindIconv.cmake).  It is first finding iconv.h (from Fink in the OP) and then finding libiconv.dylib (in /usr/lib). The file finding logic is not consistent between these two search macros:
~~~~
FIND_PATH(ICONV_INCLUDE_DIR iconv.h)
FIND_LIBRARY(iconv_lib NAMES iconv libiconv libiconv-2 c)
~~~~

**Comment by odysseus9672** [comment]
@nieder, should I send that information upstream to the cmake project?

**Comment by howarthjw** [comment]
Are you sure that FindIconv.cmake comes from cmake itself? I don't see that
in the cmake 3.2.3 files.

**Comment by nieder** [comment]
@odysseus9672 `FindIconv.cmake` is not from upstream. I don't know how responsive they are to debugging Find*.cmake files written by third parties.

**Comment by vtjnash** [comment]
On my system, I traced this issue as coming from CMake: It unconditionally adds /sw and /opt/local to my path when searching for the pkg-config binary, even though I don't put any package managers in my PATH variable to avoid this problem (and the inevitable resulting confusion https://github.com/libgit2/libgit2/issues/3296#issuecomment-119203158):
https://github.com/Kitware/CMake/blob/101ba25e6a2c177f9f3a81f3879a171256806756/Modules/Platform/Darwin.cmake#L238-L241

(homebrew isn't necessarily any better at this, since it is also willing to install /usr/local/bin/pkg-config to supplement the system libraries, and it can be a bit harder to remove from the PATH variable due to its placement in the default search paths for the compiler).

**Comment by carlosmn** [comment]
Homebrew does not put its own copy of a system library into the default search path, nor does its CMake put the path of such a copy into its default. That's why homebrew works well here.
