### ISSUE TITLE
libgit2's API changed so frequently

### ISSUE THREAD

**Issue by xiangism** [libgit2/libgit2#3324]
libgit2's API changed so frequently, and lots of examples can't run again;

**Comment by shiftkey** [comment]
@xiangism what sort of examples are you referring to?

**Comment by carlosmn** [comment]
The API does change across releases, but that's why we provide the maintenance releases. We sometimes need to fix design errors or misunderstandings in how the Git system works. Sometimes we simply have to cope with changes in how git itself changes.

That said, we do keep our examples up to date. The ones which live in the source code are checked on each PR and and the website is updated for a release. There's not much we can do about examples which are external to the project. These changes are made so that we do keep the released API once we commit to its stability.

**Comment by linquize** [comment]
libgit2 is still v0.x
v0.x API may change quickly
v1.x API may be more stable

**Comment by xiangism** [comment]
@shiftkey @carlosmn I refer the the examples which are external to the libgit2, such as sba1/simplegit. Maybe I should study your official examples first. 
At last, I look forward to the v1.x of libgit2 released.
