### ISSUE TITLE
Failed HTTP authentication tough to show error message

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#3358]
It looks like in #3269 the HTTP authentication was modified to continuously poll the provided callback for credentials, but I think this means it's tough to get libgit2 to report that a 401 status code was received. I've modified my credentials callback to run at most once (just have a boolean that returns an error on the second invocation). There appears to be two situations from after the credentials callback is called:

* If `GIT_PASSTHROUGH` [is returned](https://github.com/libgit2/libgit2/blob/cf716beed2f4729cf01a9822d75b4f1ebf7ccbf1/src/transports/http.c#L351-L352), then it'll set the local `no_callback` and the error message reported is "authentication required but no callback set", which isn't quite true (as the callback was called).
If some other error [is returned](https://github.com/libgit2/libgit2/blob/cf716beed2f4729cf01a9822d75b4f1ebf7ccbf1/src/transports/http.c#L353-L354) then it looks like the connection is retried, so the error is basically ignored.
* Otherwise the callback needs to [succeed somewhow](https://github.com/libgit2/libgit2/blob/cf716beed2f4729cf01a9822d75b4f1ebf7ccbf1/src/transports/http.c#L355-L365).

Would it be possible to have a `GIT_PASSTHROUGH` from the callback translate to just reporting that a "401 status, expected 200" error was found? Perhaps associating it with `GIT_EAUTH` as well would be nice! It looks like this was somewhat attempted in #3243 but perhaps stagnated?

**Comment by carlosmn** [comment]
If you return `PASSTHROUGH`, we report that there was no callback set because that's what the callback wanted us to pretend. This is made for the situation where a language binding always sets the callback (because it finds it more convenient or it doesn't quite yet know whether the user has set it). If the bindings discover that the user did not in fact set the callback, they can return this error code so libgit2 reacts appropriately, allowing the implementation details of bindings to be transparent.

The callback doesn't have to succeed. It can return `GIT_EAUTH` itself, or set an error somewhere it controls and return `GIT_EUSER` to let the caller of `_fetch()` or `_push()` know for sure that this was aborted by the application code. If the user/application has given up on providing credentials, the right thing to do there is return an error, which will abort the process and return the error to the caller of the fetch or push.

**Comment by alexcrichton** [comment]
> If you return PASSTHROUGH, we report that there was no callback set because that's what the callback wanted us to pretend.

Ah ok, thanks for the clarification!

> It can return GIT_EAUTH itself, or set an error somewhere it controls and return GIT_EUSER to let the caller of _fetch() or _push() know for sure that this was aborted by the application code.

I tried, this, but it looks like the error returned by the callback isn't propagated? The error I get back is "HTTP parser error: the on_headers_complete callback failed" with the `klass` field set to 12 and the error code from `git_remote_fetch` was -1 (`GIT_ERROR`). Maybe this is where I got confused?

**Comment by carlosmn** [comment]
> The error I get back is "HTTP parser error: the on_headers_complete callback failed"

That's definitely a bug on our side. We should be a lot smarter about handling the user-supplied error.

**Comment by alexcrichton** [comment]
I believe this was fixed by #3383

**Comment by ethomson** [comment]
Great!  Please do reopen if it wasn't.  Thanks!
