### ISSUE TITLE
Git LFS confuses Libgit2 status.

### ISSUE THREAD

**Issue by envygeeks** [libgit2/libgit2#3373]
When a file is added to Git LFS and pushed Atom through Libgit2 still thinks the file has changed and highlights it in orange even though it has already been pushed up to Github and git status reports that the file is no longer modified.

See Below:

```
ruby -r rugged -e 'Rugged::Repository.new(".").status { |k, v| $stdout.puts "#{k}: #{v}" }' && printf '\n\n'; git status
repo/x86_64/APKINDEX.tar.gz: [:worktree_modified]
repo/x86_64/glibc-2.21-r4.apk: [:worktree_modified]
repo/x86_64/glibc-bin-2.21-r4.apk: [:worktree_modified]
repo/x86_64/glibc-dev-2.21-r4.apk: [:worktree_modified]
repo/x86_64/glibc-doc-2.21-r4.apk: [:worktree_modified]


On branch master
nothing to commit, working directory clean
```

/cc https://github.com/atom/atom/issues/8291

**Comment by ethomson** [comment]
That's correct.  We do not run external filters for you - you should be able to hook up an lfs filter via [`git_filter_register`](https://github.com/libgit2/libgit2/blob/master/include/git2/sys/filter.h#L292) and then figure out how to exec LFS in your environment.  (It may make sense to register the wildcard filter, `*`, so that you can handle all possible external filters.

We don't have a lot of people using this API quite yet, so please do provide feedback.

**Comment by envygeeks** [comment]
That's fair, I guess it's time for me to hit a third repo and see if I can PR a global filter onto Atom's sidebar git handling so that it detects these changes.

**Comment by ethomson** [comment]
Sounds good - thanks.
