### ISSUE TITLE
Feature Request: custom HTTP user agents/headers

### ISSUE THREAD

**Issue by michaeledgar** [libgit2/libgit2#3400]
My binary uses libgit2 in part for its HTTP git client implementation. Our use case for a custom User Agent (or any other custom X- header) is this: we'd like our server to be able to approximate how much traffic comes from our custom binary.

We currently achieve a custom user agent with a brutal hack: our build script changes the LIBGIT2_VERSION variable in include/git2/version.h to include a string suffix, and that string suffix ends up in the User Agent.

Precedent exists for this particular feature request. Stock git, for example, [will use the GIT_HTTP_USER_AGENT environment variable](https://github.com/git/git/blob/3a9835bf65d07321924f2d60686a194e9d257d20/http.c#L521) if it specified. JGit provides [an API](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/UserAgent.java#L123) for setting the User Agent globally.

**Comment by ethomson** [comment]
:+1: 

We have the same concerns in our product, but since we use a custom transport, we actually update the user-agent ourselves.  I can very much see how this is an issue.

I could see how there's a [handy option](https://github.com/libgit2/libgit2/blob/c7f94123569e8fe00ffb3a35e6a12b6ebe9320ec/include/git2/common.h#L245) to set this.

**Comment by carlosmn** [comment]
The custom header fields was handled by #3411 and setting the user-agent in particular (for the places where we already set it) is done by #3448

**Comment by carlosmn** [comment]
Both of those PRs are now merged, so closing as done.
