### ISSUE TITLE
libgit2 doesn't push properly 2 refs without common ancestor to GitHub server

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3405]
I have a test bare repo with has 2 branches: `master` and `test`. Both are up-to-date with the corresponding private repo on GitHub.

I'm calling `git_remote_upload()` passing 2 refspecs to push over SSH:
- `refs/heads/master:refs/heads/master`
- `refs/heads/test:refs/heads/test`

The push fails and the GitHub server simply says "001fng refs/heads/test\n failed\n" (the fact libgit2 fails to properly parse this report line is covered by #3404).

If I push each separately i.e. one at a time using `git_remote_upload()`, then the GitHub server accepts them without failing.

Git CLT is also able to push both refs to the GitHub server, so it appears there's a problem with libgit2:
```
$ GIT_TRACE=1 GIT_TRACE_PACKET=1 git push -v origin refs/heads/master:refs/heads/master refs/heads/test:refs/heads/test
16:51:09.132787 git.c:348               trace: built-in: git 'push' '-v' 'origin' 'refs/heads/master:refs/heads/master' 'refs/heads/test:refs/heads/test'
Pushing to git@github.com:swisspol/Decks.git
16:51:09.134982 run-command.c:347       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''swisspol/Decks.git'\'''
16:51:10.587824 pkt-line.c:46           packet:         push< 37725a382f40e7c13efdcdea4589c70964338d08 refs/heads/master\0report-status delete-refs side-band-64k quiet atomic ofs-delta agent=git/2:2.4.8+github-1117-g10c819b
16:51:10.587878 pkt-line.c:46           packet:         push< 8f400acce001fb3a8391d0ad7ec94437ae5241df refs/heads/test
16:51:10.587887 pkt-line.c:46           packet:         push< 0000
16:51:10.587986 pkt-line.c:46           packet:         push> 0000
To git@github.com:swisspol/Decks.git
 = [up to date]      master -> master
 = [up to date]      test -> test
updating local tracking ref 'refs/remotes/origin/master'
updating local tracking ref 'refs/remotes/origin/test'
Everything up-to-date
```

PS: These 2 refs have no common ancestor (i.e. they lead to separate roots).

![image](https://cloud.githubusercontent.com/assets/627915/9592811/b4b2aa8e-4ffb-11e5-9468-45e22914c159.png)

**Comment by swisspol** [comment]
I wrote a reproducible case at https://github.com/git-up/github-bug - see README for details. I already invited @carlosmn and @ethomson as collaborators to https://github.com/git-up/test-dual-roots.

**Comment by peff** [comment]
This should be fixed now, and was a GitHub bug. But I think there is something else interesting going on with libgit2 here, which is that the ref lines sent during a libgit2 push all end in newline (I think due to [this line]( https://github.com/libgit2/libgit2/blob/21e7015ca3425e396c2b7cc03ac67e297a646c91/src/transports/smart_protocol.c#L675)). Whereas git's line do not (see [here](https://github.com/gitster/git/blob/7aa67f62c7cc0f5771dffe58c3234b6940d35a5d/send-pack.c#L492-L501)).

On the receiving end, git's `packet_read_line` will auto-chomp the newline from each packet, meaning that the extra newlines don't matter. But in the first ref, with the capabilities string, we chomp a newline from the end of the capabilities string, and would _not_ chomp a newline before the `\0` separator.

Fortunately this works out for libgit2, which is also adding a newline to the end of the packet (including capabilities). So there's no bug. But you may want to make libgit2 match git's behavior.

Of course, the git documentation being what it is, [the spec](https://github.com/gitster/git/blob/7aa67f62c7cc0f5771dffe58c3234b6940d35a5d/Documentation/technical/pack-protocol.txt#L472-L473) appears to call for the newline. Yeesh.

**Comment by carlosmn** [comment]
I thought the spec mentioned that finishing with LF was optional on each pkt-line, but it seems it's (currently?) only mentioned in the server's ref advertisement. It's nice for debugging, but if git won't generate them, then we probably want to remove them as well.

**Comment by peff** [comment]
Git is horribly inconsistent, both in what it does and in what it documents. :)

I'm inclined to say that what libgit2 is doing is _right_, and what git is doing is not _wrong_, but is simply exercising its liberty with a SHOULD directive in the spec. I've sent [this](http://thread.gmane.org/gmane.comp.version-control.git/277182/focus=277185) upstream which makes that more clear in the spec. We'll see what others think.

**Comment by carlosmn** [comment]
Excellent. Since this was a server-side issue, I'll close the bug, and we'll react to the LF issue as the ML reacts to it.

**Comment by peff** [comment]
:+1:

**Comment by swisspol** [comment]
I can confirm that the test case I provided above is now passing. Thanks everyone!
