### ISSUE TITLE
Not a bug but a question about something I don’t understand in the code

### ISSUE THREAD

**Issue by ytrezq** [libgit2/libgit2#3457]
Sorry for asking it here but, what’s the point of limiting the size of diff hunks headers to exactly 128 chars ?
Why not a bit less or slightly more ?

**Comment by ethomson** [comment]
You're asking (I think) about the size of the `diff_hunk_header`?  This is the `@@ -a,b +c,d @@` line, and that number was chosen because we want a statically sized buffer there that is large enough to hold any diff header that we will encounter.  That is far more than long enough in practice.

I didn't come up with that number, but I might have chosen the same.  If you're looking at four numbers, they're all line numbers (thus should probably be unsigned).  2^64 in decimal is 20 characters long.  Four of those makes 80 characters.  Add in the `@@`s and other markup and you're up to 91 characters.  128 is the next power of two.

Obviously, though. you're not doing to do a diff of two files with that many lines, so it's rather moot.  In any case, it's chosen to be sufficiently large that it's bigger than any line you would see from a diff file.

**Comment by ytrezq** [comment]
@ethomson : No I’m talking about the`git_diff_hunk`structure in`diff.h`

**Comment by ethomson** [comment]
Well, `git_diff_hunk` is *not* 128 bytes, because it has the `header` member that is 128 bytes (plus it has other things).

If you mean https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L488 - then please see my response, above.

**Comment by ytrezq** [comment]
@ethomson : Thank you. More than large diff this would need a very use number of`\n`or`\r`meaning very large files.
But remember ꜰᴀᴛ32 is less than 20 years old and it’s reaching it’s limits. So may be it worth switching to a more dynamic allocation now.

**Comment by ethomson** [comment]
I'm not sure what this has to do with FAT32.  But I think that we can wait to address this problem until we have the capability to deal with files that have more than 18,446,744,073,709,551,616 lines in them which - I'm quite certain - we don't right now.

**Comment by ytrezq** [comment]
@ethomson : yet an another question. I don’t understand the purpose of don’t fetching large files to the xdiff library.

**Comment by carlosmn** [comment]
xdiff can't handle big files, so we don't give it big files.

The @ sign is special for the documentation, so if you want to use a literal '@' you need to escape it, the same reason you escape anything.

**Comment by ytrezq** [comment]
@carlosmn : Yes I already understood both point. I misasked my questions.

What makes xdiff unable to handle large files ?
How is the`@`special in docs ?
