### ISSUE TITLE
repository modified right after cloning on HFS+ when filenames are precomposed

### ISSUE THREAD

**Issue by palmin** [libgit2/libgit2#3496]
I see strange behaviour for some filenames on HFS+ where a cloned repository starts out as modified right after being cloned. I have tried to find a minimal example that illustrates the problem.

The repository `https://github.com/palmin/umlaut` contains the lonely file `ä` where the umlaut is precomposed. 

Cloning this repository with default options and looking at status indicates one added file and one deleted file, both ä but I presume one is precomposed and one is decomposed.

The following example will replicate the problem on the current master commit (d571a54):

    int status_cb(const char *path, unsigned int status_flags, void *payload) {
       printf("%s : %d\n", path, status_flags);
       return 0;
    }
    
    int main() {
       const char *url = "https://github.com/palmin/umlaut";
       const char *path = "umlaut";
    
       git_clone_options clone_options = GIT_CLONE_OPTIONS_INIT;
       git_repository *repo = NULL;
    
       git_libgit2_init();
    
       int error = git_clone(&repo, url, path, &clone_options);
       if(error >= 0) {
          error = git_status_foreach(repo, status_cb, NULL);
       }
       printf("error = %d\n", error);	
       return 0;
    }

Output indicates `ä` is both added and deleted

    ä : 512
    ä : 128
    error = 0

It seems like a error that a repository can be modified right after cloning, but command-line git (version 2.4.9) has similar but not identical behaviour.

    git clone https://github.com/palmin/umlaut
    cd umlaut
    git status

will output

    On branch master
    Your branch is up-to-date with 'origin/master'.
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
    	"\303\244"
    
    	nothing added to commit but untracked files present (use "git add" to track)

This happens for libgit2 on both OS X and iOS, variants of HFS+ where one is case sensitive and the other is case insensitive. 

Is this a error or expected behaviour?

If this is indeed a error, I can dig deeper and look for a solution.

**Comment by ethomson** [comment]
Your repository does not contain a precomposed path - that path is NFD. 

    % git ls-tree HEAD
    100644 blob 9daeafb9864cf43055ae93beb0afd6c7d144bfa4    "a\314\210"

Which is U+0061 U+0308.  NFC is U+00E4 (0xc3 0xa4).

When you clone the repository on a Mac (either libgit2 or git), it will set `core.precomposeunicode` in the repository by default.  When your repository already contains decomposed paths, this will appear as you have described.

It does seem like there *is* a bug here - libgit2 should probably be showing the same status as git.  This may or may not be related to #2268 .

**Comment by palmin** [comment]
Using libgit2 to clone and command-line git to check status will give identical results as cloning with command-line git. 

This seems to indicate that cloning itself is not to blame. 

I will keep digging.

**Comment by ethomson** [comment]
No, like I said - there appears to be a bug in status, but otherwise, this is behaving exactly as it should.

If you have decomposed paths in your repository, but you have `core.precomposeunicode = true`, then you've not been truthful about the state of your repository.  If you want to use this repository on a Mac and use `core.precomposeunicode = true` (and you should) then you should actually convert your repository to use precomposed paths.

**Comment by carlosmn** [comment]
Indeed that file is known to Git in its decomposed form, which is unexpected for a recent repository. How did you insert this path into a commit? This can happen on older gits which do not precompose paths when inserting into the index. Or, if you pass the decomposed form to libgit2 in some places, which makes the creation of such an oddity partly our fault, as per #2268.

The difference in the status output might just come down to implementation details, which is unfortunate.

As you say, the cloning itself isn't at fault, it's just copying data. The checkout will put the decomposed form on the filesystem, which is what it likes (though if we had the composed form, it would convert it). The underlying issue is the entry in the tree and index is in decomposed form, whereas Git nowadays assume you want to have the precomposed form in Git, and then deal with conversions to and from the filesystem (a bit like crlf). When we have the decomposed form inside Git, we still convert the path into precomposed (due to `core.precomposeunicode`) and thus fail to match with the existing entry.

Up to there, we're doing the same as git. `a\314\210` are not the same bytes as `\303\244` so we fail to match (git then shows the path precomposed, which seems confusing, but whatever). I'm not sure why libgit2 would fail to match the other path, though.

**Comment by palmin** [comment]
I have users with repositories containing filenames in either form, such that both values for core.precomposeunicode will cause problems. One could argue that such repositories are in themselves problematic, but the problems do not seem to surface except on HFS+.

The file was made on a linux box with:

    echo test > $(echo -e "\0141\0314\0210")

in a attempt to distill the problem to a minimal form.

**Comment by ethomson** [comment]
That's because HFS+ does not store the literal filenames that you give it.  It *only* supports NFD (well, technically, a modified NFD).

You simply *cannot* roundtrip a filename reliably.  If you create a file with U+00E4, Mac OS will tell you that you have a file named U+0061 U+0308.

Since Git itself as no concept of a canonical Unicode format, and simply stores the literal bytes you give it, this is going to be problematic.

This is why git provides `core.precomposeunicode`.  So that you can at least use a more standard NFC form for your file names.  However, you will have to use the more standard NFC form, this is not a magic bullet.

Fundamentally, this is a problem with Git itself, and not a place that libgit2 wants to innovate.  If Git itself comes up with a superior solution to this problem, we will happily implement it.

**Comment by palmin** [comment]
Ok. I understand this better now.
Thank you for your explanations.

As far as I am concerned, this issue can be closed.
