### ISSUE TITLE
Lots of valgrind errors related to git_remote_lookup

### ISSUE THREAD

**Issue by FedeDP** [libgit2/libgit2#3509]
Hi,
while trying to implement a fetch, i noticed that this code is producing lots of valgrind errors: http://codepad.org/a04rmBur. The problem is in the "git_remote_connect" inside "git_remote_fecth".
This is valgrind output: http://codepad.org/Aw0HyfP4. 
The weird thing is that avoiding  "git_remote_lookup"(L18) by using instead "git_remote_create_anonymous "(L 19), all errors are gone, 0 valgrind problems.
Any idea?

Thank you very much!

**Comment by carlosmn** [comment]
OpenSSL is rather unwieldly, and it's not necessarily clear whether libgit2 should be in the business of clearing the per-thread data it stores. These steps are usually up to the application (OpenSSL is not particularly good at being a secondary dependency). There's also some allocations which would be detected by a tool such as valgrind, but do not represent actual issues. See e.g. [their FAQ](https://www.openssl.org/docs/faq.html#PROG13)

**Comment by FedeDP** [comment]
So, i still don't understand why avoiding "git_remote_lookup" fixes all these issues. 
You know, i'm still calling "git_remote_fetch"...

**Comment by carlosmn** [comment]
They don't come from `git_remote_lookup()`, which doesn't touch crypto or networking at all. "Avoiding" that function would mean you have no remote you can use, so the rest of the code can't do anything.

The allocations are made from `git_remote_connect()` since that's the one that connect and thus makes OpenSSL initialise its global tables. But it should only come from the very first one, any other connections would be able to use the global tables that already exist by that time.

**Comment by FedeDP** [comment]
I see now...thank you very much!

**Comment by FedeDP** [comment]
Well it seems errors keeps increasing indeed:

1 call: ERROR SUMMARY: 113557 errors from 613 contexts (suppressed: 0 from 0)
2 calls: ERROR SUMMARY: 210986 errors from 676 contexts (suppressed: 0 from 0)
3 calls: ERROR SUMMARY: 332668 errors from 720 contexts (suppressed: 0 from 0)

Note that i'm not freeing anything openssl related.
Btw i find that running valgrind with "--undef-value-errors=no" removes these "errors", so i'll use this option while debugging this source file.
I thought it was a good idea to leave this solution here.
