### ISSUE TITLE
No direct way of getting a non-cached Index object via `git_repository_index`

### ISSUE THREAD

**Issue by srajko** [libgit2/libgit2#3531]
Since `git_repository_index` caches the Index object in `repo->_index` (https://github.com/libgit2/libgit2/blob/15e6a5afb9217b09e60cd0aef48e0a7781f3922f/src/repository.c#L828), typically everything calling `git_repository_index` gets back the same object.  I have a use case where I read in the index, do some in-memory modifications to it, and then use it without ever writing the index back to disc.  Because of the caching, the in-memory modifications affect the index object for other code that got (or will get) the index via `git_repository_index`, and often the interaction is unintended and with negative consequences.

It is possible to get a unique, non-cached Index object by taking advantage of `git_repository_set_index(repo, NULL);` to clear the cache before and/or after `git_repository_index`.  It is also possible to force-read the index after in-memory modifications or before use via `git_index_read(index, 1)`, but both of those feel awkward.

Would it be good to add a direct way of getting a non-cached Index that's associated with a repository?  Or perhaps a way to associate an index obtained via `git_index_open` with a repository?

**Comment by ethomson** [comment]
> Would it be good to add a direct way of getting a non-cached Index that's associated with a repository? 

Can you clarify what you mean by an index that's associated with a repository?  I think of the repository as having an index, and then other indexes - for example, the ones that are the results of a `git_merge` - aren't really *associated* with a repository.  I say this just to clarify - I hate to get bogged down in terminology here.

My 5 minute thought here is that what I would want in your shoes is a way to duplicate an index.  You could then duplicate the repository's index, modify the duplicate and throw it away at will without affecting the repository's index.

The easy way to do this would just be to duplicate everything.  We don't actually have a way to do this directly at the moment, though you could create a new index and `git_index_read_index` the existing index into the new one.  (Generally speaking, this will merge the two indexes, but with an empty target, it will effectively be a duplicate.)

**Comment by srajko** [comment]
Sure - I mean it along the lines of what is mentioned here: https://libgit2.github.com/libgit2/#HEAD/group/index/git_index_open

"Since there is no ODB or working directory behind this index, any Index methods which rely on these (e.g. index_add_bypath) will fail with the GIT_ERROR error code.

If you need to access the index of an actual repository, use the git_repository_index wrapper."

Specifically, I need an index that *does have* "an ODB or working directory" behind it, so that it is fully functional.  I believe `git_repository_index` accomplishes this via `GIT_REFCOUNT_OWN(index, repo);` and maybe `git_index_set_caps(repo->_index, GIT_INDEXCAP_FROM_OWNER);`.

Duplicating an index would work - that would be a nice interface, I think.  `git_index_read_index` sounds like would work, but it doesn't seem to be exposed externally?

**Comment by carlosmn** [comment]
If you want to read an index file into memory, you can use `git_index_open()`, but if you want to refresh the data that's in the `git_index` instance returned by the repository, there's no need to delete the instance or merge, you use `git_index_read()`. This is what the library does when you ask it to do something which needs to look at the contents of the index as they exist.

I've thought about making `git_repository_index()` hand out a fresh instance, but that makes some things more awkward. If you don't want to make use of the caching, I'd recommend to open the index file directly. The object db part of that isn't generally an issue, since you can use `git_index_write_tree_to()` when you want to write it out as a tree to an arbitrary repository.

You can associate an index with a repository with the function you mentioned, `git_repository_set_index()` but that's rarely something you'd want to do. If you're dealing with "the" index, you can use the accessor. Otherwise, you probably don't want the library to think an index you instanciated for the data structure is anything close to the repository's index, or we'll write your temporary data to disk during a diff.
