### ISSUE TITLE
API for choice of compression algorithm

### ISSUE THREAD

**Issue by pberto** [libgit2/libgit2#3566]
I'd like to discuss whether it is possible to request swappable compression algorithms.

Currently, libgit2 uses zlib which is probably the best choice in terms of compression ratio and therefore transfer.

There are however cases where optimal disk size is not a top priority, we would not mind to sacrifice compression ratio in exchange of fast compression/decompression (such as when using LZ4, which is by the way distributed with a friendly BSD license -- https://github.com/Cyan4973/lz4).

Therefore we would like to have some API to choose compression algorithm, the following choices would be great:

- `none` -- no compression (useful for projects that are not SCMs -- see this issue: https://github.com/libgit2/libgit2/issues/422)
- `zlib` (default -- offers good transfer/compression ratio)
- `lz4` (offers very fast compression/decompression with less compression ratio)

Please let us know whether there is interest and if this is feasible in libgit2, or if we should handle this internally (by disabling compression and handling compression internally using LZ4). On the other hand, if there is wider community need for this, it would be great if it could receive your attention.

Thanks for making this great piece of software.

**Comment by carlosmn** [comment]
We use zlib because that's what the Git repository format uses. The network protocol is defined as using zlib. If we were to use lz4 or anything else, it would no longer be a Git repository.

Which means we would either create a parallel kind of repository, which looks like a git repo but won't work with any implementation but one which somehow knows to set the options, or we'd need a revamp of the Git objects to know what method things are compressed with.

The former is not something I think we should have in the upstream library. But you can already create your own object db backends which implement whatever compression method you want for internal use. This is what .e.g VSTS uses to store their data in SQL Server. If no other implementations are supposed to be able to use the repo, that's the method I'd recommend.

If it's supposed to be shareable, then that is a discussion that needs to happen with Git as a whole in the git.git mailing list, not here.

**Comment by ethomson** [comment]
Agreed.  We only use zlib in the places where interop is required.

If you do not require interop with git itself then you are welcome to create a custom backend, but this would not be something that libgit2 would want to include.

If you would like to see git itself use this backend then a discussion on and / or patches to the mailing list would be the place to start.  We would of course want to include this for compatibility.
