### ISSUE TITLE
File status incorrectly labeled GIT_STATUS_INDEX_RENAMED

### ISSUE THREAD

**Issue by smith-kyle** [libgit2/libgit2#3674]
Think I've found a case where the status of a file is incorrectly labeled as `GIT_STATUS_INDEX_RENAMED` instead of `NEW`.

During a merge conflict, if `fileA`is conflicted and some newly added file `fileB` with the same contents as `fileA` was added in the merge head, after resolving the conflicts in `fileA` the status of `fileB` will change to renamed and modified.

Here are the repro steps:
1. Clone https://github.com/smith-kyle/status-bug
2. Merge the `conflict` branch into `master`
3. Stage `fileA` after resolving conflicts (be sure to take `conflict`'s version so the index contains some changes to `fileA`)
4. See the status of `fileB` has changed from new to modified and renamed

**Comment by ethomson** [comment]
This certainly seems reasonable to me, although you didn't say why you expect that to be `NEW`.

You don't explain what you resolved the conflict *with*, but let's assume for the sake of argument that it's completely different.  (ie, 0% similar).  In that case, it's eligible for rewrite breaking, and git is free to now assume that you renamed `fileA` to `fileB` and created a new `fileA`.  For example:

```
zoidberg:% mv foo bar
zoidberg:% echo "new file in foo's place" > foo
zoidberg:% git add foo ; git add bar ; git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	copied:     foo -> bar
	modified:   foo
```

This is just simple rewrite breaking and rename detection.  It doesn't matter whether you staged the changes to resolve a conflict or you actually `git mv`d them or whatnot.

If git.git is showing you something different, it's possible that our defaults are slightly different than the `-B` or `-M` defaults to `git diff`.  But fundamentally, this seems like the correct behavior.

**Comment by smith-kyle** [comment]
I understand what you're saying but libgit2 seems to contradict itself between beginning the merge and committing. Hopefully this will explain the problem better:

**After starting merge from conflict to master**
*git.git*
<img width="344" alt="screen shot 2016-03-10 at 3 36 17 pm" src="https://cloud.githubusercontent.com/assets/5474861/13687403/4676ccd4-e6d8-11e5-85df-f708d5a378e5.png">
*libgit2*
<img width="385" alt="screen shot 2016-03-10 at 3 40 27 pm" src="https://cloud.githubusercontent.com/assets/5474861/13687545/198a01b8-e6d9-11e5-9cb2-54bcb2a09d3a.png">

**After resolving the conflict in fileA by taking the changes from the conflict branch**
*git.git*
<img width="330" alt="screen shot 2016-03-10 at 3 42 35 pm" src="https://cloud.githubusercontent.com/assets/5474861/13687450/98445b30-e6d8-11e5-951a-81d15091bc59.png">
*libgit2*
<img width="383" alt="screen shot 2016-03-10 at 3 43 12 pm" src="https://cloud.githubusercontent.com/assets/5474861/13687459/a964b16c-e6d8-11e5-925c-b296729aec79.png">

**After committing the merge**
<img width="206" alt="screen shot 2016-03-10 at 3 51 08 pm" src="https://cloud.githubusercontent.com/assets/5474861/13687467/b54ab26a-e6d8-11e5-9a4b-56917f3380cc.png">

According to libgit2 after resolving the conflicts `fileA` had a status of new and `fileB` modified, but after committing with libgit2 it's the opposite.

**Comment by ethomson** [comment]
> According to libgit2 after resolving the conflicts fileA had a status of new and fileB modified, but after committing with libgit2 it's the opposite.

You didn't include the results of a diff using libgit2 after the merge, so I'm not able to see what you mean by this.

**Comment by smith-kyle** [comment]
My bad. Here it is using `nodegit`:
<img width="191" alt="screen shot 2016-03-11 at 9 30 05 am" src="https://cloud.githubusercontent.com/assets/5474861/13708478/14586188-e76c-11e5-9e46-50012360f3c0.png">
It's identical to the git.git diff

**Comment by ethomson** [comment]
That makes the problem less obvious.  Are you doing rename detection in node git?

**Comment by johnhaley81** [comment]
@smith-kyle what's the code that you're using to call NodeGit?

**Comment by johnhaley81** [comment]
Ahh, by default we do rename detection: https://github.com/nodegit/nodegit/blob/master/lib/repository.js#L1098-L1120

**Comment by smith-kyle** [comment]
that explains it! Sorry @ethomson thanks for your help

**Comment by ethomson** [comment]
Just to expand on this a little bit.  When you do a merge and have a conflict, that conflict is in high stage index entries.  We do *not* take those into account when doing rename detection (ever).  So `fileA` as conflicted and `fileB` as staged makes sense.

However, as soon as you stage `fileA`, the resolved file is staged.  It is now eligible for rename detection in git and libgit2.  `git status` and libgit2's status both do rename detection here (by default).  As I mentioned, there is nothing special about merge or that this was a conflict:  it's a staged change as far as anybody is concerned and rename detection *will* happen on it unless you ask it not to.

As I mentioned, git will show you renames that occurred during conflict resolution.  The bug here appears to be that we are showing renames when git itself isn't.  There are a handful of possible reasons why this is:  both our rename detection algorithms have a minimum file size at which we start paying attention.  It's possible that these defaults are different, or we measure slightly differently.  Whitespace may be an issue.  In any case, we don't guarantee our rename detection algorithm to be identical.  Nor do I want to...

I suspect that you're finding this difference while writing unit tests.  I would recommend you increase the size of the files that you're working with to avoid false positives.  Please feel free to file bugs against us if the results seem broken, but I don't want to start with the idea that we're going to be identical to git.git.  This is one of the very few places that I am happy *not* being bug-for-bug compatible with git.  (Though I think that here we should be devilishly close.)

**Comment by ethomson** [comment]
By the way you almost certainly *do not* want to do rename detection on index -> workdir.  This will find renames that you haven't staged yet.  This differs from git (which only looks at staged changes for renames.)

It ends up being computationally punishing because almost nobody properly `.gitignore`s their build directories and you will end up looking at build output for renames.  This is only an option for clients who want to have a workflow where you don't stage changes, but show all the changes on disk, and find renames that the user did without staging them.
