### ISSUE TITLE
include.path with non-existing file

### ISSUE THREAD

**Issue by andreineculau** [libgit2/libgit2#3681]
I have my `~/.gitconfig` set up as a symlink (shared among my terminals) and with content like

```
[include]
    path                = ~/.gitconfig_pre

..... main config goes here ....

[include]
    path                = ~/.gitconfig_extra
```

This allows me to have local modifications, specific to the terminal.
But on some terminals, I don't have any modifications, so those include paths are missing.
libgit2 seems to crash in that scenario and returns no global configurations.

**Comment by carlosmn** [comment]
What do you mean by crash? Does the application crash or does it consider a missing file an error?

**Comment by ethomson** [comment]
I'm adding the "easy fix" tag because I think this would be a good place for a person to jump in.  It sounds to me like "returns no global configurations" means it's _not_ crashing, it's just not doing what you expected.  😀 

To tackle this, I would:

1. Write a unit test where we open a configuration file with an `include.path` that does not exist.  Before even asserting anything about the state of the repository, verify that running this unit test _really doesn't crash_.  😀 
2. Update the unit test to check that the configuration loaded successfully.  Given the bug report, I would expect this to fail; I expect loading a configuration file in this state returns `-1` and sets a meaningful error message.
3. Trace through to where we deal with including configuration files from within configuration files.  Check for `errno == ENOTFOUND` and turn this into a non-error.  Make sure to `giterr_clear`!  Keep other error handling the same, we might get some strange errors when reading that included file that we _don't_ want to ignore.

**Comment by meatcoder** [comment]
I had a look at this and created #3828 to attempt and fix it. It turns out that the parsing only stops when the file being included is relative to the home directory. Using absolute and relative paths seems to work as expected.

**Comment by csware** [comment]
Please also see issue #4168 which fixes resolving of absolute symlinks.
