### ISSUE TITLE
Fix the examples/diff.c implementation of the -B

### ISSUE THREAD

**Issue by saurabhsuniljain** [libgit2/libgit2#3686]
I want to fix the implementation of examples/diff.c  I understand i need to check whether there is anything extra after -B like /70% or 20%, and set the values for appropriate flags. So is it okay for me to write a another if else statement inside that ?

I have made some [changes](https://github.com/saurabhsuniljain/libgit2/commit/e1a235713ee35f6c5d6eeb9cc243a38b7c922391) please someone review it before I make a pull request.
Thanks :)
@carlosmn @ethomson

**Comment by ethomson** [comment]
Hello and welcome!  As a procedural note - please do open pull requests!  That's where we do code review.  GitHub is very nicely designed around being able to open pull requests and do code review inside the context of those PRs.  It's much harder for code reviewers to look at some branch in your fork.  

So there's no need to ask permission to open a pull request.  We're happy to see them.  :)

Since you opened #3688, I'm going to close this issue.  Thanks!
