### ISSUE TITLE
Regarding GSoC 2016

### ISSUE THREAD

**Issue by saurabhsuniljain** [libgit2/libgit2#3694]
Hi,
I am interested in applying for GSoC 16, I read README.md, PROJECTS.md and CONVENTIONS.md files and tried to fix a bug for the microproject. I made [pull request](https://github.com/libgit2/libgit2/pull/3688) but no one seems to give attention (before that I made a [Issue](https://github.com/libgit2/libgit2/issues/3686), also no reply). 

I would like to discuss my ideas with the mentors, so please all those who are concerned with GSoC 16, please drop me a mail at saurabhsuniljain@gmail.com. 

Please someone review my [pull request](https://github.com/libgit2/libgit2/pull/3688).

@carlosmn

**Comment by ethomson** [comment]
Hello again!  Apologies for taking some time to reply.  We'll discuss the contents of #3688 in that pull request.

Otherwise, if you have specific questions about GSOC, please ask them here.  It makes sense to keep that sort of communication open on GitHub rather than over email.  (If you don't have any specific questions, then please close this issue for housekeeping.  Thanks!)

**Comment by saurabhsuniljain** [comment]
Regarding GSoC I would like to know who are the mentors, because I am having new ideas and would like to discuss with the mentors and have my proposal reviewed before final submission.

Thanks :)

**Comment by ethomson** [comment]
@carlosmn and I (@ethomson) are mentors.

**Comment by saurabhsuniljain** [comment]
Thanks I will be closing this Issue now.
