### ISSUE TITLE
Installing libgit2

### ISSUE THREAD

**Issue by saurabhsuniljain** [libgit2/libgit2#3697]
How to install libgit2 with all files in examples folder, I followed the steps given in README.md, but it excludes all example folder files.

**Comment by ethomson** [comment]
The installation instructions are for installing _the library itself_ so that you can link against it (globally).  The examples programs are only meant to be code samples to illustrate how the library works.  They are not meant to actually be generally used programs.  End-users who want to build programs on top of libgit2, and distributions bundling libgit2, would not expect these sample programs to be installed.

**Comment by ethomson** [comment]
If you want to install the example programs, you can simply copy them wherever you want them to live!  :smiley:
