### ISSUE TITLE
Function to parse author and committer information from environment

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3751]
`git_signature_default` parses the `user.name` and `user.email` values from `git_config`, but does not allow for other sources of that information.  Per `man git-commit-tree`:

```
       author and
       committer information is taken from the following environment
       variables, if set:

           GIT_AUTHOR_NAME
           GIT_AUTHOR_EMAIL
           GIT_AUTHOR_DATE
           GIT_COMMITTER_NAME
           GIT_COMMITTER_EMAIL
           GIT_COMMITTER_DATE

       (nb "<", ">" and "\n"s are stripped)

       In case (some of) these environment variables are not set, the
       information is taken from the configuration items user.name and
       user.email, or, if not present, the environment variable EMAIL
```

While the existing behavior of `git_signature_default` should likely not change to take environment variables into account, I'd suggest adding a `git_signature_author_env` and `git_signature_committer_env` that do.  Those would be the appropriate defaults to pass when creating a commit, for any program mimicking the git command-line tools.

**Comment by venkatesh-coder** [comment]
Is this issue still not resolved, I'd like to work on this issue seems achievable to me. Let me know.
Thanks for creating a great library for us. Thank you.

**Comment by venkatesh-coder** [comment]
Thanks @ethomson, I will try my best. I will ask questions if I need more clarification.

**Comment by venkatesh-coder** [comment]
as @joshtriplett mentioned, I created functions `git_signature_author_env` and `git_signature_committer_env` that gets environment variables mentioned in man page for *git-commit* and stores them as `git_signature` struct. I just want to clarify some things
   * there are functions like `git_commit_create`, `git_commit__create_internal` and `git_commit__create_buffer_internal` (first two functions are wrappers for `git_commit__create_buffer_internal`) that sets author and committer details. which function best fits to use `git_signature_author_env` and `git_signatue_committer_env` to change `author` and `committer`.
   * I think `git_commit_create` is right function because others part of the code might use `git_commit__create_buffer_internal` or `git_commit__create_internal` for other purposes the `git_commit__create_buffer_internal` function being the lowest level function which writes to commit `buf`.
   * can I use the `git_signature_author_env` and `git_signature_committer_env` to change the parameters `author` and `committer` that being passed to `git_commit__create_internal` in `git_commit_create`
   My assumptions might be wrong please help me.
Thank you.
