### ISSUE TITLE
Question about using this in a C++ DLL of mine.

### ISSUE THREAD

**Issue by AraHaan** [libgit2/libgit2#3766]
does this lib allow me to querry github like every fraction of a second for json data that I plan to be a dll's way of a database to detect things and always load the latest data on it?

What my DLL is intended to do: use ``FindWindow`` on things in the json arrays. Thing is I do need to for loop it I know for all data in the arrays (but with me being new to C++ more than python that can prove a challenge.) What I want is to make the DLL more accurate without all of the detecting stuff in the dll and have a total wheel to reinvent when I can do such thing 1 time and loop through it as a list. That is where a external online database comes in.

**Why have this database on github?**
Well the benefit to this is that game devs can send pull requests implimenting possible things to detect so that way ppl are less likely to hacking it. Not only them but normal everyday ppl who dont like hackers.)

**Why use github for antihacking reason?**
Anti-hackign software nowdays has and operate on a offline database only and download updates almost every day not only that but are CPU extensive. Will all of my stuff being a DLL I am sure game devs can make their program do a integrity check on the DLL using CRC32. and honestly it is not a bad idea because then ppl who try to bypass the DLL would get (litterally) SOL.

Odd how some things come together 2 completely different projects but they come together to make 1 anti-hacking program that is litterally and hopefully unlike any other.

**Comment by ethomson** [comment]
> does this lib allow me to querry github like every fraction of a second for json data that I plan to be a dll's way of a database to detect things and always load the latest data on it?

Not really, no;  this does not sound like an appropriate use of libgit2.  You _may_ be better served by the [GitHub API](https://developer.github.com).  But using either technology, it's likely that having clients polling _multiple times a second_ is certain to far exceed [rate limits imposed upon you](https://developer.github.com/v3/#rate-limiting).

**Comment by carlosmn** [comment]
libgit2 is for dealing with Git data. Git or GitHub are not database services and using either as such will lead to bad performance and hitting limits early. You can certainly use it for collaboration, but your database will likely be served better by a service specifically for your purpose, which is optimised for your use-case rather than code collaboration.

If you'd like your database to be updated when someone changes a repository on GitHub, you can subscribe your service to [a webhook](https://developer.github.com/webhooks/) so it knows when to grab data from GitHub. Otherwise you'll spend all the time trying to connect instead of performing whatever it is your service wants to do.

**Comment by AraHaan** [comment]
Yeah I sorta rethought of it while at school to querry it every 5 sec and to hopefully somehow pull the info using ``https://rawgit.com/`` <--- basically what I want is the raw data only of the files and hopefully would not have to store local copies of it.
