### ISSUE TITLE
libgit2 v0.24.1: Kate crashes on startup

### ISSUE THREAD

**Issue by dolohow** [libgit2/libgit2#3806]
I am using kdeconnect plugin for accessing content on my mobile device, when I try to open  a file there it crashes.

But then it starts crashes every time I open any file, not only through kdeconnect.

Reproducible: Always

Steps to Reproduce:
1. Access file on through kdeconnect.
2. Observe how it crashes.
3. Now open any file on your computer and see it how crashes again.

Actual Results:  
Crash

[backtrace](https://github.com/libgit2/libgit2/files/292293/bt.txt)

Originally reported https://bugs.kde.org/show_bug.cgi?id=361537

**Comment by ethomson** [comment]
I don't understand.  What is kate?  What does this have to do with libgit2?

**Comment by dolohow** [comment]
Kate is a software that is using libgit2 where the crash happens.  Take a look at backtrace.

**Comment by ethomson** [comment]
If you're having trouble building and running the unit tests for libgit2, either ask a question about that, or open an issue if you think there's actually a bug.

If kdevelop crashes, then that's not a bug report that we can take action on.  In particular:

> Steps to Reproduce:
> 1. Access file on through kdeconnect.
> 2. Observe how it crashes.
> 3. Now open any file on your computer and see it how crashes again.

Those are *not* steps to reproduce a bug in libgit2.

**Comment by dolohow** [comment]
> If you're having trouble building and running the unit tests for libgit2, either ask a question about that, or open an issue if you think there's actually a bug.

In version 0.24.1 tests are passing.

> If kdevelop crashes, then that's not a bug report that we can take action on.

I understand, but I was told to report bug upstream.

**Comment by ethomson** [comment]
> I understand, but I was told to report bug upstream.

If they think the problem is with libgit2, then _they_ should open an issue so that we can resolve it together.

I know literally nothing about kdedevelop or kate.  _They_ should work with _us_ to track this down.

That said, it looks like you're crashing while libgit2 is trying to handle an error.  So I suspect that either something has blown up your memory and written all over it, or you've run out of it.

But it looks like you're using a year-old version of libgit2.  The first thing that I would do is upgrade and see if this still happens in a recent version.

**Comment by ethomson** [comment]
Hm.  I'm sorry - I'm very confused about what version you're running.  The bug you link to mentions libgit2 v0.23.  The stack trace mentions v0.24.  And you mention that the unit tests pass with v0.24.1...

Is kate using libgit2 v0.23 or v0.24?  Did you do that upgrade to v0.24?  Or did you plug in debugging symbols from two different versions?  Sorry, I'm a bit lost.

**Comment by dolohow** [comment]
I reported the bug when I was using v0.23 and tests were broken.  But the bug is still reproducible with v0.24.1

**Comment by ethomson** [comment]
Thanks for the follow up.

Without a repro case talking to libgit2, or some information about what, or how, kdeconnect or kate is doing anything, I really can't help.  Please encourage them to reach out.

**Comment by dolohow** [comment]
It happened again,

I think libgit2 is crashing when it cannot open a file

```
#9  0x00007f3d9e239abc in git_buf_vprintf (buf=buf@entry=0x7f3d78003668, format=format@entry=0x7f3d9e2df28d "Could not read directory '%s'", ap=ap@entry=0x7f3d7f09b370) at /home/dlh/abs/libgit2/src/libgit2-0.24.6/src/buffer.c:379
#10 0x00007f3d9e25cd04 in giterr_set (error_class=error_class@entry=2, string=string@entry=0x7f3d9e2df28d "Could not read directory '%s'") at /home/dlh/abs/libgit2/src/libgit2-0.24.6/src/errors.c:62
```

[backtrace](https://bugsfiles.kde.org/attachment.cgi?id=103694)

**Comment by dhaumann** [comment]
Could you please reevaluate? This issue is closed, even though a crash clearly happens in libgit2 as I see it. Would be nice if you could have a look again. Thanks! :-)

**Comment by ethomson** [comment]
> Could you please reevaluate? This issue is closed, even though a crash clearly happens in libgit2 as I see it. Would be nice if you could have a look again. Thanks! :-)

Are you seeing it?  Are you running kate or kdevelop or whatever program this bug report is about?  Are you a kate developer?  If not, why aren't you talking to them about this problem so that - again - we can work together?  How often does this happen?  Same stack trace or no?  What's going on when this happens?  Concurrency on the filesystem?  Directories being removed?  What platform are you on?  Can you reproduce it?  If so, that would be great, and I _would_ love to evaluate the situation and fix it if there's a problem.

But there are literally zero details that can help track this problem down, and without an actual bug report with reproduction steps then there's not a lot that we can do.

**Comment by ethomson** [comment]
Actually, after blaming the line that sets that error message, I take that back; there have been some independent changes that may fix this problem.

Can you upgrade to the latest release of libgit2?  If _that_ doesn't fix your problem then I will indeed need additional information to troubleshoot this.
