### ISSUE TITLE
git_config_parse_int64 (and git__strtol64) fails to parse maximum negative int64

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3817]
`git__strtol64`, used by `git_config_parse_int64`, parses the integer as positive and tracks the sign separately.  As a result, it cannot parse the maximum negative int64, -9223372036854775808.

(This is incredibly minor and low-priority; I ran into it when writing a test suite for a language binding.)

**Comment by rkrp** [comment]
I am a beginner in contributing to opensource projects. I would like to pick this one up.

I am thinking, this can be fixed by replacing 

```c
nn = n*base + v;
```
as

```c
nn = n * base + (neg ? -v : v);
```

If this is illegible, it can be replaced with an if..else block.

Also, the check for overflows must be rewritten accordingly. Otherwise `(nn < n)` would be true for any negative number, resulting in an overflow. 

Please let me know if I am on the right track.

**Comment by pks-t** [comment]
@rkrp I think your best bet to fix the issue is to write some unit tests first. Unit tests help in specifying the actual behavior of functions so that you can then check if your fix actually solves the error mentioned in this ticket as well as not breaking other use-cases.

`git_config_parse_int64` is called by `git_config_get_int64`, which is being tested in `tests/config/read.c`. You could simply add a test case which tries to parse various "extreme" values like INT64_MAX or INT64_MIN and then verify that we actually parse the numbers correctly. As we currently don't parse them correctly, you should see an error in the test suite now.

When you have reproduced the error, try to fix it and re-run the test suite to verify that your tests now actually succeed. Like this you can be sure your fix is correct and we will also have a unit test present that will help spot regressions for this code in the future.

Let me know if you need any help with this.

**Comment by rkrp** [comment]
@pks-t Thanks for the instructions. Now that I have done it, starting out by writing unit tests make more sense. 

- added the borderline cases to the unit tests which obviously caused it to fail. 
- fixed `git__strntol64()` at `src/util.c` to parse `INT64_MIN` without failing
- tests are now running without any fail

Please let me know if I can fork and send a pull request now.

**Comment by ethomson** [comment]
> Please let me know if I can fork and send a pull request now.

That sounds great, please do!  😀

**Comment by rkrp** [comment]
@ethomson I just have a small query. I was asked by @pks-t to write tests concerning `git__strtol64()` in `tests/config/read.c`. I've fixed the bug. It is working fine now. But, I just now happened to notice that tests for `git__strtol64()` is written in `tests/core/strtol.c`. Should I make another commit by moving the tests to `tests/core/strtol.c` or shall I proceed with the pull request?

**Comment by ethomson** [comment]
@rkrp If you're testing `strtol64` itself, then I think that moving the tests into `core/strtol.c`.  :)

**Comment by pks-t** [comment]
Huh? Strange I didn't find the `core/strtol.c` tests, I've grepped for `git__strtol64` but wasn't able to spot these.

**Comment by rkrp** [comment]
Sent pull request #3846

**Comment by joshtriplett** [comment]
Closing this, as pull request #3846 fixed it. Thanks!
