### ISSUE TITLE
file paths for nested submodules are to long to be resolved

### ISSUE THREAD

**Issue by jensborn** [libgit2/libgit2#3821]
I have a project that has a three level nested submodules structure. When I try to commit things tortoise tells me that the submodules are dirty and tries to commit them as well - what is very beautiful. But in my case the path tortoise tries to resolve (don’t know for what it is searching for in the parent directories, maybe the origin definitions?!) seems to be too long for them. So I get the failure message every time I try to commit the deepest submodules:
Could not get HEAD hash. libgit2 returned: Failed to resolve path ‘E:/Tangram/Tool/ OOo Draw Extension/Tangram_Lector_Workstation/Submodules/Tangram_InteractionManager/Submodules/BrailleIO/../../../../../../../.git/modules/Tool/OOo Draw Extension/Tangram_Lector_Workstation/modules/Submodules/Tangram_InteractionManager/modules/Submodules/BrailleIO’: Der Dateiname oder die Erweiterung ist zu lang _[in German – means ‘file name or extension is too long’]_

The Main repository is staring at ‘E:/Tangram’.

Used in TortoiseGit 2.1.4.0 (20160513-bd31542a; C:\Program Files\TortoiseGit\bin) git version 1.9.5.msysgit.1 (C:\Program Files (x86)\Git\bin; C:\Program Files (x86)\Git\; C:\Program Files (x86)\Git\etc\gitconfig; C:\ProgramData\Git\config)

**Comment by jensborn** [comment]
from the tortoise team I get the answer:

*Sven Strickroth @mrtux commented about 10 hours ago Owner
Windows has a general problem with paths longer than 255 chars. Here, the issue lies inside libgit2. Sorry, there is nothing we can do about it.*

**Comment by ethomson** [comment]
Do you have `core.longpaths` on?

**Comment by ethomson** [comment]
(Note, we don't support `core.longpaths` yet, so I'm not suggesting a solution.  I'm just trying to understand what you expect to happen, because it's difficult to understand what should happen in TortoiseGit, since I've never used it and certainly didn't write it.)

If you _do_ have `core.longpaths` on, then this is a fairly straightforward bug report.

If you _do not_ then I think it would be helpful if _they_ would describe the sort of failure mode that _they_ want.  Because there's nothing to do here _but_ fail, as far as I can tell, and if they want a different failure to handle, then I think that they should describe it...  Putting the onus on you, the end user, is not helpful because since you're not using libgit2 directly, but instead using TortoiseGit, I don't know when I've fixed it for you.  :P

**Comment by csware** [comment]
To shed some light on what's going on inside TortoiseGit: We're opening the (submodule) repository using `git_repository_open` and calling `git_repository_head_unborn` and `git_revparse_single(&object, repo, "HEAD")` and this fails inside libgit2 (suppose libgit2 is already failing on `open`).

**Comment by ethomson** [comment]
But what would you prefer to occur?  https://github.com/libgit2/libgit2/issues/3696 suggests that we silently ignore things, is that preferable?  Does git core work here (without `core.longpaths`)?  Should we spend much time on this or should we just turn `core.longpaths` on by default?  Especially now that Windows 10 is going to drop the `MAX_PATH` limitation?

**Comment by csware** [comment]
The reporter told that `core.longpaths` is set to on.

Removing the MAX_PATH limitation might not work for lots of already compiled tools, because of hardcoded buffers with MAX_PATH-length.

**Comment by csware** [comment]
Cross-ref: #3053

**Comment by ethomson** [comment]
I agree that this is a dup of #3053.  I think that the current behavior - at least, when `core.longpaths` is off - is correct and that we should raise an error message.
