### ISSUE TITLE
Add support for Universal Windows Platform

### ISSUE THREAD

**Issue by anhoavu** [libgit2/libgit2#3832]
I think the only thing we need to change is about file system handling. Many of the existing Win32 calls seem to be available but some like CreateFileW, GetModuleHandleW, environment and registry stuffs are not (due to obvious security constraint of the platform). It would also be great if we can extract OS-dependent stuffs into an interface which clients can supply.

**Comment by ethomson** [comment]
I'm not _entirely_ sure what you're requesting here, but if the goal is to simply _not_ do any file system access, then I think those interfaces are already defined.

It sounds like you want some proper subset of libgit2 that only ever speaks to bare repositories, has no default backends (since those are all implemented in terms of the filesystem) and has no working directory functionality.  Then you would provide your own object database, reference database and configuration backends that talk to whatever storage mechanism it is that you use.

At present there is no mechanism to build this subset, but it seems like it may be possible to separate.

Is this something that you want to tackle?  I don't believe that anybody else has shown any interest in this subset of the library.

**Comment by anhoavu** [comment]
Well, I do need non-bare repository with working directory. The problem is that UWP limits the FileAPI, only allows a subset of it so I need to find a way to avoid inaccessible API calls.

**Comment by ethomson** [comment]
I see, so `CreateFile` is not available in UWP, but they offer some reasonable replacement.

That's actually quite a bit _easier_.  The interface that is used in libgit2 is basically the POSIX API (with a very few exceptions).  You can see how we emulate - for example - something very similar to the POSIX `rename` call using `MoveFileEx`:  https://github.com/libgit2/libgit2/blob/77394a27af283b366fa8bb444d29670131bfa104/src/win32/posix_w32.c#L609

(For a number of things, like our `open` call we simply delegate to the Win32 POSIX emulation API with things like `_wopen`.)

I don't know enough about UWP to know how much it does offer, but my initial thought would be to create a third variant of these, perhaps creating a `uwp` directory, and creating `uwp/posix_uwp.c` and starting to implement the necessary functions in terms of what UWP supports.

There are likely places that are sort of poorly abstracted on the assumption that there's Win32 and POSIX.  (I think the fast directory reader may fall into this category.)  But on the whole most of the library uses the `p_*` POSIX emulation calls, so that really should be the main interface to implement.

However if there are only _a few_ places then it would make sense to use as much of the existing Win32 POSIX emulation as possible.

**Comment by anhoavu** [comment]
@ethomson Thanks for your help. I have implemented missing Win32 functions such as `GetFileAttributesW` using available ones `GetFileAttributesEx` and `#ifdef` the registry stuffs. There is an issue when creating refs such as `refs/remotes/origin/master`, libgit2 attempts to remove the directory that might clash with the ref file https://github.com/libgit2/libgit2/blob/77394a27af283b366fa8bb444d29670131bfa104/src/refdb_fs.c#L725-729 but this somehow fails for me at the moment when cloning since no such directory structure exists (i.e. `remotes` is not yet to exist under `refs`). [Commenting out this part works.] I think this might be at Microsoft's fault and some peculiarity with the replacement API.

**Comment by ethomson** [comment]
Happy to see a PR for this, but we don’t have any plans to implement this ourselves so I’m closing this issue.
