### ISSUE TITLE
Out of memory error under VS2015

### ISSUE THREAD

**Issue by soen-ionoco** [libgit2/libgit2#3852]
Hi-
We've just started to adopt Git for our projects - And some of our projects have huge binary assets (the typical size for each project is around 10gig..), and unfortunately for us, due to our decentralised nature, we cannot use LFS.

We've tried committing an 800mbyte binary file using Visual Studio 2015 but we simply get an "out of memory" exception a couple of seconds into the process. Here's the version numbers that VS2015 uses internally:
LibGit2Sharp 14.0.25029.0
LibGit2 14.0.25309.0

Does anyone have any ideas? I've already tried limited the memory usage by setting the pack window size, turning deltas off, etc, but these settings appear to have no bearing under libgit2. Git For Windows commits these files fine, but I suspect we're hitting the limit of the 32bit memory space (as Visual Studio is surprisingly not yet 64bit).

I'd love to hear your thoughts,
Soen

**Comment by carlosmn** [comment]
If you're having issues with Visual Studio you should contact Microsoft via their support channels. The versions of the libraries they ship are customised and if there's any workarounds, it's Microsoft support who would know. They're the ones who deal with VS and know about its use.

**Comment by soen-ionoco** [comment]
Thanks. I hadn't realise that Microsoft had modified your original code - I've also raised this with Microsoft.  

I have tried setting the file to being binary (and explicitly turning off deltas) in the .gitattributes, but it doesn't seem to modify the behaviour. Perhaps Microsoft's custom version of libgit2 is ignoring it (they have actually provided the source, so I could always have a quick look through that, I guess!) 

My only guess is that something is trying to malloc 800Mbytes of memory to read the file into memory, but it would be struggle to fit that into a 32bit address space along with the whole of Visual Studio.

Ultimately the test here should be that I build a test harness for libgit2's most recent version and try the commit again via that. That would help diagnose where the fault lies; whether Microsoft's modifications have broken something in libgit2, or whether this same issue exists in both codebases.

**Comment by soen-ionoco** [comment]
Just found another thread with a similar problem; basically large blobs are breaking libgit2 under 32bit. Their solution was to move to 64bit, but unfortunately, Microsoft doesn't provide a 64bit IDE (yet).

https://github.com/git-tfs/git-tfs/issues/224

**Comment by jeffhostetler** [comment]
Yes, you are probably running out of memory, since VS is a 32bit process.  I doubt that we (Microsoft) broke libgit2 here, but VS2015 did ship with a slightly older version of libgit2 than what is current, so there may be recent fixes in upstream that we don't have yet.

So yes, please log a bug with Microsoft and we'll investigate.  Thanks.

WRT your test case, you might take a look at the following and adapt to match your specifics:
https://github.com/jeffhostetler/public_libgit2/commit/a7c99bd47ac8d35598a86ca2aa03190bd37ce2e7
https://github.com/jeffhostetler/public_libgit2/commit/6c210f645ec4f2c556999ffb9430c03d21103314
https://github.com/libgit2/libgit2/pull/3211
https://github.com/libgit2/libgit2/pull/3197
