### ISSUE TITLE
git_signature_from_buffer parameters

### ISSUE THREAD

**Issue by txdv** [libgit2/libgit2#3857]
I was trying to port libgit2sharp to the newest libgit2 and I saw some difference in some signatures. There is [git_signature_from_buffer](https://github.com/libgit2/libgit2/blob/master/include/git2/signature.h#L76) and [git_diff_from_buffer](https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L1192).

``` c
GIT_EXTERN(int) git_signature_from_buffer(git_signature **out, const char *buf);
// ...
GIT_EXTERN(int) git_diff_from_buffer(
    git_diff **out,
    const char *content,
    size_t content_len);
```

It feels a bit strange that two signatures with basically the same functionality (do something with a given buffer) have different signatures. I personally would prefer later signature (the one with the content_len specified).

C has null termination for strings (by convention) and of course one can use the good old (pointer, length) pair. However, in C# if I do a conversation with Encoding::GetBytes from a string to a byte[] buffer, I get a byte buffer which is not null terminted. So, if I want to expose a _from_buffer function i'd in csharp with a byte[] signature

``` csharp
static extern int git_signature_from_buffer(ref git_signature *out, byte[] buf)
```

for lets say a function like

``` csharp
public class Signature
{
  public static From(byte[] buffer)
  {
    // need to create another buffer with size + 1 and copy everything
    // call git_signature_from_buffer
  }
  // or we can just create another constructor
  public static Signature(byte[] buffer)
  {
    // need to create another buffer with size + 1 and copy everything
    // call git_signature_from_buffer
  }
}
```

I would have to create another buffer (like the comment already says) with the size of the original buffer and the last one byte empty set to 0 (the null terminator).

If I want to expose a the same functionality with a string as a parameter, like:

``` csharp
public class Signature
{
  public static From(string signature) { }
}
```

The marshaller of course takes care of the null termination:

``` csharp
[DllImport(libgit2)]
internal static extern unsafe int git_signature_from_buffer(
    out git_signature* signature,
    [MarshalAs(UnmanagedType.CustomMarshaler, MarshalCookie = UniqueId.UniqueIdentifier, MarshalTypeRef = typeof(StrictUtf8Marshaler))] string buffer);
```

but it becomes much more difficult to create a function with a byte[] signature.

So my proposition is to use always a pointer, length pair in _from_buffer functions and maybe introduce a _from_string convenience function to each of them which accepts a pointer to a a null terminated string and does a strlen and passes it to the _from_buffer method.

**Comment by ethomson** [comment]
> It feels a bit strange that two signatures with basically the same functionality (do something with a given buffer) have different signatures.

Fair, the nomenclature is odd here, but:

> I personally would prefer later signature (the one with the content_len specified).

It's not about preference, it's about function:  strings are null terminated in C.  Making users call `strlen` unnecessarily just to tell us the length is annoying and usually inefficient.

Users of `git_diff_from_buffer`, on the other hand, are slinging around patch files, and want to be able to take a slice out of (say) a larger file without duplicating it and without throwing a `NUL` in the middle of some other data before passing it to us.

I'm not sure that I am entirely understanding the problem area here...

> So, if I want to expose a _from_buffer function i'd in csharp with a byte[] signature

What's the problem you're trying to solve by doing this?  a `byte[]` without a corresponding encoding is just binary, so you couldn't convert it to a UTF-8 string to give to libgit2.  Are they implied UTF-8 bytes?

Even with `byte[], Encoding` to disambiguate:  what caller would want this method?

You raise a good point with the consistency of naming between functions that take a null-terminated `char *`, a `char *, size_t` and a `git_buf`.  We use the name `from_buffer` to generally apply to all of those, I think.  I'm not unhappy about this, because any given function would accept the type of arguments that make the most sense for it.  But it does bear further consideration to avoid confusion.

**Comment by txdv** [comment]
> What's the problem you're trying to solve by doing this? a byte[] without a corresponding encoding is just binary, so you couldn't convert it to a UTF-8 string to give to libgit2. Are they implied UTF-8 bytes?

Well that would mean converting a byte[] a string in c# and converting it back to a byte[] with the marshaller but I guess since it is always a one liner the performance impact is minuscule and should be just neglected.

> Users of git_diff_from_buffer, on the other hand, are slinging around patch files, and want to be able to take a slice out of (say) a larger file without duplicating it and without throwing a NUL in the middle of some other data before passing it to us.

Yeah, I kinda see now that one of them is taking a one liner and the other one takes a something big, so the general convention is to just use a null terminated char*.

I guess I'm seeing an issue where there is none, I just got confused by the same suffix.

**Comment by ethomson** [comment]
> Well that would mean converting a byte[] a string in c# and converting it back to a byte[] with the marshaller but I guess since it is always a one liner the performance impact is minuscule and should be just neglected.

Right - this is what I'm trying to understand a bit better.  My original assumptions don't necessarily understand your use cases.

Do you actually have a `byte[]` of a signature in c#?  What encoding is it in?  Where did it come from?  Are you (de)serializing something on a wire?  Just trying to understand.  :D

I don't want you to have to `byte[]` -> `string` -> `byte[]`.  😞   I think we can come up with a better solution than that.

**Comment by txdv** [comment]
Well, it is more of a hypothetical, I personally don't do any serialization from the wire right now. But suppose I read something from a stream as a byte[], I have to convert it now to a C# string then back to a byte[] (+1 size for null terminator, which the marshaller does) and then the C function uses strlen to determine the length of the buffer ... which was already known from the very beginning. Some needless conversation here and there and then execution of strlen.

If I have a function with the signature *const char* buffer, size_t buffer_length*, I can use a null terminated string with it easy peasy just by passing *buffer, strlen(buffer)*, the other way is not that trivial, because if I have a *const char* buffer* which expects a null terminated string, but I have a *const char buffer, size_t length* pair, I need to create a new buffer which is by one byte bigger and copy everything into it and then pass that.

The downside of the pair is that uses more memory. Also harder to handle, because a char** (array of strings) is easier to handle than some construct consisting of a pointer and an integer. The APIs with a null terminated string are shorter (have one less argument) and there are many more places around which have multiple string arguments which would make the signatures longer.

But as I already said, the performance increase will be minuscule I doubt it really matters, the only thing that really bothers me is that both _from_buffer functions have different signatures.

**Comment by ethomson** [comment]
I understand the complaint about consistency, but these are quite different APIs.  Having to `dup` a few bytes of signature doesn't bother me, and in the general case these should be `NUL` terminated.  I'm closing this, because I think that functions (like `diff` and `patch`) are outliers, but I agree that we need to be cognizant of consistency generally.  Please do open issues with APIs that bother you if you find others.
