### ISSUE TITLE
inet_pton test in core/posix uses arbitrary hardcoded address families

### ISSUE THREAD

**Issue by mmuman** [libgit2/libgit2#3872]
In addition to passing NULL as buffers (which asserts Haiku's inet_pton()), the [inet_pton test](https://github.com/libgit2/libgit2/blob/master/tests/core/posix.c#L93) uses arbitrary hardcoded values to test error reporting, which can and actually do collide with some other tested values.
For example, [AF_INET6](http://cgit.haiku-os.org/haiku/tree/headers/posix/sys/socket.h#n24) is 5 on Haiku.
And do we really need to test two of those?

If you really want to test with some other value, we could try AF_MAX, although on BSD [it doesn't seem to be always defined (_BSD_VISIBLE)](http://fxr.watson.org/fxr/source/sys/socket.h#L245) and when it is it actually is one of the possible values.
How about max(AF_INET, AF_INET6)+1 ?

It still seems fragile though, as it can still be a valid and actually implemented address family.
Also note that not all systems actually support (and even define) AF_INET6. MiNT (not the GNU/Linux distro!) comes to mind (but it does define AF_APPLETALK).

I'd propose some fallbacks from the least known family, something like:

``` C
#if defined(AF_DECnet)
#define AF_BAD AF_DECnet
#elif defined(AF_CHAOS)
#define AF_BAD AF_CHAOS
#elif defined(AF_APPLETALK)
#define AF_BAD AF_APPLETALK
#elif defined(AF_MAX)
#define AF_BAD AF_MAX
#else
#define AF_BAD (max(AF_INET, AF_INET6)+1)
#endif
```

**Comment by ethomson** [comment]
Since `inet_pton` takes an `int` for the address family, I'm relatively sure that it's quite easy to come up with values that are unsupported everywhere, like `INT_MAX-1` or `-1`.

In theory, we could also simply `cl__skip` this test on non-Windows, since the goal is to test _our_ `inet_pton` implementation, and if the system implementation is broken then there's not much that we could do about it anyway.  But it is quite nice to know that our implementation matches other platforms.  So it is nice to have it running everywhere.

**Comment by mmuman** [comment]
Yeah looks like I overengineered this one, INT_MAX-1 might do as well :)

**Comment by ethomson** [comment]
Well, I overengineered the original, trying to be cute with chaosnet.  😀

**Comment by mmuman** [comment]
Looks ok to me, thanks!
