### ISSUE TITLE
Do I have to free it

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#3927]
Hi guys, 
Do I have to free the **c_git_branch_reference_** returned by git_branch_next? 
This is the code I'm using.
Thank you.
```
git_reference* c_git_branch_reference_{};
git_branch_t branch_type{ GIT_BRANCH_LOCAL };
auto res = git_branch_next(&c_git_branch_reference_, &branch_type, c_git_branch_iterator_);
```

As a side note it seems rather strange to not be able to pass simply GIT_BRANCH_LOCAL as an argument to the git_branch_next function, but instead one has to give pointer. Any reasons for it?

**Comment by ethomson** [comment]
> Do I have to free the c_git_branch_reference_ returned by git_branch_next? 

Yes - see [this test](https://github.com/libgit2/libgit2/blob/77394a27af283b366fa8bb444d29670131bfa104/tests/refs/branches/iterator.c#L39) as an example.

> As a side note it seems rather strange to not be able to pass simply GIT_BRANCH_LOCAL as an argument to the git_branch_next function, but instead one has to give pointer. Any reasons for it?

You're not passing `GIT_BRANCH_LOCAL` - it's not a filter.  You give it a pointer to a `git_branch_t` so that the `git_branch_next` function can _set_ it.  The function gives you both the _reference_ and its _type_.

**Comment by smallB007** [comment]
@ethomson 
Hi, thank you for your answer. Everything (with regards to git_branch_next that is ;) seems to be clear.
Best regards
