### ISSUE TITLE
Is checkout --orphan supported?

### ISSUE THREAD

**Issue by ankostis** [libgit2/libgit2#3934]
(I hope it is the right place)
I cannot find anything in the docs or the code that seems relevant (the "orphan" matches in the code were for a specific branch named like that in the TCs).

**Comment by carlosmn** [comment]
Questions are generally a better fit for a place like StackOverflow, but to answer the question: `--orphan` is a just the command-line flag. There is no Git concept for it. What the flag does is generate an unborn branch, and you can do that by setting `HEAD` to point to a non-existent branch instead of creating it as part of your implementation of your equivalent to `checkout`'s branch-creation mode.
