### ISSUE TITLE
where is git.h located upon install

### ISSUE THREAD

**Issue by gideondsouza** [libgit2/libgit2#3951]
I have a fedora 24 system, I'm trying to use libgit2 in C project with CMake, however so far after installing with `dnf install libgit2` I *cannot* for the life of me figure where the **git.h** file is. 

I should highlight that the install doesn't create  a `.pc` file and that is what I'm trying to do manually so that I can use pkg-config.

**Comment by gideondsouza** [comment]
So it seems like the solution is to install `libgit2-dev`, isn't this not so great? The libgit2 package is already a developer package right? :/ quite a confusing ordeal!

**Comment by ethomson** [comment]
Sorry @gideondsouza , we do not create or have control over the fedora packages.  However, this does sound correct.  Usually a package like `libgit2` would be the library itself, which is a dependency for other packages that use it.  If you - as a developer - wish to use `libgit2` yourself then you would install the `libgit2-dev` package.

However, I don't use Fedora, so I don't know what their policies look like, I'm just applying my knowledge of debian-like systems.  The best way to get an answer for this sort of question is on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2).

I'm closing this since we use the issue tracker for bugs and features in the library.  Thanks!
