### ISSUE TITLE
assert(count <= MAX_SHUTDOWN_CB && count > 0)

### ISSUE THREAD

**Issue by Vict0r-Lee** [libgit2/libgit2#3969]
Hi ,@carlosmn. I always get thsi assertion in function git__on_shutdown() when I use many threads to open the repository and make some git operation.Certainly,I use git_libgit2_init and git_libgit2_shutdown to start up and shutdown. 

I don't know whta that assertion means and how to avoid it.

**Comment by Vict0r-Lee** [comment]
Please forgive my awful English syntax. ^ ^

**Comment by pks-t** [comment]
libgit2 provides a mechanism to set up global state which is shared among all threads. This global state is initialized via the first call to `git_libgit2_init` and de-initialized on the last call to `git_libgit2_shutdown`. While initializing the global state, we also set-up a number of shutdown callbacks for subsystems. The number of callbacks which can be registered is currently fixed to 8, where 7 of these callback slots are used by libgit2 itself. We try to make sure that these callback slots are filled only once by using platform-specific support for atomics.

Regarding your bug: I can certainly envision some scenarios where we might be racy in initializing our global state when many threads are calling init/shutdown at the same time. Especially the pthread code looks racy to me when these calls are intermangled, which would be a bug on our side.

So: what platform are you on? Is your libgit2 compiled with threading support?

**Comment by Vict0r-Lee** [comment]
@pks-t  thanks for your answer. I changed the source code to become a single thread program and this bug has not appeared again.

Another question :how can I use the multi thread with libgit2.

thanks  again.

**Comment by carlosmn** [comment]
You can see the rules to follow for multi-threaded programs in the [THREADING.md](https://github.com/libgit2/libgit2/blob/master/THREADING.md) document.

The initialization functions have to be called in single-threaded context, as this is what is used to set up the multithreading capabilities.

**Comment by pks-t** [comment]
Ah, I've been searching for such a document but didn't spot it. I did expect that these requirements would have been part of `git_libgit2_init`'s documentation. Especially since it states that it "may be called multiple times", without any remarks. I'll fix this.

**Comment by Vict0r-Lee** [comment]
Thanks for everyone's "return".It's my honour to improve libgit2 with you.

**Comment by ethomson** [comment]
I don't think that `git_libgit2_init` is the problem here.  The goal with `git_libgit2_init` was that it _was_ callable in a multi-threaded context and IIRC, LibGit2Sharp's initialization relies upon this.  (In some environments, like IIS, you have limited control over how you're scheduled and there's no way to do this in a single threaded context.)

On Windows, we take a mutex in `git_libgit2_init` and `git_libgit2_shutdown` in order to handle this properly.

On Linux, we don't take a mutex, we use `pthread_once` to ensure that only a single `git_libgit2_init` is called and that initialization has occurred by the point at which `git_libgit2_init` returns.

What we _don't_ do on Linux is have any synchronization in `git_libgit2_shutdown` w/r/t `git_libgit2_init`.  That means that if you called `git_libgit2_shutdown` it could do a 1 -> 0 transition of the counter, shut all the systems down _but_ subsequent `git_libgit2_init`s would fail to actually re-initialize anything.

That would be my guess as to what's actually happening here.

**Comment by pks-t** [comment]
Yeah, I've spotted the exact same error yesterday. So if you agree that it is a bug and that we want to actually _allow_ initializing from multiple threads, I'll be happy to fix the issue and kill #3972

**Comment by ethomson** [comment]
Hmm, yeah, I suppose that fixing this so that you can reinitialize after the last `git_libgit2_shutdown` is probably appropriate...

I _think_ that in a multiple app domain situation when using LibGit2Sharp that a user could have this same problem:  two different .NET app domains have no way to share state between each other, they are isolated from each other, _but_ they can run native code which has no concept of the app domains!  Terrible stuff.  That means that they need to rely on libgit2 getting this right for them, and they can call `git_libgit2_init` and then `git_libgit2_shutdown` without having to know anything about what the other app domains are doing.

However, we should probably figure out a way to be explicit about this suckage in the documentation.  Calling `git_libgit2_init` in a single threaded context before spinning up your threads is massively encouraged.  Even if it _works_, and it should - at least in the sense that it doesn't crash ;), it's going to be a terrible experience to repeatedly tear down and re-initialize the global state.

**Comment by ethomson** [comment]
(To clarify: I don't super duper care about supporting multiple app domains, but that's the thing I always go back to when I think about the worst case of supporting multiple threads, and to remind myself that there is a legitimate use case where you don't have any knowledge of the larger native context.  Meh.)

**Comment by pks-t** [comment]
#3974 should fix the issue
