### ISSUE TITLE
Crash in merge_conflict_can_resolve_contents

### ISSUE THREAD

**Issue by tiennou** [libgit2/libgit2#4035]
I'm trying to write a merge example, and while running it against a trivial test repository, I hit a crash :

### Reproduction steps

- Code [here](https://gist.github.com/tiennou/9c3f022bb59b9648f8f4757a4d807065).
- History :
```
create file1            mod file1
      A ----------------- B            (master)
        \
         \     create file2
          -------- C                   (branch)
```
- Attempt to merge `branch` with `GIT_MERGE_FIND_RENAMES` set.
- Crash [here](https://github.com/libgit2/libgit2/blob/c655def1174f814c2adcafff7cecec4d47dc5830/src/merge.c) with a NULL-ptr dereference on `conflict->ancestor_entry.path`.

### Version of libgit2 (release number or SHA1)
SHA: c655def1174f814c2adcafff7cecec4d47dc5830

### Operating system(s) tested
OS X 10.11.6

**Comment by ethomson** [comment]
It certainly doesn't make sense that the statuses would be set to `RENAMED` if there's no ancestor.

Can you provide the repository that reproduces this?

**Comment by tiennou** [comment]
Here it is : https://www.dropbox.com/s/rerr364evi33257/test-repo.zip?dl=0. It's a pretty dumb repo I made up to test what would merge do.

I'm reproducing using the merge example in that other PR, running `./merge --git-dir=test-repo no-conflict`.

**Comment by tiennou** [comment]
Aaaand uncomment the merge options, obviously 😉.

**Comment by ethomson** [comment]
It turned out that the problem here is that `GIT_MERGE_FIND_RENAMES` was set, but `rename_threshold` was `0` and we did not provide a better default in this case.  So during rename detection, we saw items that had no similarity (literally, a `0` similarity) but that was equal to our rename threshold, so we decided to try to resort our list of differences to handle them as renames.

Of course, they _weren't_ renames, and the objects need not be set up as if they were.  In this case, there was a change that had no ancestor at all, which we were treating as a rename.

Not letting `rename_threshold` be `0` when `GIT_MERGE_FIND_RENAMES` is set fixes this problem, plus gives us a good default in that case.
