### ISSUE TITLE
NTLM credentials not posted by libgit2 if Basic authorization header stay before NTLM header

### ISSUE THREAD

**Issue by maximpashuk** [libgit2/libgit2#4039]
### Reproduction steps
1. Setup git server (TFS 2017 OnPremise in my case) to return http headers in order then Basic over NTLM
```
WWW-Authenticate: Bearer
WWW-Authenticate: Basic realm="uk-tfs01.2gis.local"
WWW-Authenticate: NTLM
```

2. Use libgit2sharp with DefaultCredentials provider (internally call **git_cred_default_new**) to fetch remote data.

### Expected behavior
Fetch completed successfully

### Actual behavior
Get an error "Too many redirects or authentication replays"

### Version of libgit2
libgit2sharp 0.22 which uses libgit2 0.24 (sha 785d8c4)

### Operating system(s) tested
Windows 10 x64

### Comments
If I setup TFS 2017 to return http headers in order then NTLM over Basic
```
WWW-Authenticate: Bearer
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="uk-tfs01.2gis.local"
```

then default credentials passed successfully, so I think this is a bug in libgit2, probably in code handling WinHTTP authentication.

I attached sample powershell script I used to test libgit2 behaviour: [gitfetch.zip](https://github.com/libgit2/libgit2/files/663092/gitfetch.zip), hope this helps.
Just put it to git controlled folder and run, it should fetch master branch from remote using DefaultCredentials.

**Comment by ethomson** [comment]
Thanks for reporting this; we'll take a look.

**Comment by tsemer** [comment]
If this is of any value: We have an acceptance environment with on-premise TFS 2017, while production was not yet upgraded and is still TFS 2015. Cloning a repository via TFS 2017 returns "Too many redirects or authentication replays" error. Cloning a repository via TFS 2015 seems to work fine. I'm using DefaultCredentials.
Version: libgit2sharp 0.22.0

**Comment by maximpashuk** [comment]
@tsemer, I was facing the same issue, I solved it by enabling Basic auth in IIS on TFS 2017 web site.
This caused Basic header be lower than NTLM and DefaultCredentials starts working.

**Comment by tsemer** [comment]
@maximpashuk thank you, alas I've now tried that and it did not seem to make a difference. Do you have any other enabled authentication methods on the TFS website?

**Comment by maximpashuk** [comment]
@tsemer Anonymous, Basic and Windows with NTLM provider. Also https set up in IIS.
Have you checked that htts auth headers are in order I said?

**Comment by graffen** [comment]
I have this issue too (specifically connecting from GitKraken to TFS2017 which worked fine with TFS2015), and enabling Basic Auth didn't solve it here either. 
Doesn't Visual Studio also use libgit2? No problems connecting to TFS2017 from there. So it's a bit weird.

**Comment by ethomson** [comment]
Yes, it looks we do depend on the order of the headers; I should be able to sort out a fix to this.

**Comment by MustafaJamal** [comment]
Hi,

This issue is still open for LibGit2Sharp, when it will be fixed in it?

**Comment by ethomson** [comment]
@MustafaJamal I don't have an ETA; as soon as I have some spare time.  Thanks for your patience!

**Comment by MustafaJamal** [comment]
Thanks @ethomson ! I will be waiting ...

**Comment by ethomson** [comment]
@MustafaJamal LibGit2Sharp now includes these changes, as of `master`, or in the prerelease nuget package https://www.nuget.org/packages/LibGit2Sharp/0.24.0-pre20170124092542

**Comment by MustafaJamal** [comment]
@ethomson Many thanks! I checked it and it's working fine. You've made my day 👍

**Comment by ethomson** [comment]
Thanks @MustafaJamal !  Your kind words just made mine!  😀

**Comment by nemecr** [comment]
Not working unless I added Basic Authentication to IIS with TFS2017.

**Comment by smartin34** [comment]
It even does not work with Basic Authentication enabled on TFS2017 RTW. I've tried the 0.24.0-pre20170124092542

                    LibGit2Sharp.PullOptions options = new LibGit2Sharp.PullOptions();
                    options.FetchOptions = new FetchOptions();
                    options.FetchOptions.CredentialsProvider = new CredentialsHandler(
                        (url, usernameFromUrl, types) =>
                            new DefaultCredentials());

                    LibGit2Sharp.Commands.Pull(repo, new LibGit2Sharp.Signature(Environment.UserName, Environment.UserDomainName, new DateTimeOffset(DateTime.Now)), options);

**Comment by ethomson** [comment]
@smartin34  You cannot use `DefaultCredentials` with HTTP basic authentication.

It's not clear to me yet that these are related.  Do specific username/password credentials work?  Did this work with TFS 2015?  Can you share a packet dump?

**Comment by nemecr** [comment]
Using last (pre) version of LibGit2Sharp.0.24.0-pre20170124092542 with LibGit2Sharp.NativeBinaries.1.0.165, both are the last versions available on NuGet (I hope).

The problem is that when you use TFS 2017 without Basic Authentication installed on IIS where TFS web is running, client receives this sequence of HTTP headers in 401 response (ordering of NTLM and Negotiate may vary depending of TFS setup):

WWW-Authenticate: Bearer
WWW-Authenticate: Basic realm="http://mytfsserver:8080/tfs"
WWW-Authenticate: NTLM
WWW-Authenticate: Negotiate

but after Basic Authentication is installed on IIS and enabled for TFS website (restart of IIS is needed to have the Basic Authentication option visible in IIS manager (AFAIK)), headers changes like this:

WWW-Authenticate: Bearer
WWW-Authenticate: NTLM
WWW-Authenticate: Negotiate
...some other headers here...
WWW-Authenticate: Basic realm="mytfsserver"

Setting default credentials for authentication does not mean that LibGit2 does some NTLM negotiation itself, it means that WinHTTP (DLL shipped with Internet Explorer) is configured to send the default credentials (those of logged in user's) for all IE zones (not just Intranet, LocalComputer and Trusted servers) - see apply_default_credentials in libgit2-master/src/transports/winhttp.c. But apparently there is a problem, because WinHTTP doesn't know how to handle first case of authenticate headers and doesn't send any kind of authentication. This results in another 401, etc. ...and after six attempts the exception "Too many redirects or authentication replays". Second form of headers result in normal GET-401-GET-200 (or the same for POST) flow.

**Comment by ethomson** [comment]
So...  is that a no on the packet dump?

Are you logged in to the domain on the client computer?  Is there a proper trust relationship between the client computer's domain and the server's?

What clients _are_ able to communicate to your TFS server?

Have you configured your server's SPN properly?  Can you sniff a connection to the server where a client (IE or Visual Studio, perhaps) is sending an SPNEGO authentication header?  Can I get a copy of _that_ too?

If you turn off Negotiate in the TFS Administrator console do things start to work?

**Comment by nemecr** [comment]
> So... is that a no on the packet dump?

Don't know what are you talking about....yes, these headers are from packet dump (Wireshark). I currently don't have the dump, but only interesting change I've already described in my post before.

Yes, I am logged in to the domain. Server and client are in the same NT domain, so trust is not needed.

> What clients are able to communicate to your TFS server?

TortoiseGit worked OK even before the Basic Authentication change, IMHO.

SPN/SPNEGO: This is all Greek to me. ;-)

AFAIK turning off the Negotiate completely is not possible, the TFS (and IIS) only allows to change order in which these 2 schemes are sent in WWW-Authenticate headers. If you choose NTLM in TFS admin console, you are only saying to prefer NTLM, but Negotiate is not disabled.

**Comment by ethomson** [comment]
> Don't know what are you talking about....yes, these headers are from packet dump (Wireshark). I currently don't have the dump, but only interesting change I've already described in my post before.

No, I really want _a dump_, this description is not enough data to troubleshoot this.  What the server is sending is interesting, but I need to know what the client is replying with, and I need to see the entirety of the handshake.  (SPNEGO and NTLM are multi-step.  I would like to see them all.)

In particular, is the client trying to send SPNEGO (a/k/a Negotiate a/k/a Kerberos) credentials and failing?  Is the client trying to send NTLM?

Without this, I can only guess as to what is going wrong.  With your description of the headers, I would expect the client to try Negotiate, and never try any other protocol.

> AFAIK turning off the Negotiate completely is not possible, the TFS (and IIS) only allows to change order in which these 2 schemes are sent in WWW-Authenticate headers. If you choose NTLM in TFS admin console, you are only saying to prefer NTLM, but Negotiate is not disabled.

No, that's not correct.  If you choose _Negotiate_ in the TFS admin console, you are saying to prefer _Negotiate_ but _NTLM_ is not disabled.

However, if you enable _Negotiate_, then there are additional steps that are required.  [If you do not set up an SPN](http://www.edwardthomson.com/blog/authenticating_git_clients_to_tfs_using_kerberos.html), then clients cannot speak Negotiate.  If you haven't done this, then we will _not_ be able to connect.

The reason I asked for a _successful_ negotiation from a client is because I want to see if Negotiate is truly set up correctly, or if successful clients are falling back to NTLM.  As far as I know, nobody does a fallback from Negotiate -> NTLM, because if you've asked for Negotiate, then silently falling back to a less secure protocol would be surprising, but anything is possible, I suppose.

Note that there's a nonzero chance that there could be some sensitive information in a packet dump like the username and domain.  Please feel free to send this information to me offline if you would like.

**Comment by nemecr** [comment]
I've just sent the requested dumps to you, check Inbox and (possibly) Spam folder.

**Comment by ethomson** [comment]
I received them; I'll take a look shortly.  Thanks!

**Comment by smartin34** [comment]
Are there any news on this issue?

**Comment by MustafaJamal** [comment]
Hi @ethomson !

In reference to our last conversation in this thread on January 24, 2017, library is working fine if we use UserNamePassword Credentials or Default Credentials with TFS 2017 BUT when we tried to use it with PAT/Access Tokens it failed to authenticate. So, we figured out that PAT/Access Token authentication requests are fulfilled successfully if we use extra header i.e. 

`$ git -c http.extraheader='Authorization: Basic cGF0Ond0cTJ1M2tkaHJwc2U2ZzRreDQ0Z2p2NGg1cDJ1N3Y1N25pZnc2aGZ3cHFlenVob2ZoNWE=' ls-remote 'http://mjtfs2017:8080/tfs/DefaultCollection/_git/GITTest001/'`

We are not be able to find Extra Header support directly in LibGit2Sharp API, so is there any workaround possible ?

Thanks,
Mustafa

**Comment by Imranonline** [comment]
I am also facing the same issue trying to use PAT on VSTS and trying it
`  var options = new PushOptions
                {
                    CredentialsProvider = (x, y, z) => new UsernamePasswordCredentials
                    {
                       
                        Username="",
                        Password="Basic OnZqY2g3bXM0bGM0YnZmZWFreDQ3ZHNlc3lia3Rvbnh0b3pqeXRvcnEyaXNrN3p6cmF0dHE="
                    },
                };`

But the above gives me a Too-many-redirects-or-authentication-replays.

**Comment by rohitisinhk** [comment]
I am using Bitbucket Personal Access Token and can confirm if works A-OK, using Username as <Your_Username> and Password as "<Your Personal Access Token>"
