### ISSUE TITLE
git_repository_index succeeds on bare repo

### ISSUE THREAD

**Issue by novalis** [libgit2/libgit2#4067]
I noticed this while using #4016 on a bare repo.  But I think the issue is independent of that PR.

Here's a minimal repro (patch on 53b77311):
[fail-on-empty-index.patch.txt](https://github.com/libgit2/libgit2/files/685545/fail-on-empty-index.patch.txt)

I'm confused about why the code is written that way.  Is that really the intent?

**Comment by carlosmn** [comment]
```
+	// Bare repos have no index
+	cl_git_fail(git_repository_index(&idx, repo));
```

There is nothing stopping a bare repository from having an index file. git itself will create it if you do something like the "trick" to get `git` as a deployment method

    GIT_WORKTREE=/var/www/foo/ git --git-dir=/var/git/foo-web.git checkout -f HEAD

which only really works by chance because git would create `/var/git/foo-web.git/index` and keeps it between "deploys". You can also pass your own with `GIT_INDEX_FILE` and git will be just fine with this.

>I'm confused about why the code is written that way. Is that really the intent?

This is what git does, whether it's on purpose there I don't know, but it's now a behaviour to expect.

**Comment by ethomson** [comment]
I feel like setting `GIT_WORKTREE` means you have a worktree, which is the opposite of bare...

**Comment by carlosmn** [comment]
Running `git read-tree HEAD` on a bare repository will also create the index file there, it's just a lesser-known command.

**Comment by ethomson** [comment]
Though having said that, I suppose now I am compelled to define what it _does_ mean to be a "bare" repository, but I think that's going to get messy very quickly.  I think even `core.bare`, while well-intentioned, is probably not sufficient to the task.

**Comment by novalis** [comment]
OK, given that it is possible for a bare repo to have an index, and that there are cases where one would want to do so, I think this is a non-bug.  Thanks.
