### ISSUE TITLE
Data corruption in git_commit_extract_signature due to use-after-free

### ISSUE THREAD

**Issue by creideiki** [libgit2/libgit2#4118]
I'm trying to validate GnuPG signatures on commits using Rugged, the Ruby bindings for libgit2. About once in every ten attempts, the signature fails to verify because the end of the commit message is corrupted. After lots of single-stepping in GDB, I saw this:

```
Thread 1 "irb" hit Breakpoint 2, git_commit_extract_signature (signature=0x7ffd2414a250, signed_data=0x7ffd2414a270, 
    repo=0x561796286ea0, commit_id=0x7ffd2414a290, field=0x7f520b9be2df "gpgsig")
    at /var/tmp/portage/dev-libs/libgit2-0.25.1/work/libgit2-0.25.1/src/commit.c:766
[...]
769                     git_odb_object_free(obj);
[...]
2: eol = 0x56179628bf9b "[...]\nStyle/StringLiterals\n"
(gdb) next
770                     return git_buf_puts(signed_data, eol+1);
[...]
2: eol = 0x56179628bf9b "[...]\nStyle/StringLiter\300\005"
```

Looking at [`git_commit_extract_signature`](https://github.com/libgit2/libgit2/blob/909d5494368a00809bc42f4780e86f4dd66e4422/src/commit.c#L701) shows that the manipulation of `eol` follows this pseudo sequence:

```c
buf = git_odb_object_data(obj); //Just a pointer to the data, not a copy
h = buf;
eol = strchr(h, '\n');
git_odb_object_free(obj); //Corrupts obj, which is OK because it's not used anymore
git_buf_puts(signed_data, eol+1); //... but eol still points into obj
```
It seems like a bad idea to use a pointer into a freed object.

### Reproduction steps
1. Install Rugged.
2. Clone creideiki/workflow-tools@9045ea1fba5bdf25c394d559f08c6fc48454fe9c
3. Standing at the top of the cloned repository, run an interactive Ruby interpreter: `irb -r rugged`
4. Run the following Ruby commands to initialise Rugged:
```ruby
repo = Rugged::Repository.new('.')
commit = repo.lookup('9045ea1fba5bdf25c394d559f08c6fc48454fe9c')
```
5. Run the following command repeatedly, until the end of the returned string exhibits corruption:
```ruby
signature, plaintext = Rugged::Commit.extract_signature(repo, commit.oid)
```

### Expected behavior
The returned signature and plaintext should match the on-disk contents of the commit object.

### Actual behavior
Approximately once in ten attempts, the plaintext has a couple of its last bytes overwritten.

### Version of libgit2 (release number or SHA1)
0.25.1. Code still looks identical in current master (b4bd5e8).

### Operating system(s) tested
Fedora 7, Gentoo.

**Comment by ethomson** [comment]
Yes, I agree with your analysis.  Thanks for reporting this.  @carlosmn ?

**Comment by pks-t** [comment]
I think the issue has to be somewhere else. As can be seen, you first read the commit object from the repository and afterwards call `extract_signature` on it. So when `git_commit_extract_signature` now calls `git_odb_read`, the object must have a reference count of at least 3: you have a reference, the cache has a reference and the `extract_signature` function now has a reference, as well. So after calling `git_odb_obj_free`, it shouldn't actually be freed but instead have a reference count of at least `2`.

This all assumes that the object is indeed cached - so when the object is not cached (I don't know if this is possible at all), we can definitly run into a use-after-free. But I think the issue is somewhere else.

**Comment by ethomson** [comment]
Hmm, yes, that's an interesting point that the cache should hold a reference to this object, but you can disable the cache entirely (or, in theory, have an object evicted quickly.)

Putting Rugged aside, and thinking about libgit2 directly, you wouldn't need to have a reference to the object yourself, either, since you pass a commit ID.  So I think there's definitely a problem here, but I agree that it's unlikely that this is the problem that @creideiki is seeing.

**Comment by pks-t** [comment]
@creideiki Does the issue still persist for you or can this ticket be closed?

**Comment by creideiki** [comment]
Sorry, I was not aware that it was supposed to have been fixed; #4122 saying "Some findings related to #4118" did not sound like a complete fix to me. I'm travelling right now, but if you believe it to be fixed I'll try again when I get back home next week.

**Comment by pks-t** [comment]
Nah, no worries. Just wanted to have a short query on this as there is at least a chance of having this fixed by #4122, even though I think it unlikely.

**Comment by creideiki** [comment]
I just tried several runs of having Rugged 0.26.0b5 (which includes libgit2 b31b2360044f5960d52b7b12d1c9e48cd647a3fb) verify 347 different signed commits (including the one referenced in the original report), and I no longer see the corruption.

**Comment by pks-t** [comment]
Thanks for testing. I'm closing this issue then -- feel free to re-open it when you hit the same issue again.
