### ISSUE TITLE
libssh2_userauth_publickey_frommemory not found in static libssh2

### ISSUE THREAD

**Issue by Wicker25** [libgit2/libgit2#4120]
When I compile the library using a static libssh2 I get the following message:

```
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
```

This happens because CHECK_LIBRARY_EXISTS macro in CMakeLists.txt is not working properly with my libssh2.a .

```
CHECK_LIBRARY_EXISTS("${LIBSSH2_LIBRARIES}" libssh2_userauth_publickey_frommemory "${LIBSSH2_LIBRARY_DIRS}" HAVE_LIBSSH2_MEMORY_CREDENTIALS)
```

The LIBSSH2_* constants are ok and the object file contains the right symbols:
```
$ nm -g libssh2/install/lib64/libssh2.a | grep libssh2_userauth_publickey_frommemory
000000000000338a T libssh2_userauth_publickey_frommemory
```

Any idea?

### Expected behavior
```
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - found
```

### Actual behavior
```
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
```

### Version of libgit2 (release number or SHA1)
104a1b0bd997433a1838b4583c6604f32953344c

### Operating system(s) tested
Arch Linux 4.9.6-1-ARCH x86_64

**Comment by pks-t** [comment]
How exactly did you provoke CMake to use the static library only? Because usually, CMake will pull in the dynamic library only. I've just checked with both Arch Linux (which does not include the static libssh2 by default) and Alpine Linux (which does provide both static and shared libssh2). On both systems it will pull in the shared object, as expected.

I then tried to build a static library locally and install it to a custom prefix "/foo". Executing "PKG_CONFIG_PATH=/foo/usr/local/lib/pkgconfig cmake .." did in fact find the custom static libssh2 and also found the `frommemory` symbol.

So I'm a bit clueless. Could you please provide a simple step-by-step manual on how to reproduce your environment and thus the error?

**Comment by pks-t** [comment]
The problem is being tackled in #4604
