### ISSUE TITLE
git_diff_from_buffer: there is no initialization of git_diff_options version

### ISSUE THREAD

**Issue by gumenikav** [libgit2/libgit2#4158]
### Reproduction steps
```cpp
	git_patch *patch;
	git_diff_options diffOpts;
        git_diff_init_options(&diffOpts, GIT_DIFF_OPTIONS_VERSION);
	diffOpts.flags |= GIT_DIFF_FORCE_BINARY | GIT_DIFF_SHOW_BINARY;
	git_patch_from_buffers(patch, "i am object before", 19, "obj1", "i am object after", 18, "obj1", &diffOpts);
        git_buf *buff;
        git_patch_to_buf(buff, patch);
        git_diff *diff;
        git_diff_from_buffer(diff, buf->ptr, buf->size);
        git_diff_print(diff, GIT_DIFF_FORMAT_PATCH, DiffPrintCB, NULL);
```
### Expected behavior
Print diff
### Actual behavior
error: invalid version 0 on git_diff_options

### Version of libgit2 (release number or SHA1)
v0.25 + 1
### Operating system(s) tested
windows 10

**Comment by ethomson** [comment]
So...  this isn't a very helpful bug report.  You haven't really explained the problem that you're seeing, and the code that you've pasted simply won't compile:  you've declared `git_buf *buff`, but then you've used `buf`.

Presuming that's just a typo, this is still very incorrect.  If you're seeing that error message from the (corrected) code it's because something is stomping all over the stack, though I'm surprised that this compiling and that it isn't just crashing outright.

You need to pass a _pointer_ to the `git_patch *`, and a _pointer_ to an actually extant `git_buf`, and a _pointer_ to the `git_diff *`.

If you correct your code as above, then I do _not_ see the error message you're complaining about:

```
git_patch *patch;
git_diff_options diffOpts;
git_diff_init_options(&diffOpts, GIT_DIFF_OPTIONS_VERSION);
diffOpts.flags |= GIT_DIFF_FORCE_BINARY | GIT_DIFF_SHOW_BINARY;
git_patch_from_buffers(&patch, "i am object before", 19, "obj1", "i am object after", 18, "obj1", &diffOpts);
git_buf buff = GIT_BUF_INIT;
git_patch_to_buf(&buff, patch);
git_diff *diff;
git_diff_from_buffer(&diff, buff.ptr, buff.size);
git_diff_print(diff, GIT_DIFF_FORMAT_PATCH, DiffPrintCB, NULL);
```

Can you provide some more details on the problem that you're seeing?

**Comment by gumenikav** [comment]
Hello, Edward!
Thank you for reply.
There were a lot of typos, sorry.
There is no  GIT_BUF_INIT macro in the scope, so i used GIT_BUF_INIT_CONST("", 0) instead:
```cpp
	git_patch *patch;
	git_diff_options diffOpts;
	git_diff_init_options(&diffOpts, GIT_DIFF_OPTIONS_VERSION);
	diffOpts.flags |= GIT_DIFF_FORCE_BINARY | GIT_DIFF_SHOW_BINARY;
	git_patch_from_buffers(&patch, "i am object before", 19, "obj1", "i am object after", 18, "obj1", &diffOpts);
	git_buf buff = GIT_BUF_INIT_CONST("", 0);
	git_patch_to_buf(&buff, patch);
	git_diff *diff;
	git_diff_from_buffer(&diff, buff.ptr, buff.size);
	git_diff_print(diff, GIT_DIFF_FORMAT_PATCH, DiffPrintCB, NULL);
```
The problem is still with me: git_diff_print function returns -1 with klass 3 and message "invalid version 0 on git_diff_options".

**Comment by ethomson** [comment]
Okay, cool.  Thanks, @gumenikav - it looks like there are some problems with `git_diff_from_buffer`, I'll take a look.
