### ISSUE TITLE
how to checkout HEAD to specified reference or tag?

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4189]
I want to downgrade my program to previous version. Is it possible to do that in libgit2?
There is my code 
------------------------------------------------------
        string path = "C://Local//Path//to//my//repo";
	string tag = "refs/tags/v0.0.4";

	git_libgit2_init();

	const char * REPO_PATH = path.c_str();

	git_repository * repo = nullptr;
	git_repository_open(&repo, REPO_PATH);

	git_reference *ref;
	git_reference_lookup(&ref, repo, "refs/heads/master");

	git_reference *new_ref;
	git_reference_symbolic_set_target(&new_ref, ref,tag.c_str(),"message");
	
	
	git_checkout_options opts = GIT_CHECKOUT_OPTIONS_INIT;
	// how to specify options to use ref or tag?
	git_checkout_head(repo, &opts);
	
	git_repository_free(repo);
	git_libgit2_shutdown();

---------------------------------------------------------
Thanks

**Comment by ethomson** [comment]
Hi @jablkojem !  We use the GitHub Issue tracker to track issues like bugs and feature requests.

For help using libgit2, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) - this helps searchability and discoverability for users in the future so that everybody can benefit from these questions and answers.  😀 

Thanks!

**Comment by ethomson** [comment]
Looks like you [just did](http://stackoverflow.com/questions/43203967/how-to-checkout-head-to-specified-reference-or-tag-in-libgit2)!  Thanks!  😀
