### ISSUE TITLE
Change checkout options default strategy to safe

### ISSUE THREAD

**Issue by hackhaslam** [libgit2/libgit2#4200]
The default checkout strategy of dry run seems confusing. It's a common theme on stack overflow questions. Would it make sense to change the default to safe? It would break people who rely on the default, but does anybody really use that in practice?

**Comment by ethomson** [comment]
I agree, it's a poor default.  The simplest solution is to simply update `GIT_CHECKOUT_OPTIONS_INIT` to set the checkout strategy to `SAFE`.  Another option is to actually change the values of `DRY_RUN` and `SAFE` so that `SAFE` is `0`, but this will affect any consumer that has to match the values (like LibGit2Sharp).

Do you want to send a PR?

**Comment by hackhaslam** [comment]
Sure, I can submit a PR that changes `GIT_CHECKOUT_OPTIONS_INIT`. My only concern is that somebody may be using the default and it will suddenly change when they update. Do you think that's likely?

**Comment by ethomson** [comment]
I don't think it's likely.  But I also think that this is an improvement, and as far as breaking changes go, it's quite a minimal one.  😛  Let's do make sure to update the `CHANGELOG` appropriately, though.
