### ISSUE TITLE
Release v0.26.0

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#4227]
It's about time for a new release...!

- [x] Make a release candidate
- [x] Plug any final leaks
- [x] Fix any last-minute issues
- [x] Make sure CHANGELOG reflects everything worth discussing
- [x] Update the version in CHANGELOG and the header
- [x] Tag
- [x] Create maint/v0.26
- [ ] Update any bindings

**Comment by pks-t** [comment]
I'd like to have #4228 included, as it changes the worktree API before its initial release.

**Comment by pks-t** [comment]
Another one of interest is #4129, as it fixes possible unintentioned data loss with forced checkouts.

**Comment by pks-t** [comment]
Summarizing the above and some additional tickets. The following PRs should be considered for v0.26.0:

[ ] #4228: adjusts worktree API: should be included to avoid future API breakage
[ ] #4129: fixes data loss with forced checkout: not a regression, but critical in my opinion
[ ] #4243: makes detection of worktrees more strict: this is actually a regression caused by worktree support, even though this fix only applies to subtly broken submodules
[ ] #4239: fixes gitignore inside of subdirectories: not a regression, only nice to have

**Comment by ethomson** [comment]
I have published release candidate 1: https://github.com/libgit2/libgit2/releases/tag/v0.26.0-rc1

Feedback welcome before this becomes v0.26.0.

**Comment by pks-t** [comment]
Looks good to me. Checked CI builds and built/tested it locally without anything interesting popping up. You didn't yet create `maint/v0.26` -- will this be created from `master` after the RC-phase or should `master` already diverge from the release branch?

**Comment by ethomson** [comment]
And an RC2: https://github.com/libgit2/libgit2/releases/tag/v0.26.0-rc2
