### ISSUE TITLE
Problem with libgit2's submodules

### ISSUE THREAD

**Issue by tiennou** [libgit2/libgit2#4274]
### Reproduction steps

- Clone the repo.
- Do the `git submodule update --init --recursive` dance.

### Expected behavior

- Everything is fine.

### Actual behavior

```
fatal: No url found for submodule path 'tests/resources/rebase-submodule/my-submodule' in .gitmodules
```

### Version of libgit2 (release number or SHA1)

2270ca9f8feecf93fe39a02a6fbde90a22c1a665

### Operating system(s) tested

macOS 10.12.*, but I don't think it's that relevant 😉.

**Comment by tiennou** [comment]
Updated : my ⌘↩-fu failed me.

**Comment by ethomson** [comment]
I'm not sure that I understand fully - when you say "clone the repo" you mean "clone _libgit2_ itself"?

What is your goal?  Why are you doing a `git submodule` anything in the libgit2 repository?

We explicitly have test resources that have submodules that _should not_ be initialized - these are our test resources, after all.  In particular, we have (intentionally) broken repositories with (intentionally) broken submodules so that we can test these broken configurations.

If you're (manually) running `git submodule ...` then my encouragement would be for you to not do that.

We have seen some CI type of systems (I forget offhand if it's travis or appveyor) that does a `git clone --recursive` by default.  This is regrettable, and it will lead to the type of situation that you're describing.  Is this what you're running into?  There are fixes for that if that's the case.

Curious about your scenario and how we can work around it.

**Comment by tiennou** [comment]
Sorry for being unclear. Yes, this is while cloning `libgit2` itself, and it is about Travis (which is why I'm reporting it) : https://travis-ci.org/libgit2/objective-git/builds/244659680. I also saw it locally before because I have `fetch.recurseSubmodule = true`.

I'm just concerned about 1) all the automated systems out there where "some" operator decided that `git submodule ...` would Just Work Forever™ and 2) users with that config setting.

**Comment by ethomson** [comment]
Thanks for the additional details - I just wanted to make sure I understood your scenario...

I have to dig a bit deeper, but since we're not actually _configuring_ these test resources as submodules, I think that Git has decided that anything with a `HEAD` file in it must be a submodule!  Urgh.

For LibGit2Sharp, we added this configuration [to .travis.yml](https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/.travis.yml):

```
git:
 submodules: false
```

But I agree that this is disappointing.  I'll see how problematic it would be to do something different here.

Thanks for reporting this - I was happy to ignore this when it was only me who encountered it, but you're right that this is quite obnoxious.

**Comment by tiennou** [comment]
No worries. A possible fix would be to rename the aforementioned test files something like `.gittedmodules` and rename those on the fly when running tests (IIRC like it's done now for the example `.git` directories). I'll try to whip up something if this sound good to you.

**Comment by ethomson** [comment]
Sure!

**Comment by ethomson** [comment]
It looks like the `.gitmodules` name is not the culprit.  That's actually only read when there's [a submodule in the index itself](https://github.com/git/git/blob/05ec6e13aaf33b6a647e1321203a770e697eea9a/builtin/submodule--helper.c).  And it appears that [we accidentally added a submodule proper](https://github.com/libgit2/libgit2/pull/4151/files).

```
$ git ls-files --stage |grep ^160000
160000 efad0b11c47cb2f0220cbd6f5b0f93bb99064b00 0       tests/resources/rebase-submodule/my-submodule
```

I think that we need to remove that (`git rm --cached tests/resources/rebase-submodule/my-submodule`) and then we can leave all the `.gitmodule`s as is.

That works for me - can you verify that works for you as well?

**Comment by tiennou** [comment]
It does indeed, I re-did the PR accordingly. Thanks for the help !

**Comment by slavikus** [comment]
Hey guys, any progress on this PR? It blocks us from updating Objective-Git to v0.26 of libgit2. :(

**Comment by implausible** [comment]
Libgit2 is also a submodule of nodegit, so I'm worried setting a travis command to ignore submodules will tank nodegit, as well.

**Comment by pks-t** [comment]
This issue is being worked on in #4275, so I hope we can fix the issue soon-ish
