### ISSUE TITLE
Missing libgit2.dylib

### ISSUE THREAD

**Issue by tiennou** [libgit2/libgit2#4352]
It seems the recent CMake change had a pretty big impact on Xcode after all, there are no libgit2.dylib created after building the git2 target.

Here's the gist of a run, trying to compile the status example : https://gist.github.com/tiennou/b935b3cb00ce318eb11a13f3553a93fd

Strangely, running `cmake --build .` works, but Xcode/`xcodebuild` will fail to link any dependent targets because of the missing library. Also, the standard Darwin symlinks are there, there's just no `libgit2.0.26.0.dylib`.

And clar runs fine, which is why I missed it (shame on me).

### Reproduction steps
```
mkdir build && cd build
cmake -GXcode -DBUILD_EXAMPLES=ON ..
[build the ALL_BUILD target in Xcode]
```

### Expected behavior

```
$ find . -name *.dylib -print
./Debug/libgit2.0.26.0.dylib
./Debug/libgit2.26.dylib
./Debug/libgit2.dylib
```

### Actual behavior

```
$ find . -name *.dylib -print
./Debug/libgit2.26.dylib
./Debug/libgit2.dylib
```

### Version of libgit2 (release number or SHA1)

212da30dbf18924cb8878348657a048698856be3

### Operating system(s) tested

macOS 10.12.6, Xcode 8.2.1

**Comment by pks-t** [comment]
Huh, interesting. Are you sure you haven't run CMake with different build options in the meantime, especially regarding the option `BUILD_SHARED_LIBS`? I'm asking because it is quite astonishing that the clar tests are running fine without the library being present. In the case where we build a shared library, clar links against it and thus requires it in its linker path to actually run. So it _has_ to be somewhere in this case.

Or, alternatively, you have at some point in time disabled building shared libraries. So the clar links statically against our own static library and you forgot to update the XCode build instructions for CMake. Just guessing a bit to make sense of what you observe here.

So have you tried to completely wipe the Xcode project and regenerate it?

**Comment by ethomson** [comment]
Actually, clar doesn't link against the shared library - it relinks the object files themselves.  It does this so that it doesn't have to worry about what symbols are exported, which allows us to test private functions.

But yes - I agree that wiping the cmake cached stuff and recreating it should work.  On a fresh build, I get:

```
% ls -Flas *dylib
1704 -rwxr-xr-x  1 ethomson  staff  1742052 20 Sep 18:23 libgit2.0.26.0.dylib*
   4 lrwxr-xr-x  1 ethomson  staff       20 20 Sep 18:23 libgit2.26.dylib@ -> libgit2.0.26.0.dylib
   4 lrwxr-xr-x  1 ethomson  staff       16 20 Sep 18:23 libgit2.dylib@ -> libgit2.26.dylib
```

**Comment by ethomson** [comment]
You mention the Xcode generator, but your above paste suggests regular makefiles.  So, you're running `cmake -GXcode`?

**Comment by tiennou** [comment]
Sorry I forgot the -G flag in the initial report. The script included in the gist is right, and this only affects the Xcode generator (running Unix Makefiles results in the dylib being correct).

That said, I've been able to manually fix the Xcode target with the following kludges :
- Xcode doesn't link an empty dynamic library against a static one. You *need* at least one C file for the linking step to appear. I've confirmed that against a blank project with only 2 targets.
- Once you get the linking to happen, the `git2` target is missing an `-L$SYMROOT` linker flag, so the linker can `-lgit2internal`. (SYMROOT is Xcode parlance for "Build Products Path".

**Comment by pks-t** [comment]
Seeing the `-lgit2internal` step, I do hope that this here will already get fixed by #4339. This causes us to never explicitly link against `git2internal` but to always use object libraries here.  Can you please check if the issue still persists with those commits?

**Comment by tiennou** [comment]
Running the test script on top of #4339, the linking failures go away after adding a "Compile source" step with some empty C file. IOW the first issue is still present.

I guess this means we need to special-case the Xcode generator so there's at least one of those, even if it's just a build artifact (like `features.h`).

**Comment by pks-t** [comment]
Strange. It's unfortunate we don't have a single CI job for the Xcode generator. We should probably add one, but seeing that the macOS jobs are already the longest running jobs I'm hesitant to do so. Next week I've got a lot of time for libgit2, so I'll hopefully come around to that issue then.

**Comment by tiennou** [comment]
Sorry, I've just encountered that same issue while working on my merge example PR. Xcode *really* needs something to compile, else it will just not link anything, and the features.h file doesn't cut it — 
it actually doesn't appear anywhere in the target's Build Phases. I'll try to see if I can coerce CMake into generating a dummy.c file for Xcode enjoyment…
