### ISSUE TITLE
Improve performance for git_tag_foreach

### ISSUE THREAD

**Issue by godfat** [libgit2/libgit2#4360]
### Reproduction steps

We have a repository which had 29435 empty directories in `refs/heads/*`, and listing tags was extremely slow. After trying to `strace` it, we figured that even if we're trying to list tags, it's also iterating through other refs, which seems not needed.

### Expected behavior

Just traverse through `refs/tags/*`? I see that we could potentially use `git_reference_foreach_glob` and pass the glob as `refs/tags/**/*` or something like that to limit where it's iterating through.

### Actual behavior

It traverses through all refs via `git_reference_foreach_name` with `tags_cb`.

### Version of libgit2 (release number or SHA1)

v0.26.0

### Operating system(s) tested

Linux x86_64

**Comment by ethomson** [comment]
This is because we have an abstract reference backend.  To accomplish this, we would need to teach the reference backends the difference between branches and tags, which is a major refactoring and accomplishes very little, except in this one particular case.

It's unlikely that this is an avenue that we would explore, especially since it does little to fix the problems in the `git_branch` functions that are _also_ impacted by your problem.
