### ISSUE TITLE
Configuration functions not case-sensitive

### ISSUE THREAD

**Issue by omus** [libgit2/libgit2#4390]
I've noticed that functions like `git_config_set_string` write variable names in lowercase and `git_config_iterator_glob_new` don't work when you provide non-lowercase input. I would expect that functions which write config variables to retain the provided casing.

An example of a git configuration variable that uses uppercase letters is [useHttpPath](https://git-scm.com/docs/gitcredentials#gitcredentials-useHttpPath)

Git2 version v0.26.0 (15e1193)

**Comment by carlosmn** [comment]
There's a bunch of different things here, but they look to stem out of a misunderstanding of how Git configuration keys behave.

We should be case-preserving. We likely simply write out of the normalised representation instead of the input string, which would indeed be a bug, though a cosmetic one.

Configuration options like `credential.useHttpPath` are case *in*sensitive in Git configuration.

I don't recall how much of the regexp behaviour was done to explicitly copy git's actual behaviour, but the behaviour of `git config --get-regexp` is also case-sensitive. In particular, its documentation specifies that

>Regular expression matching is currently case-sensitive and done against a canonicalized version of the key in which section and variable names are lowercased, but subsection names are not.

which is about the only workable solution, as Git configuration keys are in part case-sensitive and in part case-insensitive. We also match against the normalised version of the key. The correct thing here if you want a glob to match the url-specific option, is to spell both the `credential` and `usehttppath` in lowercase.

**Comment by pks-t** [comment]
With the writing part being fixed via #4392, I'd consider this issue closed as it is based on a misunderstanding. @omus: feel free to expand on your issue if you disagree, otherwise please close this issue.

**Comment by omus** [comment]
> I've noticed that functions like `git_config_set_string` write variable names in lowercase

#4392 does address this part of the issue.

> `git_config_iterator_glob_new` doesn't work when you provide non-lowercase input

This part of the issue should be addressed by #4396. I'll close this issue once that PR is merged.

**Comment by pks-t** [comment]
Seems fair. I've overlooked issue #4396
