### ISSUE TITLE
Filesystem git clone of large repo can be very slow on OSX

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#4464]
This issue was originally reported as https://github.com/rust-lang/cargo/issues/4604, winnowed down with https://github.com/alexcrichton/git2-rs/issues/280, and now I'm coming over here to see if we can track it further! 

The behavior that we're seeing is that clones of a repo from the filesystem can take a huge amount of time when `git` the command line tool comparably takes a much shorter amount of time. In my own testing I'm also seeing that OSX takes an even larger amont of time than Linux (although I'm not sure why).

A small [reproduction script](https://gist.github.com/alexcrichton/fdec5ccfcccd3b1e3d01873e717f68d6) includes a program which basically just clones the [servo](https://github.com/servo/servo) repository from one location on disk to another. On Linux this takes ~2 minutes on my machine (the `git` tool takes 2s for `git clone ./servo ./servo2`). On OSX it's currently running but taking quite awhile. It's progressing at about the rate of 100 received objects per second, which out of 482k objects is probably going to take quite awhile!

So I think this is sort of a dual issue/question. Are we doing something wrong when cloning on the filesystem? Are there other options we should use to speed this up? Or is this a performance bug in libgit2?

Some rough profiling on OSX shows that about 100% of the time here is spent in `mmap` and `munmap` (at least while I had Instruments.app attached that's where it all was), mostly called from `git_mwindow_free_all_locked`. I guess mmap is slower on OSX than Linux?

**Comment by carlosmn** [comment]
You're performing a fetch rather than letting us know it's a clone, so libgit2 is creating the packfile. Our pack-objects code is missing some of the optimisations which exist in git which would let us avoid inflating and deflating many of the objects. Thus it looks like a duplicate of #2836 .

If you were to use the cloning function, you could let us know to activate local clone optimisation, via `git_clone_options`'s `local` field. That would tell us to hardlink the object db instead of performing a fetch.

`mmap` is indeed somewhat slower on macOS than Linux, but it shouldn't make that big a difference overall (as our time _should_ be spent in inflating and deflating). If you're seeing the majority of calls be about mapping and unmapping, it could be due to the source repository having a large amount of small packfiles.

**Comment by alexcrichton** [comment]
Aha indeed this does look like a dupe, sorry for the noise!

Also thanks for the info on clones/links, I'll look to see if we can refactor and use that instead. Thanks for the info!
