### ISSUE TITLE
libgit2 fails to read config files with empty lines with CRLF ending

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#4517]
### Reproduction steps

1. Have a `.gitconfig` file with CRLF line endings and at least one empty line (e.g. at the end)

### Expected behavior

Config file is parsed correctly (as Git for Windows does or older libgit2 versions such as e0568621535869451c91e915d28a69ac7c84b8b7).

### Actual behavior

libgit2 fails with the error: `failed to parse config file: Invalid configuration key (in C:/Users/Username/.gitconfig:5, column 0)`. (whereas line 5 is an empty line)

### Version of libgit2 (release number or SHA1)

f7225946edeae35f48e3d402e2e0c94ea07f9666

### Operating system(s) tested

Windows 7 x64

### Additional notes ###

This affects all files which are parsed as config files, such as `.gitmodules` (however, in that case `git_submodule_foreach` does not return any error, but fails silently and lists no submodules at all, the callback is not called once; this is maybe another bug in libgit2)...

Maybe this is related to compiler: I'm using MS VisualStudio 2017 15.5.5

Cross-ref: https://gitlab.com/tortoisegit/tortoisegit/issues/3153

**Comment by csware** [comment]
This is a regression e0568621535869451c91e915d28a69ac7c84b8b7 worked just fine.

**Comment by tiennou** [comment]
The issue is that I understand [this](https://github.com/libgit2/libgit2/blob/f7225946edeae35f48e3d402e2e0c94ea07f9666/src/config_parse.c?utf8=%E2%9C%93#L478) should be advancing over "whitespace", but it doesn't actually : the first part of the `&&` does, the second part fails, thus we never `continue` over the "blank" line.

@pks-t I think the fix is easy, just want to be sure I'm not misunderstanding the purpose of those lines…

Test case :
```
void test_config_read__read_crlf(void) {
	git_config *cfg;
	git_buf path = GIT_BUF_INIT;

	cl_git_mkfile("./config-crlf", "\r\n");//\r\n");
//				  "[test]\r\n path = file.txt\r\n[section]\r\n\r\ndata = lol\r\n");
	cl_git_pass(git_config_open_ondisk(&cfg, "./config-crlf"));

	cl_git_pass(git_config_get_path(&path, cfg, "test.path"));
	cl_assert_equal_s("file.txt", path.ptr);

	git_buf_free(&path);
	git_config_free(cfg);
}
```

**Comment by csware** [comment]
The regression seems to be introduced between 88450c1c6043b34c4433c475dcfd4928439a4810 (working) and 15f8d9a232097c63c87d8bb2b959e72bb7c1c798 (not working any more).

**Comment by pks-t** [comment]
Thanks for the report. The culprit will definitly be #4308.

@tiennou: I think this is a bit more complicated than you think, though I haven't yet found the root issue. The `git_parse_peek(SKIP_WHITESPACE) < 0 && git_parse_peek(0)` line is correct though, even though what it does is quite intricate and should be documented. Its intent is to either get the first non-whitespace character of the line in case there is one or, otherwise, the first whitespace character.

I'll investigate.

**Comment by pks-t** [comment]
Okay, the issue is actually kind of trivial. See #4308 for a fix and please let me know if that fixes your issue.

**Comment by csware** [comment]
The PR fies the issue.

**Comment by csware** [comment]
Works, thanks!

**Comment by tiennou** [comment]
I'm completely confused over those `parse_peek` calls, because I don't understand what they did since you actually have to handle those whitespace characters in the switch below (and you're calling `on_comment` in case of whitespace then ?).

Eg. here's the pseudo-code I'm basing myself on :
```
  err = git_parse_peek(&c, SKIP_WS);
  if (err != 0) continue; // We hit EOL, skip that line

  switch (c) // Over meaningful characters
```
and I don't see what the 2nd peek calls gives us (apart from failing those "\r"/"\n" check and having to redo them in the switch instead of `continue`-ing).

In all, I might be missing something from "the spec", so I'm not getting in the way. I'm just surprised that a line-by-line parser has confused me 😉.

**Comment by pks-t** [comment]
"Meaningful character" is a bit tricky in this context, thoug. You need to know that "whitespace" and "comment" characters are meaningful _if and only if_ there is no other character in that line. This is required as the parser is actually also used to write the configuration file -- if we just skipped whitespace in all cases, we wouldn't be able to restore the original file, because we'd drop the whitespace.

That is why there are two calls - first `git_parse_peek(&c, SKIP_WS)` to get any non-whitespace character. But if there is no non-whitespace character in the current line, we have to get the first whitespace character, which is being done by `git_parse_peek(&c, 0)`. So we actually _do_ want to handle whitespace characters in the switch, as they can be meaningful in some situations.

Its a bit weird, I agree.

**Comment by tiennou** [comment]
Thanks, now that makes perfect sense (I had a hunch writing might be involved). I've proposed an alternative comment for this your PR describing this "why". That only leaves my "does this means `on_comment` is actually `on_comment_or_blank_line` ?", but I can live with that now that it's documented.
