### ISSUE TITLE
Cylance throwing virus alert

### ISSUE THREAD

**Issue by avineshwar** [libgit2/libgit2#4589]
### Operating System
- MacOS (latest)

### File location
- /usr/local/Cellar/libgit2/0.26.3/share/libgit2/examples/cgit2

### SHA256
- a9bdf1dd476be384df3bd571d57afaeaaa1ae5dfefb7575e07672e4d60dc3101

### MD5
- 2F0D9029195978166256BF555D3154C0

**Comment by pks-t** [comment]
Thanks for your report.

First things first: we don't intentionally put any virus into our code base. Due to that, the only possibility would be for Homebrew to put a virus into the distributed binaries, in which case you should raise an issue at their [project](https://github.com/Homebrew). I'd bet though that this is simply a false positive raised by the virus scanner.

Anyway, I'm closing this issue. This is really only a concern to the distributor of libgit2, as the libgit2 project itself never distributes binaries.
