### ISSUE TITLE
Unable to locate diff.h overview and terminology in documentation

### ISSUE THREAD

**Issue by micjabbour** [libgit2/libgit2#4634]
### Reproduction steps
I have been searching for what is meant exactly by a `git_diff`, a `git_diff_delta` and a `git_patch` for hours, until I found these helpful documentation comments in [`diff.h`](https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L20-L61)
### Expected behavior
These comments should be exported by docurium to the documentation somewhere (they are really useful for newcomers like me).
### Actual behavior
I couldn't find any of these paragraphs while browsing the [docs](https://libgit2.github.com/libgit2/#HEAD). This is especially annoying if one is using some libgit2 bindings library (e.g. Rugged) and isn't really prepared for browsing through tons of C code until he reaches these comments.
### Version of libgit2 (release number or SHA1)
709e099c2173b0f9939b6d3b4ff9076821a59acd
### Operating system(s) tested
N/A

**Comment by ethomson** [comment]
Thanks, @micjabbour, this is very good feedback.  Sorry that it took you so long to find the information you were looking for, but I appreciate you taking the time to log an issue about this.

**Comment by tiennou** [comment]
This is likely to require a whole bunch of changes to docurium, but maybe those kind of "group comments" could be added at the top of their group section (ie. [here](https://libgit2.github.com/libgit2/#HEAD/group/diff)).

"Whole bunch" meaning I would guess clang doesn't actually see it because it's not "attached to any relevant C AST thingie".

**Comment by pks-t** [comment]
Closed via #4788
