### ISSUE TITLE
git_remote_create without insteadof rewrite rules

### ISSUE THREAD

**Issue by vors** [libgit2/libgit2#4658]
> You are opening a _bug report_ against the libgit2 project.  If you have a
> question about an API or usage, please ask on StackOverflow:
> http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
> reproduction steps (below) and delete this introductory paragraph.  Thanks!

### Prelude
Apoligies in advance for openning an issue that could be viewed more like an API question and not a bug report. I [asked on stackoverflow](https://stackoverflow.com/questions/50548680/libgit2-git-remote-create-without-apply-insteadof) as suggested, but didn't get any replies.
It's unclear to me that this is even possible to achive with the current public APIs at all. Hence, I think it's appropriate to open an issue in this repo.

### Question

This is somewhat similar to #2923 .

I'd like to use an equivalent of [`git_remote_create_anonymous`](https://github.com/libgit2/libgit2/blob/0eca42304a10c9ad6170a38a440dfab8e354d38d/include/git2/remote.h#L73) function, but without applying `insteadof` url substitutions. This is similar to [`git_remote_create_detached`](https://github.com/libgit2/libgit2/blob/0eca42304a10c9ad6170a38a440dfab8e354d38d/include/git2/remote.h#L92) which explicitly says that it doesn't apply `insteadof` substitues.

I could not find an equivalent API or combination of APIs that would get me a fetchable repo without the global config substitutes applied.

Am I missing something? If not, would it be reasonable to add such API?

### Motivation
The use-case of it is to bypass any users global `~/.gitconfig` settings.
For example, it's common to have

```
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```

[CircleCI uses](https://github.com/rust-lang/cargo/issues/2429#issuecomment-191370340) this approach.

That causes somewhat unpredictable behavior for tools that use github repos for their online indexes, like [cargo](https://github.com/rust-lang/cargo). Users find workaround for it, but it would be really nice to put more control in the hands of tools authors, so they can bypass the rewrite rules. libgit2 already does it for `git ls-remote` functionality with detached repos.

**Comment by tiennou** [comment]
I'm not really against adding API for that, I'm just wondering about this (after having written the code 🤷‍♂️) :

If your ultimate goal is to ignore the user's `.gitconfig`, what prevents you from manually building a `git_config` instance and switching the repository to that instead of using the default ? See [git_repository_set_config][set_conf] and [git_config_open_ondisk][conf_open].

[set_conf]: https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_set_config
[conf_open]: https://libgit2.github.com/libgit2/#HEAD/group/config/git_config_open_ondisk

AFAIU, your repoes are not really user-accessible ?

On the subject of API changes, this can bring down the 4 `git_remote_create*` functions we have down to 2. If this is deemed a worthy goal, I can PR the code I have.

**Comment by pks-t** [comment]
I think it's sensible to provide a way of creating remotes without paying attention to insteadof rules.

The current design of our creation functions is a bit unfortunate, as none of these functions is able to accept an `opts` structure. But changing existing public API to fix that is a no-go, unfortunately, so that we make sure to not break our users. One way to fix this situation is to just provide a new set of functions `git_remote_create_*_with_opts`, which would allow us to do future changes without breaking the API. Yeah, it is ugly, but I don't see a better way to do this while keeping our API.

**Comment by vors** [comment]
Yes, making it extensible for the future is a great idea. @tiennou just used a name `git_remote_create_ext` in the #4667 , which I think a consistent C name for such cases (I'm very far from C expert, don't quote me on it).

**Comment by vors** [comment]
This is merged now!

**Comment by pks-t** [comment]
On Tue, Nov 13, 2018 at 08:33:02AM -0800, Sergei Vorobev wrote:
> This is merged now!

Thanks for keeping track and opening the feature request! :)
