### ISSUE TITLE
Regression: Refdb glob

### ISSUE THREAD

**Issue by jacquesg** [libgit2/libgit2#4664]
### Reproduction steps
Call ```git_revwalk_hide_glob``` with a ref that doesn't exist, something like ```refs/heads/notmaster```

### Expected behavior
No error.

### Actual behavior
Errors out with an error similar to the following:

`failed to open directory '/Users/jacquesg/github/p5-Git-Raw/.build/FmeM1xl2sg/t/test_repo/.git//refs/heads/notmaster/': No such file or directory`

### Version of libgit2 (release number or SHA1)
Introduced by 20a2b02d9a1bcb4825ec49605146223c565dcacf

### Operating system(s) tested
Linux

**Comment by neithernut** [comment]
Looks like I introduced this bug. I'll have a closer look in a few hours.

**Comment by neithernut** [comment]
Well, I think I know what's causing the regression:

Within `iter_load_loose_paths()`, we iterate over all references within the `refs/` directory, which essentially means listing directories and,in some cases, recursing into them. Previously, all of those references were simply matched against the glob.

The changes I introduced provide a shortcut: in some cases, we can already tell that a glob will only match references within some sub-directory and may as well start in this directory. Further down, this leads to listing of the directory. This will obviously not work if the directory does not exist.

The question is how this regression is fixed best: we could simply hide the failure of opening the directory, but this would also hide other (potential) errors. We could also check whether the directory exists and bail out early, since we won't iterate over any references anyway. The latter option makes more sense to me.

I'll be off for a few hours now (sleep). If I no one came up with a better idea or any objections, I'll prepare a fix then. We also better include a test for this regression.

Honestly, it's a bit embarrassing that this didn't occur to me earlier. I guess I was also "lucky" enough not to have a typo in my original test-cases for measuring the enhancement in performance.
