### ISSUE TITLE
Using Meson instead of CMake

### ISSUE THREAD

**Issue by hackertron** [libgit2/libgit2#4707]
Hey can we try/use meson build system instead of CMake.  Meson is much more easier and faster than CMake.

**Comment by ethomson** [comment]
I’m not particularly in love with cmake, in fact I think it’s pretty obnoxious.  However I’ve not seen a compelling replacement that can handle all our platforms and configurations.  I’m happy to look at a PR that introduces a new build system but I don’t think that any of the core contributors are super excited about tackling this at the moment.

**Comment by hackertron** [comment]
Then i can try for it.

**Comment by tiennou** [comment]
Let's say that as long as you're not proposing autotools, I'm 👍 🤣.

It's just that I believe CMake has the folllowing benefits/requirements :
- it's pretty obnoxious in terms of availability. This directly impacts things like CI, for which having to install meson might not make it faster.
- it has generators for various IDEs (Xcode/MSVC), which I would (personally) hard-require. Also, that might make the "faster" point moot in those cases (since the IDE's "speed" becomes the bottleneck, ie. a CMake "Unix Makefile" build is noticeably faster than an "Xcode" one).

**Comment by ethomson** [comment]
> it has generators for various IDEs (Xcode/MSVC)

Yes, MSVC solution generation is a hard requirement.

**Comment by hackertron** [comment]
Actually meson has provided something called meson introspect with which it can be used with almost any IDE and as for MSVC there is already meson plugin support for it .https://github.com/mesonbuild/meson/blob/master/docs/markdown/Using-with-Visual-Studio.md

**Comment by ethomson** [comment]
Haven't really seen any movement on this - I don't think that anybody on the core team wants to pursue this right now, but if somebody else wants to tackle it, I'd review a PR.

**Comment by ao2** [comment]
FWIW one advantage of using meson would be that other meson projects depending on libgit2 could easily import libgit2 as a *meson subproject* and be independent from the version provided by the distribution.

I recently had the need to get a newer libgit2 to tests something in gitg https://gitlab.gnome.org/GNOME/gitg

**Comment by ao2** [comment]
FWIW, one advantage of using meson would be that other meson projects depending on libgit2 could easily import libgit2 as a *meson subproject* and be independent from the version provided by the distribution, at least during the development cycle.

Just as an example, I plan to use this *meson subproject* concept to import libgit2-glib (https://gitlab.gnome.org/GNOME/libgit2-glib) in gitg (https://gitlab.gnome.org/GNOME/gitg).
