### ISSUE TITLE
iconv support disabled when compiling with musl

### ISSUE THREAD

**Issue by tpimh** [libgit2/libgit2#4775]
### Reproduction steps
On a musl based distro (I used Alpine) obtain libgit2 source and configure with cmake.

### Expected behavior
Configure output should have "iconv, iconv encoding conversion support" as enabled feature (musl libc provides `iconv.h`)

### Actual behavior
"iconv, iconv encoding conversion support" is actually listed as disabled feature

### Version of libgit2 (release number or SHA1)
0.27.4 and older versions

### Operating system(s) tested
Alpine Linux x86_64

**Comment by pks-t** [comment]
I've never really bothered to get iconv set up on my system, which is a Gentoo with musl libc. I've created #4777 to fix this issue, so that we now also detect iconv support on systems where it is directly implemented via libc.

As I note in the PR, some of our tests will fail as musl libc's iconv support is a bit more bare bones. I honestly don't care enough right now to fix them, and I definitely don't want to disable them. A solution would be to dynamically compute whether the iconv library in use is able to perform certain transformations -- if it is not, we could just skip some of our tests which require them.

Please have a look whether it fixes your issue. Note that you have to add "-DUSE_ICONV=ON", as we only default to using it on macOS.

**Comment by tpimh** [comment]
Thank you, it worked. This issue can be closed after #4777 is merged.

**Comment by pks-t** [comment]
Thanks for confirming!
