### ISSUE TITLE
Update minimum CMake version

### ISSUE THREAD

**Issue by slurps-mad-rips** [libgit2/libgit2#4795]
Hello,

libgit2 currently targets CMake 2.8.11. I would like to update this (along with the build files themselves) to a post-3.0 release. While I understand that some people have asked for a move to meson like in #4707, some of us are still stuck in the CMake space. I'm more than willing to put in the work to do this myself, but wanted to ask if this kind of change would be accepted, as I'd rather not waste libgit2's, as well as my own, time. I've also filed a request to do the same for libssh2/libssh2#265, and would do these updates in tandem if possible. (Additionally, as I would be writing these changes myself, it would also resolve #4649)

**Comment by ethomson** [comment]
Sorry, you haven't explained why this would be useful to you?  What's wrong with 2.8.11 compatibility that you want something newer?

**Comment by slurps-mad-rips** [comment]
Well, as I said, it would solve #4649, which would let a parent project pull both libgit2 and libssh2 in as dependencies without requiring that they be built, I'd also be able to set the targets such that `include_directories` for dependent targets rely on transitive linking automatically (effectively allowing people with modern CMake to simply do `target_link_libraries(<name> PUBLIC git2)` and all includes, flags, etc. are automatically added), CMake 3.0 also added `PLATFORM_ID` generator expressions so fewer if's and list construction is needed when doing platform specific linking of dependencies.

Also, I'd be able to more easily generate a `libgit2-config.cmake` so that windows users aren't trapped trying to find it by using pkg-config (so a `find_package(libgit2)` would work, and this could then let namespaced exported targets automatically be handled). 

Lastly, I'd be able to more easily handle 'future' proof CMake implementation features when working on libgit2. At the moment, the `src/CMakeLists.txt` file uses globs, which means if files are added or removed, one has to remember to 'touch' the `CMakeLists.txt` file. CMake 3.12 and newer support a special `CONFIGURE_DEPENDS` option that can be added conditionally to each glob command and in those cases developers of libgit2 on modern CMake installations wouldn't have to worry about touch a CMakeLists.txt file manually. (It is also quite fast, even for a project of libgit2's size). With this "future proofing" (and assuming libssh2 takes my changes as well), I could also support optionally pulling in libssh2 as a dependency via `FetchContent`, which means I don't have to spend time installing libssh2 as a dependency, and can keep my build contained if I (or others) so desire.

I hope that was explained well enough, please let me know if you want me to expand on this further with code examples, as I more than understand why someone would not want to get deeper into CMake.

**Comment by pks-t** [comment]
While I agree that upgrading CMake to a newer version, this is not something we can do willy-nilly. Unfortunately, certain distributions exist that are widely used and supported which do not have newish versions available. The most common offenders that come to mind are RHEL/CentOS, where CentOS 6 ships CMake 2.8.12.2 by default.

Agreed, we already say that some distros come with a CMake that is too old, like Debian Stable and CentOS 5. But we only raised the version roughly a year ago in cf9f34521 (cmake: bump minimum version to 2.8.11, 2017-09-06), I don't know if we should break another set of distros. Also, from the commit message:

    - CentOS 5: 2.6.2
    - CentOS 6: 2.8.12.2
    - Debian 7: 2.8.11
    - Fedora 23: 3.3.2
    - OpenSUSE 13.2: 3.0.2
    - Ubuntu Precise: 2.8.7
    - Ubuntu Trusty: 2.8.12

So unfortunately, we are left in the sad state we are in right now.

That being said, I wouldn't be opposed to adding more version checks into the build instructions. We already have some locations where we build differently based on what version we are currently on. src/CMakeLists.txt comes to mind, where we use `TARGET_INCLUDE_DIRECTORIES` instead of `INCLUDE_DIRECTORIES` if we're on v2.8.12 or newer, or our feature summary code at the bottom of CMakeLists.txt. So there's precedent already and we can add more of that in cases where it's maintainable and has obvious benefits.

I'm closing the issue due to this rationale. As said, please feel free to create pull requests that replaces certain features with more modern ones based on the CMake version that is being used.

**Comment by slurps-mad-rips** [comment]
@pks-t I know its been a little over a year, but has anything changed regarding minimum OS support? I didn't want to open a new issue, but also couldn't find any definitive list. 

I've been going around and trying to bump folks to at least CMake 3.4 to help improve the general C and C++ ecosystem, and 3.4 is a pretty good default. I know CentOS 6 might be an issue, but they do have an SCL available with a newer CMake available. (One can also theoretically grab the `.sh` installer for 3.4 off of GitHub directly from KitWare). I understand wanting to keep supporting older operating systems, but given they aren't receiving security updates, would it be a burden to request users to install a more recent CMake version? I know Kitware has gone to great lengths to ensure ABI stability with CMake (to a point that it is arguably detrimental to their devs working on the project)

**Comment by pks-t** [comment]
Thanks for pinging. I've created #5260 which upgrades our minimum CMake version to v3.5.1.

**Comment by slurps-mad-rips** [comment]
@pks-t happy to do so! I'm basically going around and trying to get folks CMake files all nice and clean. The bump to 3.5 means I can start improving libgit2's stuff (Though some coordination with libssh2 is needed. Perhaps I should ping them as well 😅)
