### ISSUE TITLE
Prefix CMake options with "LIBGIT2_"

### ISSUE THREAD

**Issue by julianbreiteneicher** [libgit2/libgit2#4796]
Hi,

I would like to suggest to prefix all CMake options with the string "LIBGIT2_". I think this would have several advantages:

- Tools such as cmake-gui group options with a common prefix, so all libgit options would be nicely grouped together.
- If the parent project (that uses libgit2) uses options with the same name then there is no easy way to set them separately. For example, in our use case we want to set BUILD_SHARED_LIBS to OFF for libgit, but for the root project we want to set it to ON. This would be easier if they were separate options.

**Comment by ethomson** [comment]
This is an interesting request.  You have a project that builds shared libraries, so you (and libgit2) both have an option named `BUILD_SHARED_LIBS`.

Do you have an outline of how this would work?  I ask because `BUILD_SHARED_LIBS` is the standard convention that cmake uses - we don't have some complicated `IF (BUILD_SHARED_LIBS)` mechanisms in our `CMakeLists.txt`, we just let cmake do its magic when that option is set.

Are you proposing some mechanism whereby we detect `LIBGIT2_BUILD_SHARED_LIBS` and then reset `BUILD_SHARED_LIBS` based on that?  This seems awkward and non-standard.

Can you not just `SET` the options you want before `ADD_SUBDIRECTORY`?  ie:

    SET(BUILD_SHARED_LIBS OFF)
    ADD_SUBDIRECTORY(libgit2)

**Comment by julianbreiteneicher** [comment]
Hmm, I think you are right. For `BUILD_SHARED_LIBS` this does seem hacky. I assumed that there was some kind of `IF (BUILD_SHARED_LIBS)`, but after reading about the option it seems that the option is indeed intended to be global for all projects.

As a workaround, we do something like that, yes. We store the content of `BUILD_SHARED_LIBS` in a backup variable, set it to `OFF` for libgit2 and restore it afterwards.

But I still think that for the other options (`THREADSAFE`, `USE_SSH` and so on) it would make sense to have them in their own "namespace".
It would avoid name clashes with other projects and the user could easily recognize that these
options belong to libgit2, which is very useful when multiple libraries are used in a project.

**Comment by pks-t** [comment]
In hindsight it might've made sense. If you ask me, our set of build options is a huge mess anyway, which is owed to the fact that they were organically grown without us having clear guidelines.

But on the other hand, I'm a bit hesitant to do this change. While it might seem a bit far-fetched, you can essentially see the build options as kind of an interface to downstream distributors and packagers. Renaming all our options would mean that we break this interface for them, which will result in all packagers having to change how they build libgit2. And we've already got our share of hate because we were frequently changing interfaces between releases, I personally want to improve and behave better :P

So, yeah. I think to improve the situation we should focus on implementing a policy/guideline for how options should look like and, going forward, apply them to all new options. When touching existing options, we should also adapt them to that new style. But I don't know whether we should just plain convert all the existing ones to use the new style, as that would induce some pain for packagers. The downside is obviously that we're left in a half-state between old-and-awful and new-and-shiny options.

(Please take the above as proposals/thoughts, not as something set into stone)

**Comment by pks-t** [comment]
Yeah, I think I tend to agree. A prerequisite would be to error out though in case where the user has specified any build options that do not exist anymore, and I honestly don't know whether CMake does that by default. I'm not sure about BUILD_SHARED_LIBS, though, as that is a switch provided by CMake itself.

Patches welcome, but I think I might also tackle this in the mid-term future. Probably not for the next release, though

**Comment by ethomson** [comment]
Closing as stale. I’d be interested in understanding how we can handle this case better but I don’t think prefixing everything is necessarily the best solution.
