### ISSUE TITLE
Invalid Content-Type when cloning from Glitch

### ISSUE THREAD

**Issue by palmin** [libgit2/libgit2#4844]
Cloning repositories with the plain http transport fails against ``https://api.glitch.com`` where commandline Git can clone without problems.

The specific problem seems to be that libgit2 at one [point](https://github.com/libgit2/libgit2/blob/475db39bb4c44a2221f340c66c227f555e478d10/src/transports/http.c#L441-L460) expects the "application/x-git-upload-pack-result" content-type but receives "application/x-git-upload-pack-advertisement".

I would like to do the work to track this down and turn this into a pull request, but right now I'm not even 100% sure that libgit2 is in the wrong. Some kind of guidance on things to try out or to research would be much appreciated. 

### Reproduction steps

````
git_repository *repo = NULL;
int errcode;
git_libgit2_init();
errcode = git_clone(&repo, "https://api.glitch.com/htmltidy/git", "htmltidy", NULL);
fprintf(stderr, "errcode=%d, message = %s\n", errcode, giterr_last()->message);
````    

### Expected behavior

Cloning should complete without error.

Commandline Git does the following:

````
$ clone -vv https://api.glitch.com/htmltidy/git
Cloning into 'git'...
Server supports multi_ack_detailed
Server supports no-done
Server supports side-band-64k
Server supports ofs-delta
Server version is git/2.7.4
want f0558da3e2fc579ebe4e7f8e275c907becc71fbc (refs/heads/master)
done
POST git-upload-pack (157 bytes)
remote: Counting objects: 147, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 147 (delta 69), reused 124 (delta 55)
Receiving objects: 100% (147/147), 19.73 KiB | 841.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
````
### Actual behavior

Cloning fails with ``errcode=-1`` and ``message=invalid Content-Type: application/x-git-upload-pack-advertisement``

### Version of libgit2 (release number or SHA1)

0c973356f2ee49e4f22e93a4155cf0c7c32cf9d7

### Operating system(s) tested

iOS 12.0 and macOS 10.14

**Comment by carlosmn** [comment]
It looks like both git and glitch mostly ignore the HTTP portion whereas the libgit2 code was written by someone who'll gladly scream "semantics!" at you.

An except from `GIT_CURL_VERBOSE=1 git clone https://api.glitch.com/htmltidy/git /tmp/foo` which tells git to tell libcurl to output debugging information.

```
> GET /htmltidy/git/info/refs?service=git-upload-pack HTTP/1.1
Host: api.glitch.com
User-Agent: git/2.19.0
Accept: */*
Accept-Encoding: deflate, gzip
Accept-Language: en-US, *;q=0.9
Pragma: no-cache

< HTTP/1.1 200 OK
< Date: Wed, 10 Oct 2018 11:37:54 GMT
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
<
```

Up to here everything is fine. We've asked for an advertisement and we get that `Content-Type`. In the next request however, we no longer want an advertisement, but the packfile (the negotiation can go on for a couple of requests, but in this case it's a clone so the second requests asks to send the data).

```
Host: api.glitch.com
User-Agent: git/2.19.0
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Length: 141

* upload completely sent off: 141 out of 141 bytes
< HTTP/1.1 200 OK
< Date: Wed, 10 Oct 2018 11:37:54 GMT
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
<
```

and here is where glitch isn't taking the `Accept` header field into consideration, is returning the wrong `Content-Type` for the response it's delivering and where libgit2 errors out because it cares, whereas git just goes on its merry way.

The `Accept` header field here is `application/x-git-upload-pack-result` which is what you get when the server sends the packfile. However, glitch's implementation is sending `Content-Type: application/x-git-upload-pack-advertisement` which is neither what we asked for nor what it's delivering.

**Comment by palmin** [comment]
Thank you. This is super helpful.

Would it be a good idea for me to take this up with Glitch instead and close this issue?

**Comment by carlosmn** [comment]
I would say so yeah, this is on glitch's software to adjust the content-type.

**Comment by cori** [comment]
To be explicit for future visitors, the issue that @palmin linked to above is the _source_ of the apparent problem in Glitch (full disclosure; I work for Glitch) since we rely on git-http-backend to serve our repos over http.

**Comment by rashkov** [comment]
Is there a workaround for this?

**Comment by palmin** [comment]
@rashkov It isn't pretty but I have patched away this content-type check as I prefer the behaviour to match command line git.
https://github.com/palmin/libgit2/commit/da50e9aa050fa20d5038967868cbbfa1d50c9119

**Comment by ethomson** [comment]
We should fix this.  If git doesn't enforce this, neither should we.

**Comment by ethomson** [comment]
@palmin do you happen to know if they do _any_ checking on the content-type?  (ie, does it work because `application/x-git-upload-pack-advertisement` is in a list of allowed content-types?  Or is it completely ignored?)

**Comment by palmin** [comment]
@ethomson I have had a look around http.c and related files in git/git and I didn't see any checks but I don't know the code well enough to answer with confidence.
