### ISSUE TITLE
libgit2 with compiled openssl 1.1.1

### ISSUE THREAD

**Issue by yar05** [libgit2/libgit2#4890]
### Reproduction steps
Centos 6 : Compile openssl 1.1.1 on bare centos docker image without openssl
Compile libssh2
Compile libgit2
Pip install pygit2 to virtualenv
Pygit2 Git clone from any https source returns : user cancelled certificate check

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pygit2/lib/python2.7/site-packages/pygit2/__init__.py", line 263, in clone_repository
    check_error(err)
  File "/tmp/pygit2/lib/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: user cancelled certificate check`

### Expected behavior
Pygit2 should clone the repo 

### Actual behavior
Returns only : user cancelled certificate check

### Version of libgit2 (release number or SHA1)
0.27

### Operating system(s) tested
centos 7
https://gist.github.com/yar05/923749a73b59e9204bc791621e4ed205  < Dockerfile

**Comment by ethomson** [comment]
You have a self-signed certificate (or a certificate that is otherwise not trusted by your configuration).  If you want to accept a self-signed certificate, then you need to hook up a certificate validation function.

This is unlikely to be a libgit2 problem.  Please see the pygit2 documentation for instructions, ask a question on StackOverflow, or open a question in their repository if you still believe that there is a bug.

**Comment by yar05** [comment]
This problem appears on every https website including github.com
