### ISSUE TITLE
Convert remote branch Ref to valid Refspec

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#4903]
Given a local branch ref like `refs/heads/master` and a remote branch ref `refs/remotes/origin/foo` I cannot find a way with the current api to produce a valid refspec that `git_remote_push` accepts.

Just concatenating them like so wont work: `refs/heads/master:refs/remotes/origin/foo`

I have to manually "rename" the remote branch ref with naive string ops to look like `refs/heads/foo` to produce a valid refspec for pushing to a remote name with a different name.

Looking like this: `refs/heads/master:refs/heads/foo`

Did I overlook something or how else do I get from a remote branch name to a refspec name that `git_remote_push` will accept? Or is there simply no API to convert?

**Comment by pks-t** [comment]
The first refspec you have ("refs/heads/master:refs/remotes/origin/foo") rather looks like a fetch-refspec. It tells you Git to always fetch the fetched reference "refs/heads/master" into your local reference "refs/remotes/origin/foo". So this is really only used for fetching, and not for pushing.

For pushing, this kind of depends on what exactly you want to do and where you exactly get the remote branch reference from. If you say simply `git push origin foo`, then Git will assume that the destination reference is the same as the source reference, so it is equivalent to saying `git push origin foo:foo` or `git push origin refs/heads/foo:refs/heads/foo`. The refspec in that case would be "foo:foo" or "refs/heads/foo:refs/heads/foo". If that is not the case, then you have to manually fiddle around, same as you'd do on the command line.

I think this is really no different to what you're doing in Git itself. If you want to push your branch to a different upstream branch, you have to fiddle around with the refspec, too. E.g. by saying `git push foo:bar` or saying `git push refs/heads/foo:refs/heads/bar`. Again, the refspecs in these cases would be "foo:bar" or "refs/heads/foo:refs/heads/bar".

I guess your confusion stems from the difference between fetch and pull refspecs, which are slightly different in both cases. In case of a fetch, you fetch into kind of a remote namespace "refs/remote/origin/foo". In case of a push, you push directly to a branch "refs/heads/foo" instead of pushing into this remote namespace.

**Comment by eaigner** [comment]
Basically what I am doing is looking up all local and remote branches using `git_branch_lookup`. Now I want to push to one of the returned remote branches which is always in this form `refs/remotes/origin/foo` (which I have to manually correct to `refs/heads/foo` for the target refspec).

**Comment by pks-t** [comment]
Sorry for not answering earlier, I had been off for some weeks.

You are able to do so with `git_refspec_rtransform`. The following code is an example for how to do so. I based it off of our examples code, so you'll obviously have to adjust the `check_lg2` calls. But it works as you expect, transforming a refspec of "refs/remotes/origin/foo" to "refs/heads/foo".

```
#include "common.h"

int main(int argc, const char *argv[])
{
	const git_refspec *refspec;
	git_buf transformed = {0};
	git_repository *repo;
	git_remote *remote;

	(void)(argc);
	(void)(argv);

	git_libgit2_init();

	check_lg2(git_repository_open_ext(&repo, ".", 0, NULL),
			"Couldn't open repository", NULL);
	check_lg2(git_remote_lookup(&remote, repo, "origin"),
			"Couldn't look up 'origin' remote", NULL);

	refspec = git_remote_get_refspec(remote, 0);

	check_lg2(git_refspec_rtransform(&transformed, refspec, "refs/remotes/origin/foo"),
			"Couldn't transform refspec", NULL);

	printf("Transformed: '%s'\n", transformed.ptr);

	git_buf_dispose(&transformed);
	git_remote_free(remote);
	git_repository_free(repo);

	return 0;
}
```

**Comment by eaigner** [comment]
Thanks for your reply. Mhm, I imagined that I tried transforming, but without luck. I'll try your snippet later. Thanks!
