### ISSUE TITLE
.gitignore syntax with cascaded rules fail 

### ISSUE THREAD

**Issue by oomathias** [libgit2/libgit2#5037]
I was tracking down a bug in Atom see https://github.com/atom/tree-view/issues/196#issuecomment-478982049

### Reproduction steps

`.gitignore`

```ini
*           # Ignore all files
!/**/       # Allow directories
!*.keep     # Allow .keep files
!.gitignore # Allow .gitignore
```

files
```
.
├── .gitignore
└── src
    ├── A
    └── A.keep
```

custom test case
```c
void test_attr_ignore__mytest(void)
{
	cl_git_rewritefile(
		"*\n",
		"!/**/\n"
		"!*.keep\n"
		"!.gitignore\n"
	);

	assert_is_ignored(false, "src/"); // PASS
	assert_is_ignored(false, "src/A.keep"); // PASS
	assert_is_ignored(false, ".gitignore"); // PASS
	assert_is_ignored(true, "src/A"); // FAIL
}
```

### Expected behavior

`src/A` should be ignored

Proof:
<img width="330" alt="screenshot 23" src="https://user-images.githubusercontent.com/465790/55477194-c1ac2900-5618-11e9-8206-64d95d5c7673.png">

### Actual behavior

`src/A` is not ignored

### Version of libgit2 (release number or SHA1)

9aa049d4c1578cfd73ce66801fe2575632296060 (includes #5020)

### Operating system(s) tested

OSX 10.14.4 (18E226)

**Comment by pks-t** [comment]
Thanks for your report and testcase! Unfortunately, the testcase itself is faulty. Instead of writing the ".gitignore" file, you're writing the ignore rules into a file named "*\n" (first parameter to `cl_git_rewritefile`). The following passes just fine:

```
void test_attr_ignore__mytest(void)
{
	cl_git_rewritefile(
		"attr/.gitignore",
		"*\n"
		"!/**/\n"
		"!*.keep\n"
		"!.gitignore\n"
	);

	assert_is_ignored(false, "src/A.keep");
	assert_is_ignored(false, ".gitignore");
	assert_is_ignored(true, "src/A");
}
```

Note my intentional omission of `assert_is_ignored(false, "src/")`. In fact, we do report it as being ignored even though it should not be.

**Comment by pks-t** [comment]
And this issue is in fact trivially fixed. The problem here is that "!/**/" gets added to our list of ignores as a negative ignore matching directories only. But if we use `git_ignore_path_is_ignored`, then we cannot always tell whether the given path is a directory or simple file because the path doesn't need to exist (e.g. the results would be different depending on whether "src" is a directory or not).

So in the cas where we give "src" to `git_ignore_path_is_ignored`, it is very much assumed that it would say it is ignored, because "src" may not necessarily be a directory. On the other hand, passing "src/" to that function should very much assume that the path name is a directory, and so we should say that it is not ignored in that case.

I'll create a PR shortly to fix that.

**Comment by oomathias** [comment]
Thanks for your detailed answer and the PR.

Sorry about that faulty test case I read the code too fast...
I tested again with your fix and now everything work as expected 🎉 

I also tested with the version used by atom `v0.27.0` and `assert_is_ignored(true, "src/A");` was faulty. So this bug is gone in `libgit2`.

**Comment by pks-t** [comment]
Perfect, thanks for letting me know!
