### ISSUE TITLE
Why Submitted files are deleted by default when submitted?

### ISSUE THREAD

**Issue by xiaofuhub** [libgit2/libgit2#5048]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

**Comment by xiaofuhub** [comment]
First. delete file examples:
	error = git_index_remove_all(index, &_pathspecs, index_matched_path_cb, local_opt);  
	error = git_index_write(index);
Second. I  use the index to commit, but, I don't select the file by my removed, but, It is also commit to the repository. Am I getting the index error ?

**Comment by xiaofuhub** [comment]
https://github.com/xiaofuhub/BranchTest/blob/serverbranch001/remove&commit.c

**Comment by pks-t** [comment]
I'm not quite sure I understand, but from what I gather I think your problem is that all files are deleted even though you only wanted to delete selected files from the index.

The thing is, given your code libgit2 actually behaves as expected:

```
error = git_index_remove_all(index, &_pathspecs, NULL, NULL);  //index_matched_path_cb
if(error < 0)
{
	break;
}
```

If `_pathspecs` contains any paths, then `git_index_remove_all` will remove only those selected paths. If `_pathspecs` is not given or empty, then libgit2 will remove _all_ entries from the index. And this is in fact what you accidentally do: you create a pathspecs array with `strArray` and `file_num`. I don't know what `file_num` is, but I do know that `strArray` is never set to anything but `NULL`. Due to that, we take it as an empty pathspec and delete all entries from the index. What you probably intended to use was not `strArray`, but the `file_name` argument from `git_remove`.

**Comment by xiaofuhub** [comment]
thanks,this is my specific doubts  https://stackoverflow.com/questions/55609934/why-is-the-deleted-file-commit-by-default-when-using-the-commit-command-in-libgi
