### ISSUE TITLE
Cannot init repo in root directory with absolute path

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#5130]
### Reproduction steps
Call `git_repository_init_ext` with path `/foo` on a posix-like system (not windows) for a path that does not exist.

```c
git_repository *repo;
git_repository_init_options initopts = GIT_REPOSITORY_INIT_OPTIONS_INIT;
git_libgit2_init();
initopts.flags |= GIT_REPOSITORY_INIT_MKDIR | GIT_REPOSITORY_INIT_MKPATH;
int error = git_repository_init_ext(&repo, "/foo", &initopts);
if (error) {
    const git_error *err = git_error_last();
    fprintf(stderr, "[%d] %s\n", err->klass, err->message);
}
```

### Expected behavior
Creates a new repo `/foo/.git`

### Actual behavior
Fails with `[2] failed to make directory '/foo/.git': No such file or directory`

### Version of libgit2 (release number or SHA1)
55a1535dd51c62f4e4ed764412200bbd49f3a1ab

### Operating system(s) tested
Linux or macOS.

### Notes
This is caused by the change in #5050.

**Comment by neithernut** [comment]
I just tried reproducing this issue (successfully) on Linux. I noticed, an additional anomaly: when run as a regular user, the reproducer obviously fails due to permissions.However, at least the formatting of the error message is broken. The first character is missing:

    [2] failed to make directory '/oo': Permission denied

When run as root, the reproducer actually creates the directory `/oo`.

Also, as the issue's title suggests, the issue does not arise when the new repository is not created in `/`.
