### ISSUE TITLE
Drop Slack

### ISSUE THREAD

**Issue by ddevault** [libgit2/libgit2#5228]
>Visit slack.libgit2.org to sign up, then join us in #libgit2. If you prefer IRC, you can also point your client to our slack channel once you've registered.

Open source projects should not use a proprietary chat medium. IRC users can no longer connect, the Slack bridge was taken down years ago. Please consider moving to a better chat medium, such as IRC or Matrix.

**Comment by ethomson** [comment]
I’ll leave this open for a hot minute, but I don’t have any interest in moving, personally.

**Comment by ethomson** [comment]
I realize that my haste seems dismissive.  Apologies.

We have our own slack because it allows us multiple channels.  The nodegit project has its own channel to communicate with that project, but still allows us to cross communicate on issues that affect us mutually (either policy or technical).  We can also have private channels.

Plus slack is the de facto communication mechanism for many of us and I (for one) want to minimize the number of places I communicate.

There is a #libgit2 on freenode - which I encourage you to use if you don’t like slack - but I think that keeping the main policy discussion of the project on slack is a fine goal.

So I’m solidly 👎 on this but I’m sure that others may want a chance to weigh in.

**Comment by ddevault** [comment]
IRC can have several channels, too, even Freenode will let you manage a group of channels formally if you wish. You can create ad-hoc channels with zero overhead, too, you just join them and boom, they exist. Private channels are easily done, too. All of the reasons you state for Slack are things supported by IRC. Matrix as well, I think.

You'll never see me on Slack and I'm not the only one. This choice limits who will contribute to your project.

**Comment by joepie91** [comment]
I'd also like to add that Matrix is specifically designed to support (first-class) bridges to other protocols, including Slack, so that you can *actually* centralize your communications into a single client, without necessarily needing to centralize the conversations themselves to a single platform.

There will of course always be imperfections in bridging due to protocol design mismatches, but in my experience the bridging in Matrix works quite well in practice, and I've come to prefer it over eg. having a dedicated IRC client.

(Matrix, like IRC, is a semi-decentralized protocol rather than a single centralized service.)

**Comment by ethomson** [comment]
> You'll never see me on Slack and I'm not the only one. This choice limits who will contribute to your project.

OK, but why is our irc channel not sufficient for your needs?

**Comment by ddevault** [comment]
Official? It seems to be a second-class citizen, with only 12 people in it, and a link to join slack.

**Comment by ethomson** [comment]
I think you're overestimating how much discussion happens in our slack channel.

**Comment by ddevault** [comment]
Will you add the IRC channel to the README, along with the Slack instructions? The idea that you can connect to Slack with an IRC client is badly outdated, that should be removed.

**Comment by ethomson** [comment]
> Will you add the IRC channel to the README, along with the Slack instructions? The idea that you can connect to Slack with an IRC client is badly outdated, that should be removed.

Yes, I think that we should do this.  Sorry, I thought I mentioned it upthread, but it seems that I did not.  Mea culpa.

If you'd be interested in opening a pull request, that would be great.  Otherwise, I'll do this when I have some time.

**Comment by ddevault** [comment]
https://github.com/libgit2/libgit2/pull/5229

**Comment by ddevault** [comment]
I still encourage you to leave Slack, on the basis that a proprietary and centralized chat system has no business being part of the infrastructure of an open source community. But since IRC is shown in the README now, I'll close this issue.

**Comment by pks-t** [comment]
> I still encourage you to leave Slack

As said in IRC I can totally relate. I'd love to drop Slack, too, and in fact I'd also love to use a more open alternative to GitHub. For Slack we'd need a good alternative, though, as IRC is quite strange for those who don't use it frequently. Maybe we should have a look at Mattermost, but I don't know how much support that'd garner. And I do think it would actively hurt libgit2 to switch away from GitHub, as it still is the most popular platform by far and thus helps us attract more people. :/

**Comment by ddevault** [comment]
I don't really agree that Github helps much to attract people. After all, libgit2's popularity is naturally equal to or less than the popularity of git itself, which isn't hosted on Github.

**Comment by ethomson** [comment]
> I don't really agree that Github helps much to attract people. After all, libgit2's popularity is naturally equal to or less than the popularity of git itself, which isn't hosted on Github.

It's GItHub with a capital H.

**Comment by ddevault** [comment]
Who cares?

**Comment by ethomson** [comment]
> Who cares?

I do, for one.

GitHub has been a major contributor to libgit2 since it started, providing both developers and cash money.  Independent of that, you can suggest that libgit2 not be hosted on GitHub, but there's no need to be rude about being corrected about how to spell the organization's name.

**Comment by ddevault** [comment]
Frankly, it's much ruder that you'd stop the discussion to issue such pedantry. It's not insulting to GitHub to call them Github. It can hardly even be considered a mistake. It's a README.md, not a [README](https://github.com/libgit2/libgit2/issues/5228#issuecomment-533179486); it's Slack, not [slack](https://github.com/libgit2/libgit2/issues/5228#issuecomment-531597101), it's [IRC](https://github.com/libgit2/libgit2/issues/5228#issuecomment-531595055), not irc; it's de-facto, not [de facto](https://github.com/libgit2/libgit2/issues/5228#issuecomment-531548397), and so on. I don't think that derailing discussions to correct people on the capitalization of GitHub is doing your employer any favors.

**Comment by ddevault** [comment]
It's sourcehut, Sourcehut, SourceHut, sr.ht, whatever, interchangably. Naturally, I do not take offense at any stylization of the company's name as it comes up in casual development conversations. I don't want to argue about this with you any further.

**Comment by aaronfranke** [comment]
I know this issue is old and closed, but I'd like to revive this issue, because another option has become available.

[Rocket.Chat](https://rocket.chat) is an open source chat platform that is similar to Slack. It can either be self-hosted, on a server libgit2 hosts, or you can pay them to host. Compared with Slack, it is open source, and shares many features, including text channels, threading, direct messages, emojis, and more. Compared with IRC, it has a ton more features. Compared with Matrix, it's far easier to use.

Godot has been using Rocket.Chat for awhile. You can see what it looks like by [joining their server](https://chat.godotengine.org).
