### ISSUE TITLE
No support for proxy url without trailing slash

### ISSUE THREAD

**Issue by kcajf** [libgit2/libgit2#5255]
I've been trying to debug this issue: https://github.com/JuliaLang/julia/issues/33405 which I really suspect is a libgit2 issue, so I've been running some tests. Some appear to be failing on lasest master f04a58b00, however I'm not sure if this is because I am behind a web proxy. Should the tests in theory work behind a proxy anyway?

Test output attached
[tests.txt](https://github.com/libgit2/libgit2/files/3692140/tests.txt)

**Comment by ethomson** [comment]
> I've been trying to debug this issue: JuliaLang/julia#33405 which I really suspect is a libgit2 issue, so I've been running some tests. Some appear to be failing on lasest master f04a58b, however I'm not sure if this is because I am behind a web proxy. Should the tests in theory work behind a proxy anyway?

No, you'll need a direct connection to run any of the `online` tests.  Nor can they likely be made to use a proxy since many of them set up our own proxy.

We've changed the way we deal with networking and proxies relatively recently.  Do you happen to know what version of libgit2 it is that julia is using?

**Comment by kcajf** [comment]
Ok, makes sense, thanks.

The commit that changed the libgit2 version (which was previously working fine on this machine, and no config has changed since) is https://github.com/JuliaLang/julia/pull/32806/files
i.e. from 0.27.7 -> 0.28.2. As a result, it seems likely this is proxy-related.

**Comment by ethomson** [comment]
I'm not very familiar with Julia so it's pretty hard for me to parse what's going on.  It definitely looks like [`GIT_PROXY_AUTO`](https://github.com/libgit2/libgit2/blob/master/include/git2/proxy.h#L31) should be set.  It looks like that's the default for [`ProxyOptions`](https://github.com/JuliaLang/julia/blob/2e91c5e73af4e44c45e942e057e5c09fa062cf8f/stdlib/LibGit2/src/types.jl#L315) in Julia, and ultimately in [`FetchOptions `](https://github.com/JuliaLang/julia/blob/2e91c5e73af4e44c45e942e057e5c09fa062cf8f/stdlib/LibGit2/src/types.jl#L355).

But is it possible to call `clone` without specifying `FetchOptions`?  If so that would implicitly use `GIT_PROXY_NONE`.  The change here is that we previously would have just handed this over to libcurl and it would have ignored our proxy settings, while now we never use libcurl so we always respect the information provided to the API options.

**Comment by kcajf** [comment]
Thanks for digging into this. I tried to run my snippet again with `GIT_PROXY_NONE`:
```
import LibGit2

const repo_url = "https://github.com/JuliaRegistries/General.git"
const repo_path = "/tmp/General"
const credentials = nothing
const callbacks = LibGit2.Callbacks()
const cred_payload = LibGit2.reset!(LibGit2.CredentialPayload(credentials))
callbacks[:credentials] = (LibGit2.credentials_cb(), cred_payload)
const lbranch = Base.cconvert(Cstring, "")
const remote_callbacks = LibGit2.RemoteCallbacks(callbacks)
const fetch_opts = LibGit2.FetchOptions(callbacks=remote_callbacks, proxy_opts = LibGit2.ProxyOptions(proxytype=LibGit2.Consts.PROXY_NONE))
const clone_opts = LibGit2.CloneOptions(
            bare = Cint(false),
            checkout_branch = Cstring(C_NULL),
            fetch_opts = fetch_opts,
            remote_cb = C_NULL
        )
LibGit2.ensure_initialized()
const clone_opts_ref = Ref(clone_opts)
const repo_ptr_ptr = Ref{Ptr{Cvoid}}(C_NULL)

ccall((:git_clone, :libgit2), Cint,
            (Ptr{Ptr{Cvoid}}, Cstring, Cstring, Ref{LibGit2.CloneOptions}),
            repo_ptr_ptr, repo_url, repo_path, clone_opts_ref)
```
and the final call now returns `-1` instead of `-12` ..

**Comment by kcajf** [comment]
I just tried the above but with the modification:
```
const fetch_opts = LibGit2.FetchOptions(callbacks=remote_callbacks,
 proxy_opts = LibGit2.ProxyOptions(proxytype=LibGit2.Consts.PROXY_SPECIFIED, url=Cstring(pointer("http://mywebproxy:3128"))))
```
and I got `-12` again.

Are there any obvious places that the `GIT_EINVALIDSPEC` error code can originate from? Can you think of any way that I can debug this in more detail - any way to get back a stacktrace or anything?

**Comment by kcajf** [comment]
Snippet works fine on a computer with a direct connection - same julia version (and by extension libgit2 version)
Perhaps I'm barking up the wrong tree with the proxy thing, and there is just some other differentiating factor.. Though two computers that are failing behind the proxy are reasonably different between themselves: one is Fedora 28, one is CentOS 7, different hardware, etc.

**Comment by kcajf** [comment]
I've realised I can get out the libgit2 error message:
```
julia> ccall((:git_clone, :libgit2), Cint,
                   (Ptr{Ptr{Cvoid}}, Cstring, Cstring, Ref{LibGit2.CloneOptions}),
                   repo_ptr_ptr, repo_url, repo_path, clone_opts_ref)
-12

julia> LibGit2.Error.last_error()
(LibGit2.Error.Net, "invalid url, missing path")
```
but I'm struggling to find out where that is getting raised

**Comment by kcajf** [comment]
OK, finally worked it out! When I use `GIT_PROXY_SPECIFIED`, if I specify the proxy url as `http://mywebproxy.com:3128` it fails, but if I add a trailing slash (`http://mywebproxy.com:3128/`) it succeeds. I feel like the trailing slash should be optional.

**Comment by hkrummeck** [comment]
I have the same problem, a proxy url without a trailing slash is not accepted (0.28.1).

The reason seems to be an error ("invalid url, missing path") which will be raised in `netops.c:gitno_extract_url_parts()` if the url has no path component. 

With `GIT_PROXY_SPECIFIED `you can use the workaround with the trailing slash but `GIT_PROXY_AUTO `always fails.

**Comment by ethomson** [comment]
Aha, appreciate the additional debugging.  This was fixed in https://github.com/libgit2/libgit2/pull/5052/commits/c6ab183e9c960b74471a7d106a4deb0c8b28a8ec and will be included in the next release which we hope to be :soon:.
