### ISSUE TITLE
Crash with invalid proxy configuration

### ISSUE THREAD

**Issue by seshonaar** [libgit2/libgit2#5323]
libgit 0.28.3
winhttp.c
winhttp_stream_connect
if (proxy_url)
gitno_extract_url_parts
default port not specified

If the configuration contains an URL without a port (as a mistake for example), gitno_extract_url_parts will try to deference the default_port received as argument, that is NULL.

**Comment by pks-t** [comment]
Did you check whether this behaviour still exists in current master? We've removed `gitno_extract_url_parts` due to some refactorings in c6ab183e9 (net: rename gitno_connection_data to git_net_url, 2019-03-11), and we're not passing any default ports anymore. I'd thus expect that this has been implicitly fixed already.

**Comment by seshonaar** [comment]
I confirm. The issue only exists in 0.28.3.

**Comment by seshonaar** [comment]
Still, because as of latest libgit2sharp is using 0.28.4, the issue affects a PR that would allow libgit2sharp to detect proxy settings https://github.com/libgit2/libgit2sharp/pull/1708 . I'll move the discussion there

**Comment by pks-t** [comment]
Thanks a lot for confirming! Normally I'd consider backporting, but backporting this particular season doesn't seem feasible to me as there's too many things that've been changed. It's a bit unfortunate, but yeah. We're prorably going to release v0.99 soon-ish anyway, at which point libgit2sharp could upgrade to our newer release.
