### ISSUE TITLE
`pack::packbuilder` tests failing on v0.28.3

### ISSUE THREAD

**Issue by krallin** [libgit2/libgit2#5324]
### Reproduction steps

I took a fresh clone of v0.28.3, and I'm building it and running the packbuilder tests using:

```
make -DUSE_HTTPS=OFF -DUSE_NTLMCLIENT=OFF .. && cmake --build . && ./libgit2_clar -spack::packbuilder
```

### Expected behavior

The tests pass.

### Actual behavior

Unfortunately, this fails on my system, with the following errors:

```

  1) Failure:
pack::packbuilder::create_pack [/home/torozco/local/foo/libgit2/tests/pack/packbuilder.c:139]
  String mismatch: hex != "5d410bdf97cf896f9007681b92868471d636954b"
  '5f688cedc3a5132f15fc3352a35bc5dcb6a536a4' != '5d410bdf97cf896f9007681b92868471d636954b' (at byte 1)

  2) Failure:
pack::packbuilder::get_hash [/home/torozco/local/foo/libgit2/tests/pack/packbuilder.c:151]
  String mismatch: hex != "7f5fa362c664d68ba7221259be1cbd187434b2f0"
  'f120f6bbad709d0e3c021ca8f9d7c26c3882497b' != '7f5fa362c664d68ba7221259be1cbd187434b2f0' (at byte 0)

  3) Failure:
pack::packbuilder::permissions_standard [/home/torozco/local/foo/libgit2/tests/pack/packbuilder.c:175]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - <no message>

  4) Failure:
pack::packbuilder::permissions_readonly [/home/torozco/local/foo/libgit2/tests/pack/packbuilder.c:175]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - <no message>

  5) Failure:
pack::packbuilder::permissions_readwrite [/home/torozco/local/foo/libgit2/tests/pack/packbuilder.c:175]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - <no message>
```

It looks like those are all symptoms of the same underlying problem (i.e. the hash generated by packbuilder is different).

On another machine, I'm able to get the tests to pass. Here is is the configure output for the machine I'm working on:

```
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Checking for module 'libssh2'
--   No package 'libssh2' found
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
-- Enabled features:
 * nanoseconds, whether to use sub-second file mtimes and ctimes
 * tracing, tracing support
 * threadsafe, threadsafe support
 * SHA, using CollisionDetection
 * regex, using system PCRE
 * http-parser, http-parser support (bundled)
 * zlib, using system zlib

-- Disabled features:
 * debugpool, debug pool allocator
 * HTTPS
 * SSH, SSH transport support
 * ntlmclient, NTLM authentication support for Unix
 * SPNEGO
 * iconv, iconv encoding conversion support
 * valgrind, valgrind hints
```

How would I go about debugging this?

### Version of libgit2 (release number or SHA1)

v0.28.3

### Operating system(s) tested

CentOS

**Comment by ethomson** [comment]
Wow.  I've built libgit2 and run our test suite on countless machines - physical, virtual, and containers; Linux, macOS, Windows.  Even a few oddball old Unixes.  And never have I seen this.

Are you getting consistently the same results?  Do subsequent test runs _always_ have the same failures?  Are they identical with the same hex output?  (eg, does `pack::packbuilder::get_hash` always fail with `'f120f6bbad709d0e3c021ca8f9d7c26c3882497b' != '7f5fa362c664d68ba7221259be1cbd187434b2f0' (at byte 0)`?

Is there anything interesting about this machine?  Is it a real machine or a VM?  Any interesting changes?  (SELinux?)  Any interesting hardware failures?  Flaky RAM?

What's the "other system" that this works on?  How is it different?

**Comment by ethomson** [comment]
Also, since you mention that you're trying v0.28.3: did you `git clone https://github.com/libgit2/libgit2` and then check out the `v0.28.3` tag?  Or did you download a tarball of the source?

If the latter, can you try cloning the repository and building there?

And if **that** gives you the same problem, I'm curious if checking out master and building **that** gives you the same problem as well.

**Comment by krallin** [comment]
@ethomson 
 
> Are you getting consistently the same results? Do subsequent test runs always have the same failures?

The error is indeed deterministic: I always get the exact same hashes (`5f688cedc3a5132f15fc3352a35bc5dcb6a536a4` and `f120f6bbad709d0e3c021ca8f9d7c26c3882497b`).

> Is there anything interesting about this machine? Is it a real machine or a VM? Any interesting changes? (SELinux?) Any interesting hardware failures? Flaky RAM?

I'm running this on a CentOS 7 VM. AFAIK, the hardware isn't flaky (I certainly haven't seen any issues that would suggest it might be), but I can try to repro on a separate but similarly configured VM to confirm if necessary (though I guess the determinism suggests the hardware might be fine).

One thing that's a bit unusual and comes to mind about the VM is that the root volume is BTRFS, but I tried running the tests with `TMP` pointing at a tmpfs, and that didn't help. I also tried cloning libgit2 into a tmpfs but the issue remained.

We also use in-house built libraries for most things, but I configured libgit to build using its internal PCRE dep instead of the system one (it made no difference either way).

If that's useful, here is the output of strace from running the test, showing what we're accessing (I edited this a little bit to some internal details — I notably stripped the dynamic linker parts): [trace.txt](https://github.com/libgit2/libgit2/files/3935183/trace.txt).

> What's the "other system" that this works on? How is it different?

I tried on a Mac laptop, so different in quite a lot of ways! :) 

> Also, since you mention that you're trying v0.28.3: [...]
 
I had both downloaded the tarball and git-cloned it. I also tried again on master now, and I'm seeing the same error on all 3 approaches.

**Comment by pks-t** [comment]
> I also tried cloning libgit2 into a tmpfs but the issue remained.

Okay, so you did create a completely new clone which wasn't a tarball at one point, right? I'm asking because we had issues with release tarballs in the past and also because it's possible for some data to end up in any of our embedded git repos which isn't catched by "git status" at all.

You're probably not able to share the VM images? If not, is your machine configured in any special way with regards to either hardware or CentOS so that we can try and reproduce?

**Comment by pks-t** [comment]
I just spun up a CentOS 7 VM under qemu with btrfs filesystem and SELinux enabled. I wasn't able to reproduce your problem with either v0.28.3 cloned as a git repository nor by using the release tarball. :/

**Comment by pks-t** [comment]
You would've probably mentioned, but this is an x86_64 machine, right? No big endian/little endian mismatches to be expected?

**Comment by krallin** [comment]
> Okay, so you did create a completely new clone which wasn't a tarball at one point, right?

Yep!

> You're probably not able to share the VM images? If not, is your machine configured in any special way with regards to either hardware or CentOS so that we can try and reproduce?

Probably in more ways than I could count, unfortunately :( These machines are managed internally at $work and they're using packages built internally, a Kernel built internally, etc.

Many of those things don't diverge from upstream, but I'm sure some of them do. I think it's a likely possibility that one of those things is behaving unusually (or incorrectly) and causing the issue, but I'd love to root cause it to fix it or make libgit2 more robust against it if the behavior isn't incorrect but just unusual.

Is there some information I could collect during the execution of the test in order to debug why the pack being produced has a different hash (and which I could compare to the output on my Mac). I'm happy to do the legwork here, but a few pointers regarding where to start would be very helpful! 

> You would've probably mentioned, but this is an x86_64 machine, right? No big endian/little endian mismatches to be expected?

It's indeed an x86_64 machine, yep

**Comment by pks-t** [comment]
> Probably in more ways than I could count, unfortunately :( These machines are managed internally at $work and they're using packages built internally, a Kernel built internally, etc.

Is libgit2 currently linking against any non-standard library that might explain the behaviour? We've had cases in the past where incompatible libraries were used at runtime due to some custom built ones being loaded. The output of ldd might be useful here. 

> Is there some information I could collect during the execution of the test in order to debug why the pack being produced has a different hash (and which I could compare to the output on my Mac). I'm happy to do the legwork here, but a few pointers regarding where to start would be very helpful!

Hard to tell. I think the first thing that we should try to come up with is a minimal reproducer outside of the libgit2 test framework. Like, creating a minimal repo that pinpoints the issue and determining at which exact step we start to diverge from what builds on other machines do. This should be hopefully be rather easy to do with the existing failing test, but it'd already help to remove everything unrelated to the failure. I usually do so by creating a new command in our "examples/" structure, which is the most straight forward. Let me know if you need any help here.

After we've got that I'd love to compare straces once again, which should hopefully be less verbose then. Ideally, I'd like to be able to compare strace for two machines which are as similar to each other as possible while one of them fails and the other one succeeds. You said you've got other VMs available, so maybe we're lucky and one of them doesn't exhibit faulty behaviour. So maybe we're able to see any telling differences between these logs.

**Comment by krallin** [comment]
Got it; thanks for the pointers! I'm going to try and see if I can put together a smaller repro from this.

**Comment by krallin** [comment]
> Is libgit2 currently linking against any non-standard library that might explain the behaviour?

Here's the output of ldd:

```
$ ldd build/libgit2.so
	linux-vdso.so.1 =>  (0x00007ffc52de3000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe65e877000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe65e65b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe65e445000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe65e078000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe65ee01000)
```

Unfortunately, as I mentioned, it is possible that those aren't exactly identical to their upstream counterparts :/

**Comment by pks-t** [comment]
I'd encourage you to remove the external dependency on zlib by using our bundled zlib instead with "-DUSE_BUNDLED_ZLIB=ON". This at least reduces the possibility that it's anything caused by your special environment, as I think it really unlikely that it's anything in any of the standard libraries.

**Comment by krallin** [comment]
Aha, I was just trying that out in fact! Indeed, it looks like using bundled zlib makes the problem go away. Now, to figure out why that is..!

**Comment by pks-t** [comment]
Interesting. This is probably a custom version of zlib, right? The big question is whether this is a certain version of zlib itself that creates the issue or whether it's some custom patches you have. Can you share RPM build instructions for your version of zlib or is that not possible?

**Comment by krallin** [comment]
Yeah, it appears to be at least quite a bit different from upstream. That said, it appears that if you use https://github.com/cloudflare/zlib as your zlib, the exact same error repros!

**Comment by pks-t** [comment]
Cool, thanks for the hint! I'm currently fixing some other errors, but will try to come back here to reproduce.

**Comment by krallin** [comment]
I put up a repro using Cloudflare's zlib here — running the `xx.sh` script _should_ repro the issue, though the whole thing is a bit janky (also, I imported zlib as a git submodule, so you'd want to make sure you pull it): https://github.com/krallin/libgit2/tree/packbuilder-repro

**Comment by pks-t** [comment]
Yup, that's it. Building zlib from the cloudflare repo and starting libgit2_clar with LD_PRELOAD pointing to libz.so brings up the errors.

**Comment by pks-t** [comment]
It's very likely that the problem here is some improper use of the zlib API. Notable is that you're only experiencing issues in pack::, but in fact we're using zlib e.g. for loose objects, too. The main difference between both is that for loose objects, we use our zstream abstraction which is battle hardened already, while for packfiles we use self-rolled zlib invocations.

I'm currently refactoring the packfile code to make use of zstream, too. I'll probably not get this done today, but hope for this weekend or next week.

**Comment by pks-t** [comment]
So I did the refactoring part, but it didn't fix the issue. I thus decided to bisect into Cloudflare's zlib fork, which ended up at 5f1bd2b (It changes the hash and longest match functions to always match at least 4 bytes, instead the 3 the spec allows. It allows for faster and more effective compression because there are less hash collisions, and false matches are discarded faster. In theory it could lead to worse compression in some cases, but for the most common files there is an improvement for all levels both in speed and in compression ratio., 2014-11-29). Jay for short commit summaries :/

Anyway. It seems to me like Cloudflare optimized zlib while disregarding the spec, as they say themselves (matching last 4 bytes instead of last 3 as the spec allows). Thus the compressed results are different to what we expect from "normal" zlib. One could argue that we shouldn't rely on stable output from zlib anyway in those tests, but in the past we've always been good with this and didn't have any problems.

In the end, I feel like this isn't something we can do anything about, except that we could remove these tests. I'm not too thrilled about that though and thus tend towards "It's their problem, as they knowingly violate the spec". That being said, I don't think libgit2 or git should care about this during normal operations.

There's at least some good outcome of this with the refactoring I did for packfile zlib code which I'm going to post in a few minutes.

**Comment by krallin** [comment]
Thanks a ton for the thorough investigation @pks-t! Do you think it would make sense to do one of the following:

- Detect which zlib we're using, and expect the corresponding hash?
- Allow both hashes?

It'd be awesome to have this test passing, or at least skipped without the need to maintain local patches!

**Comment by pks-t** [comment]
I'm honestly not too thrilled about including workarounds for that. The thing is that Cloudflare's fork _explicitly_ says they're breaking the spec with their changes, which is not something that seems sane to support if you ask me. On the other hand it seems crazy to rely on stable zlib output, but it has worked well enough on all platforms until now.

Dunno. To me it feels like the issue is in Cloudflare's fork -- the most sensible way forward would be to fix their disregard of the spec instead of adding workarounds in dependents, right?

**Comment by ethomson** [comment]
My reading of that is that the spec _allows_ an implementation to match a 3 byte span of bytes, but doesn't _enforce_ that an implementation must match a 3 byte span of bytes.  If that interpretation is correct then they're not really out of specification, this really is just down to differences in the implementation.

Put a different way:  wouldn't changing compression levels make our tests fail?  If I'm understanding correctly: if we turned on the moral equivalent of no compression, we'd end up with different hashes here.

This does feel like a not very stable test, and I'm honestly a bit surprised that we haven't seen this before now.  I guess that just shows the consistency of the (standard) zlib implementation.

I don't have a good solution here, though.  I think that three of those tests are really just looking at the permissions, so that doesn't depend on a stable hash or a consistent zlib result.

I haven't  👀 to have a good idea for a solution (I'll take a look over the weekend), but I think that we should probably change the other two, as well.

**Comment by pks-t** [comment]
> My reading of that is that the spec allows an implementation to match a 3 byte span of bytes, but doesn't enforce that an implementation must match a 3 byte span of bytes. 

Fair enough.

> Put a different way: wouldn't changing compression levels make our tests fail? If I'm understanding correctly: if we turned on the moral equivalent of no compression, we'd end up with different hashes here.
> This does feel like a not very stable test, and I'm honestly a bit surprised that we haven't seen this before now. I guess that just shows the consistency of the (standard) zlib implementation.

Yeah, definitely. I've been surprised by this, too. Dunno. I'd probably be fine to drop these tests or at least drop the expectance of stable hashes, but I'm opposed to adding workarounds like accepting both hashes. @krallin: I guess if you'd come up with a PR that removes our reliance on stable zlib output then chances are high we merge it.
