### ISSUE TITLE
"cred.h" is missing in releas tarball

### ISSUE THREAD

**Issue by maxmeyer** [libgit2/libgit2#5343]
### Reproduction steps

1. Download release tarball https://github.com/libgit2/libgit2/archive/v0.28.4.tar.gz
2. Browse archive and look for "cred.h"

### Expected behavior

"cred.h" is part of tarbal, as this is required to build "git2go".

### Actual behavior

"cred.h" is missing in release tarball

### Version of libgit2 (release number or SHA1)

0.28.4

### Operating system(s) tested

Arch Linux (https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libgit2)

**Comment by ethomson** [comment]
Weeeeeeeeird.  These are created automatically -- @carlosmn do you know how these are generated or know who does?

**Comment by maxmeyer** [comment]
Any progress on this?

**Comment by pks-t** [comment]
Well, "cred.h" was renamed to "credentials.h" now. So maybe the bug is fixed by this :P

Anyway, I feel like we should start assembling our own archives. Maybe we should create a script that takes the new version as argument and then:

- verifies that we've incremented the version correctly in all the required places
- verifies release notes from our CHANGELOG.md
- creates the archives
- creates a GitHub release using the archive and release notes extracted from CHANGELOG.md

This would implicitly document our release process, ensure consistency and makes sure that nothing is forgotten. I'll have a look at the GitHub API and try to come up with something that can then also be used for our upcoming v0.99 release.

**Comment by ethomson** [comment]
> Anyway, I feel like we should start assembling our own archives. 

I'm not opposed to this but I'm disappointed that there's no way to remove the automatically generated ones.  It feels like if we start assembling our own then it won't be obvious to people which one to use.

I do happen to know someone who works at GitHub, though, so I can inquire about possible solutions.

**Comment by pks-t** [comment]
> I'm not opposed to this but I'm disappointed that there's no way to remove the automatically generated ones. It feels like if we start assembling our own then it won't be obvious to people which one to use.

Definitely true. I've created #5372, which introduces such a new release script, but I've noted the same confusion that results from having multiple archives. We could probably counteract that by choosing proper labels. "Download this here, it's the real thing"

**Comment by ethomson** [comment]
Closing this as stale.
