### ISSUE TITLE
git_checkout_index doesn't respect GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH checkout parameter

### ISSUE THREAD

**Issue by lapfelix** [libgit2/libgit2#5377]
### Reproduction steps
Use `git_checkout_index` to checkout multiple modified files (where we want to revert the changes that were made) with the `GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH` flag enabled in the `checkout_strategy` where the files all have the same prefix as other modified files.

For example, I modified `test9.txt`, `test10.txt`, `test11.txt` and `test12.txt` and I want to discard the changes from `test10.txt` and `test11.txt` by using `git_checkout_index`.

### Expected behavior
Only the files specified in the `git_checkout_options`'s `paths` should be checked out.

In my example, that would be only `test10.txt` and `test11.txt`.

### Actual behavior
All of the files with the same prefix as the two checked out files have their changes discarded too.

In my example, the changes made to `test12.txt` would also be discarded because `test12.txt` has `test1` as prefix.

I created a test case in `checkout/index.c` in a branch in my libgit2 fork that demonstrates the issue: https://github.com/libgit2/libgit2/commit/f37c77b4186714b0a973cab1c0a9dcf8efd19fae

### Version of libgit2 (release number or SHA1)
559751714b23f63ead726e9a773be8b07e3551ae (which is the latest commit on master).
Also reproduced on 15e119375018fba121cf58e02a9f17fe22df0df8 (which dates back from 2017)

### Operating system(s) tested
macOS 10.15.2 (build 19C57)

**Comment by ethomson** [comment]
Thanks for opening the issue, and thanks especially for the helpful test case.  That made it very easy to reproduce this issue and - ultimately - to understand it.

One note - your test was setting checkout pathspecs to `test11.txt` and `test12.txt` but was validating that `test10.txt` and `test11.txt` were the ones checked out.  I modified the test case so that they match.

Should be fixed by https://github.com/libgit2/libgit2/pull/5378 - if you have other test criteria, could you test them against this patch?

**Comment by lapfelix** [comment]
Oh yes you're right about the test12.txt typo 🤦‍♂

I'll test the patch with GitUp, but if my test passes then it should be good!

Thanks a lot for the quick patch!
