### ISSUE TITLE
git_mempack_reset returns int after libgit2 update

### ISSUE THREAD

**Issue by lydza** [libgit2/libgit2#5379]
Hello, all. I ran into an issue while running tests using git2go's master branch with libgit2's master branch. The fix is a quick one-liner, and everything ran smoothly after I made this change.

I tried to create a PR, but I don't have permission. I'm wondering if someone else can make this change.

```
---
 mempack.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/mempack.go b/mempack.go
index 337e67d..26f96be 100644
--- a/mempack.go
+++ b/mempack.go
@@ -6,7 +6,7 @@ package git

 extern int git_mempack_new(git_odb_backend **out);
 extern int git_mempack_dump(git_buf *pack, git_repository *repo, git_odb_backend *backend);
-extern void git_mempack_reset(git_odb_backend *backend);
+extern int git_mempack_reset(git_odb_backend *backend);
 extern void _go_git_odb_backend_free(git_odb_backend *backend);
 */
 import "C"
--
```

### Reproduction steps
`go test`

### Expected behavior
Tests pass.

### Actual behavior
```
Step 18/19 : RUN go test
 ---> Running in 8570ffd11a46
# github.com/libgit2/git2go
./mempack.go:9:13: error: conflicting types for 'git_mempack_reset'
 extern void git_mempack_reset(git_odb_backend *backend);
             ^~~~~~~~~~~~~~~~~
In file included from ./mempack.go:5:0:
/usr/include/git2/sys/mempack.h:83:17: note: previous declaration of 'git_mempack_reset' was here
 GIT_EXTERN(int) git_mempack_reset(git_odb_backend *backend);
                 ^~~~~~~~~~~~~~~~~
FAIL	github.com/libgit2/git2go [build failed]
The command '/bin/sh -c go test' returned a non-zero code: 2
```

### Version of libgit2 (release number or SHA1)
https://github.com/libgit2/libgit2/blob/559751714b23f63ead726e9a773be8b07e3551ae/src/odb_mempack.c#L128

### Operating system(s) tested
`ubuntu:18.04`

**Comment by lydza** [comment]
I'm closing this issue because I posted this in the wrong repo. This change is meant for git2go, not libgit2.

**Comment by pks-t** [comment]
> I'm closing this issue because I posted this in the wrong repo. This change is meant for git2go, not libgit2.

Well, in fact this report is really valuable to us. We considered those changes to be backwards-compatible, as we thought the only consequence of introducing a new return code would be that existing users simply didn't check it. But we definitely forgot about bindings which need to declare such function signatures, such as git2go.

I think I regard bindings as something special as they're extremly tightly coupled with libgit2. It's not nice to break git2go in this case, and there might be others. But at least we shouldn't be breaking any "normal" users of libgit2 with this change. @ethomson: let me know if you judge otherwise.

Anyway, thanks a lot for reporting this, even if unintended!

**Comment by ethomson** [comment]
> I think I regard bindings as something special as they're extremly tightly coupled with libgit2. 

I do, too.  LibGit2Sharp is another example of a place that basically redeclares our prototypes.  That means that it's affected by ABI incompatible changes, even if they're API compatible (at the C level).  Things like this, or moving things in structs.

This is unfortunate, I concede, and we could do better by the bindings.  But I agree that they're extremely special and keep this `void` to `int` change.
