### ISSUE TITLE
httpclient: reads on uninitialized memory

### ISSUE THREAD

**Issue by pks-t** [libgit2/libgit2#5394]
I've been trying to reproduce valgrind errors listed in our [nightly jobs](https://libgit2.visualstudio.com/libgit2/_build/results?buildId=3305&view=logs&j=06c8e146-9583-5f95-f4c5-26a0fe76850a&t=36635f40-af6f-5b1a-9736-6853f5d84f9c) but was unable up to now. I also don't quite get where the uninitialized memory should come from, but yeah. @ethomson, maybe you've got a clue?

**Comment by ethomson** [comment]
I spent a decent amount of time tracking issues like this down - it turns out that OpenSSL will happily `malloc` memory and then keep it uninitialized to use as a source of entropy: https://valgrind.org/docs/memcheck2005.pdf and https://rachelbythebay.com/w/2012/12/14/quiet/

(I heard a rumor that one distribution noticed this uninitialized usage and patched their version to `memset` it to `0`.  Oops.)

I'm not saying that this is definitely the source of the problem, but I was seeing this in the valgrind that we use in CI.  I updated our suppressions file but it's possible that I was not comprehensive.

**Comment by pks-t** [comment]
Huh. Most of these reports come from the HTTP parser or later downtream users of the remote code, and in fact they shouldn't access any bytes at all that we haven't written into the HTTP buffer. So shouldn't it be initialized, as we have effectively written the HTTP output in there?

**Comment by ethomson** [comment]
🤷‍♂ So, I'm not super certain here, but I think that the first error message from valgrind is the critical one:

```
Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
3: ==17380==    at 0x505399D: send (send.c:26)
3: ==17380==    by 0x4FA130: socket_write (socket.c:140)
3: ==17380==    by 0x4F8CBA: git_stream_write (stream.h:55)
3: ==17380==    by 0x4F8A32: bio_write (openssl.c:322)
3: ==17380==    by 0x55DA47B: BIO_write (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
3: ==17380==    by 0x55DD5F0: ??? (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
3: ==17380==    by 0x5281818: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
3: ==17380==    by 0x528B145: ??? (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
3: ==17380==    by 0x4F8E34: openssl_connect (openssl.c:607)
3: ==17380==    by 0x504224: git_stream_connect (stream.h:15)
3: ==17380==    by 0x503FD6: server_connect_stream (httpclient.c:764)
3: ==17380==    by 0x503C14: server_connect (httpclient.c:956)
3: ==17380==    by 0x50244F: http_client_connect (httpclient.c:1014)
3: ==17380==    by 0x501E16: git_http_client_send_request (httpclient.c:1225)
3: ==17380==    by 0x4FD058: http_stream_read (http.c:400)
3: ==17380==    by 0x505F03: git_smart__recv_cb (smart.c:25)
3: ==17380==    by 0x440BA4: gitno_recv (netops.c:20)
3: ==17380==    by 0x4FF1F4: git_smart__store_refs (smart_protocol.c:56)
3: ==17380==    by 0x506932: git_smart__connect (smart.c:255)
```

*And* I think that this is due to the entropy thing that OpenSSL helpfully does.  I think that once it's decided that this memory is uninitialized, then any decisions based on it are tainted themselves.  (They depend on uninitialized memory.)

eg - you can imagine some logic:

```c
int a, b;

if (a == 42)
    b = 6;
else
    b = 7;
```

IOW, `b` now _depends_ on uninitialized memory, but isn't itself uninitialized.  So OpenSSL doing this has confused the whole process, since that uninitialized value fed into a seed which was used for decrypting some data, then we decide what kind of packet we've got, write it to disk, etc.  And so ultimately our _writes to disk_ depend on uninitialized memory.

At least I _think_ that's what it's telling us.  😀

**Comment by pks-t** [comment]
On Fri, Feb 07, 2020 at 06:21:33AM -0800, Edward Thomson wrote:
> At least I _think_ that's what it's telling us.  😀 

Ah, that'd make sense. I think I knew that at some point in time, but
failed to connect the dots this time around. So we'll have to adjust our
suppression file once more. Will see if I find the time to do so
tomorrow.

**Comment by pks-t** [comment]
I've created a branch pks/valgrind-openssl and ran a [build](https://dev.azure.com/libgit2/libgit2/_build/results?buildId=3334&view=logs&j=bfcc9059-3690-5047-368c-49dfe7d9b8d3&t=c586cce9-af87-59ae-cff6-9de2584c83ca) to see if suppressing the uninitialized thing fixes the remaining issues. But in fact that doesn't seem to be the case, there's still loads of conditional jumps depending on uninitialised values.
