### ISSUE TITLE
Tracking: Release 0.99

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#5407]
What do we need to do to land 0.99?

- [X] #5406 
- ~~5391~~ 
- [x] #5372 
- [x] #5291

**Comment by ethomson** [comment]
I'm on the fence for #5391 - it looks ok, but looks can be deceiving. But when I remind myself that this is really a _1.0 prerelease_, and we we're calling it 0.99 to get people to use it, then I'm more okay with it.  Thoughts?

**Comment by pks-t** [comment]
Yup, makes sense.

I'm against #5391, even if we label this a prerelease. It's not fixing any real reported issues, so I don't see the point in getting it in. We can still get it in after v0.99 in preparation of v1.0 as a nice cleanup, though.

With regards to the release script #5372, my plan is to merge this in the same breath with #5291 when doing the release so that I can see if there's any unexpected issues with resulting artifacts and fix them right away.

I'd nominate #5406 as a candidate to get our ARM builds fixed, though. Seems a bit awkward to do a release of code that we weren't able to verify with our own testing infra.

**Comment by ethomson** [comment]
#5406 is in 🚀

**Comment by pks-t** [comment]
Ah, didn't realize that, perfect!

**Comment by ethomson** [comment]
I cut #5391, I agree with your reasoning.

**Comment by ethomson** [comment]
OK, I'm going to let you cut the release, since you're the keeper of the release script - that way you can adapt as needed if anything goes wrong.  🍾

**Comment by pks-t** [comment]
> OK, I'm going to let you cut the release, since you're the keeper of the release script - that way you can adapt as needed if anything goes wrong.

:+1:

Do we still need any amendments to #5291 or is the changelog up to date?

**Comment by ethomson** [comment]
> Do we still need any amendments to #5291 or is the changelog up to date?

Thanks for the reminder - I added a note about your changes to the `FETCH_HEAD`.  Otherwise, the only changes were around CI and a bugfix in code that hadn't-yet-shipped!

**Comment by pks-t** [comment]
Release v0.99 is out now, so I'm closing this issue! :tada:
