### ISSUE TITLE
refdb_backend is light on documentation

### ISSUE THREAD

**Issue by ddevault** [libgit2/libgit2#5457]
`libgit2/sys/refdb_backend.h` has very little documentation. In particular, I'm pretty unsure of how `write` is meant to be used.

**Comment by pks-t** [comment]
Documentation is hard :( I'm going to refrain from creating a pull request myself, cause I'm sure that I've got too much background knowledge I'll assume for granted. Instead, here's a short description and let's work from that. I'd highly appreciate if we can iterate from that to clear up any misunderstandings and uncertainties and from thereon create documentation that's helping:

`write` shall persist a reference such that it can be read at a later point again. Parameters:

- ref: reference to persist. You need to be able to persist both symbolic references as well as direct references pointing to OIDs.
- force: whether to overwrite an existing reference
- who, message: this information shall be used to generate reflog entries
- old, old_target: this information is used for both the reflog entries as well as for atomicity. If `force` is not set, you need to make sure a pre-existing ref points to `old`/`old_target` or otherwise return an error.

**Comment by ddevault** [comment]
What do I put in for `old`/`old_target` to create new references?

**Comment by pks-t** [comment]
On Mon, Mar 23, 2020 at 05:35:09AM -0700, Drew DeVault wrote:
> What do I put in for `old`/`old_target` to create new references?

`old_target` should be set to `NULL`, `old` should be the zero OID (all
zeroes).

**Comment by pks-t** [comment]
On Mon, Mar 23, 2020 at 07:27:26AM -0700, Patrick Steinhardt wrote:
> On Mon, Mar 23, 2020 at 05:35:09AM -0700, Drew DeVault wrote:
> > What do I put in for `old`/`old_target` to create new references?
> 
> `old_target` should be set to `NULL`, `old` should be the zero OID (all
> zeroes).

Wait, this isn't actualyl true. It shoulde be `NULL` for both. Too much
fiddling with git-update-refs(1) lately.

**Comment by ddevault** [comment]
Got it. Thanks!
