### ISSUE TITLE
Fetching the remote HEAD (aka default branch)

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#5646]
Using `git clone` automatically sets `refs/remotes/origin/HEAD` to be the remote default branch, however libgit2 [does not populate this](https://libgit2.slack.com/archives/C1BS8MML7/p1594212366020600). Therefore we don't know what is the remote default branch, and it does not get updated when it changes.

It would be great to have a way to fetch the `origin/HEAD` symref, the same as `git remote set-head origin -a` which according to the [manual page](https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emset-headem) does this:

> With -a or --auto, the remote is queried to determine its HEAD, then the symbolic-ref refs/remotes/origin/HEAD is set to the same branch. e.g., if the remote HEAD is pointed at next, "git remote set-head origin -a" will set the symbolic-ref refs/remotes/origin/HEAD to refs/remotes/origin/next. 

It would make sense if a call to [git_remote_default_branch](https://libgit2.org/libgit2/#HEAD/group/remote/git_remote_default_branch) would update the  local `refs/remotes/<name>/HEAD` value.

**Comment by ethomson** [comment]
> Using git clone automatically sets refs/remotes/origin/HEAD to be the remote default branch, however libgit2 does not populate this.

Yes, that's disappointing and a bug.  Sorry about that.

(Fortunately, it should be a simple fix.  Is this a place where you might want to contribute a pull request?)

> Therefore we don't know what is the remote default branch, and it does not get updated when it changes.

This isn't actually, something that's done at fetch time, it's something that's done at clone time.  If you change your remote's default branch, `git fetch` itself will never update the remote symref.  You can see this yourself by cloning a repository (with `git clone`), changing the default branch and then running `git fetch`.

That's because the remote `HEAD` is not a real reference, it's just data communicated in a sideband channel that indicates what the default branch should be set to after the clone has finished.  It's not part of the real refs negotiation, and even this is (relatively) new.  Older versions of git have to derive the default branch and it's not guaranteed to be correct.

> It would make sense if a call to git_remote_default_branch would actually update the refs/remotes/<name>/HEAD value.

Maybe?  I'm not sure that I agree.  I think that this call should be largely read-only.  Changing `refs/remotes/whatever/HEAD` is just a weird thing to do...  if you - as an application author - want to do it, you're certainly welcome to.  But I think that making a call to `git_remote_default_branch` maybe shouldn't do it.

---

I feel like I'm not yet sure what you're after here.  The `git_clone` issue is indeed a bug, but it sounds like it won't actually solve you're problem where you're trying to understand what's changed on the remote's `HEAD` given an existing repository...  ?

But there _is_ an API for that, which you point out.  It sounds like you're interested in reading it off disk though?  Why not just `git_remote_default_branch` and then do the update as a second call?  I guess I'm not opposed to having some new API that will do both of these things for you but it feels like a rather uncommon use case (and one that's not difficult to solve with the status quo) to have a new piece of API for.

**Comment by jeroen** [comment]
> I feel like I'm not yet sure what you're after here. The git_clone issue is indeed a bug, but it sounds like it won't actually solve you're problem where you're trying to understand what's changed on the remote's HEAD given an existing repository... ?

The most important thing is indeed to fix the bug in `git_clone()`. However many users have repositories on disk that were cloned with previous versions of libgit2 and are missing `refs/remotes/origin/HEAD`, so it would be nice if I can update the local symref for existing repos that are missing this. 

And yes, sometimes remotes change the default branch, in case we want to update the local `origin/HEAD` ref.


> Why not just git_remote_default_branch and then do the update as a second call

Could you give an example how to implement this update step? Part of the problem is my lack of understanding about how to manipulate a symref; I didn't know this was possible. If this can already be done with the current API, there is no need to add a new function, and it would be better to add this in the form of an example or test case.

**Comment by jeroen** [comment]
Thanks! Your example is helpful, but not completely correct I think, because we need to to translate the ref into a remote ref.

For example, `git_remote_default_branch` may return `refs/heads/main` which should be `refs/remotes/origin/main` when populating `refs/remotes/origin/HEAD`.

Is there an elegant way in libgit2 to convert a branch name from a local into a remote namespace, or should we just use string manipulation for this?

**Comment by jeroen** [comment]
This is what I'm doing now in my bindings (manually converting the ref): https://github.com/r-lib/gert/blob/0439cf53836f3305a67b5e48ab60a330cd9285e4/src/clone.c#L426-L453

**Comment by ethomson** [comment]
@jeroen I think that you want `git_branch_upstream`.  A simple translation will work when the refspec is predicable, like the default, but a refspec could be almost anything.  For example, a refspec to pull down pull requests from GitHub would fail:

```
    fetch = +refs/pull/*/head:refs/remotes/pr/*
```

**Comment by jeroen** [comment]
Thanks! Going to test this right away.

**Comment by jeroen** [comment]
OK it works, thanks so much! I did get confused earlier because the master branch shows version `1.0.0` in `git2/version.h` so I thought I was using an older version.

Will this fix be ported to the `maint/v1.0` branch, or will the master branch become the next release?

Sorry for be impatient, but because GitHub has changed their default master branch to "main", we have a lot of users running into this. Thanks again for the prompt fix!

**Comment by ethomson** [comment]
I'll stage v1.1 that includes this - see #5660 5660

**Comment by A-Ovchinnikov-mx** [comment]
@ethomson Still doesn't work for me with libgit2 v1.1.0 and LibGit2Sharp on Windows - there is no `refs/remotes/origin/HEAD` file. Is there some special configuration on `git_clone` that should be done for this to work?

**Comment by A-Ovchinnikov-mx** [comment]
It appears this still doesn't work with the latest libgit2 when `checkout_branch` is set in `git_clone_options` being passed to `git_clone`. The `refs/remotes/origin/HEAD` file is not being created. Checked it using git2-rs.

I will prepare a repro and open a new issue.
