### ISSUE TITLE
Regression: libgit2 crashes on Windows arm64

### ISSUE THREAD

**Issue by Alovchin91** [libgit2/libgit2#5745]
### Reproduction steps

1. Use [git2-rs](https://github.com/rust-lang/git2-rs) v0.13.13 in a Rust project. This version references libgit2-sys v0.12.15 which includes the merge commit that breaks the functionality.
2. Try to clone the repository using Rust's API `Repository::clone` which calls `git_clone` from libgit2.

### Expected behavior

The repository is cloned successfully.

### Actual behavior

```
error: process didn't exit successfully: `target\debug\git2-test.exe clone https://github.com/rust-lang/git2-rs.git C:\Projects\my-git2-rs-2` (exit code: 0x80000002)
```

### Version of libgit2 (release number or SHA1)

5699ef81942538bc24df5285876e5830570b65f3

### Operating system(s) tested

Windows 10 arm64

### Additional information

Updating libgit2 submodule of git2-rs commit by commit I found out that the following PR is the culprit:

https://github.com/libgit2/libgit2/pull/5595
https://github.com/libgit2/libgit2/commit/5699ef81942538bc24df5285876e5830570b65f3

I can't say I understand very well what's going on there but I'll do my best to at least find the exact place where it crashes.

If you need to use my device (Surface Pro X) to debug, please let me know.

**Comment by ethomson** [comment]
😬  That's disappointing.  Let me see if I can get one of my raspberry pis to run Windows arm64...

**Comment by ethomson** [comment]
Hmm, this looks like there may be an alignment problem https://github.com/libgit2/libgit2/commit/5699ef81942538bc24df5285876e5830570b65f3#diff-ec35ecc1ce27df7c8febf4f8c440c329eabb48fa92d2cfb73bd18689709e4452R114

🤔

**Comment by Alovchin91** [comment]
@ethomson Thanks for such a quick reply! Shall you have a patch to test, let me know and I can do that today.

**Comment by ethomson** [comment]
@Alovchin91 I opened #5746 with a possible fix.  I haven't tested it on Windows on ARM64 _but_ I could trivially reproduce _an_ alignment problem on Sparc64.  This fixes that issue.  I hope that you're seeing the _same_ issue.  🤞 

If not, I'll need to figure out how to get a WoA system working.

**Comment by Alovchin91** [comment]
@ethomson Thanks, I'm gonna check it now! 👍 

I also managed to reproduce the issue on WSL 2 on the same Surface Pro X: https://github.com/rust-lang/git2-rs/issues/645#issuecomment-748635273

So maybe you don't even need a WoA system but just Linux ARM64.

**Comment by ethomson** [comment]
We build on Linux arm64 as part of our CI - I think that it may an LP64/LLP64 difference.

**Comment by lhchavez** [comment]
> We build on Linux arm64 as part of our CI - I think that it may an LP64/LLP64 difference.

is it running on real hardware? from [the build logs](https://github.com/libgit2/libgit2/runs/1585151224?check_suite_focus=true)  it _seems_ to be using QEMU, and QEMU [does not emulate unaligned memory access exceptions](https://stackoverflow.com/questions/51520635/how-to-emulate-arm-unaligned-memory-access-exceptions). so it seems like the pointer size is not at fault here (just unaligned access) and the CI cannot catch it :(

(maybe if we were to add a test that tries to cache the value of `GIT_FSYNCOBJECTFILES_DEFAULT` and later try to access the submodule cache, we might have seen this due to a different-sized write, although it might be kinda difficult to anticipate this interaction. regardless #5746 will take care of both the alignment and the sized write \o/).

**Comment by ethomson** [comment]
> is it running on real hardware? from the build logs it seems to be using QEMU, and QEMU does not emulate unaligned memory access exceptions. so it seems like the pointer size is not at fault here (just unaligned access) and the CI cannot catch it :(

Aha.

Unfortunately, GitHub Actions doesn't have arm hardware available, so you're right that it's running in qemu.  I hadn't considered that emulation may be the problem here.

Amusingly, I had been running builds on physical Linux arm32/arm64 a few weeks ago as a test, but the emulation was so much simpler that I gave up on it.  🙃
