### ISSUE TITLE
"Assertion failed path && path_out" in src/path.c while trying to rename reference on custom refdb repo without commonpath set

### ISSUE THREAD

**Issue by Vesemir** [libgit2/libgit2#5851]
Hello

### Reproduction steps
1. Try to use a custom backend implementing refdb without filesystem e.g.

```c
git_odb_backend *odb_backend = NULL;
git_refdb_backend *refdb_backend = NULL;
git_odb *odb = NULL;
git_refdb *refdb = NULL;
git_repository *repository = NULL;
git_init_custom_backends(&odb_backend, &refdb_backend, path); // magic
git_odb_new(&odb);
git_odb_add_backend(odb, odb_backend, 0);
git_repository_wrap_odb(&repository, odb);
git_refdb_new(&refdb, repository);
git_refdb_set_backend(refdb, refdb_backend);
git_repository_set_refdb(repository, refdb);
```

2. Implement `rename` method of `struct git_refdb_backend` for refdb_backend as required in documentation.
3. Try to rename a reference (deleting and recreating a reference pointing to the same oid works fine).

### Expected behavior
Reference gets renamed and all is fine.

### Actual behavior
Reference gets renamed (repository state is valid on subsequent launch), then 
assertion error happens on 
git_reference_rename -> git_repository_foreach_worktree -> git_repository_open(&worktree_repo, repo->commondir) -> git_repository_open_ext(repo_out, path, GIT_REPOSITORY_OPEN_NO_SEARCH, NULL) -> ... -> git_path_prettify()
execution path because `commondir` member is unset on custom repository.

### Version of libgit2 (release number or SHA1)
cabfa3b30cfae24ec6d7d75c5cf052e052cbf131

the offending call seems to be added on https://github.com/libgit2/libgit2/commit/7216b048f5bd3cdad6416295d128f0173cb74533
despite the comment about supporting non-filesystem-based refdbs.

### Operating system(s) tested
Windows 10

Potentially similar issue seems to be fixed at https://github.com/libgit2/libgit2/pull/4967, but it seems that `git_repository_set_path` function was never added and there is no valid way to set it?
Is there any way to circumvent this issue?

Any help appreciated.

**Comment by kcsaul** [comment]
Following attempt to update to the latest version, I've encountered the same assertion with the use of a custom odb/refdb, but in the context of cloning rather than renaming references.  In my scenario, clone is calling git_branch_checked_out indirectly as part of deciding whether head references can be updated.  Prior versions of this would use git_repository_is_bare to check before git_repository_foreach_head was used.  Latest version doesn't check whether it's a bare repository before calling git_repository_foreach_worktree, which ultimately fails because repo->commondir is null.

To support the use of custom odb/refdb with no filesystem, I wonder if the bugs referred to can be fixed by simply adjusting git_repository_foreach_worktree to return 0 when repo->commondir is null? (as there's neither the common or linked worktrees to iterate over).

**Comment by kcsaul** [comment]
To support the use of custom odb/refdb with no filesystem, I wonder if the bugs referred to can be fixed by changing git_repository_foreach_worktree to use the git_repository supplied rather than attempting to re-open repo->commondir, and adjust git_worktree_list to return an empty list when repo->commondir is null.
