### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by ericonr** [libgit2/libgit2#5902]
Hi!

For distribution purposes, we appreciate having proper upstream releases to package, but since the 1.1.0 release, there have been some important bug fixes (like #5745), which are update blockers unless we patch the package locally. To avoid duplicating the labor of everyone procuring patches themselves (and tracking down bugs), it would be nice to have a bug fix release for libgit2.

As a side note, I see f10c887533fc006768cb39e63914bed111584c25 was the commit to make the new release, was there an actual ABI break? Rust projects are unfortunately very specific about what `libgit2` ABI they support (given by the soname), so it would be nice to avoid changing the soname when there haven't been actual ABI changes.

Thanks!

**Comment by ethomson** [comment]
Hi @ericonr!

> For distribution purposes, we appreciate having proper upstream releases to package, but since the 1.1.0 release, there have been some important bug fixes (like #5745), which are update blockers unless we patch the package locally. To avoid duplicating the labor of everyone procuring patches themselves (and tracking down bugs), it would be nice to have a bug fix release for libgit2.

I've been wanting to do a 1.2.0 🔜 - there are a few things to review and merge that I've been waiting for, and I've been busy at home with a new 👶.

I don't mind doing a 1.1.1 in the meantime.  What other bug fixes would you want to see in that release?

I notice that rust libgit2-sys has just updated to a newer commit on the main branch.  This certainly seems like a reasonable approach - we go to great pains to keep main releasable and stable, and this is the approach I take instead of trying to maintain my own patches.  But of course I understand wanting to have a proper official release.

> As a side note, I see f10c887 was the commit to make the new release, was there an actual ABI break? Rust projects are unfortunately very specific about what libgit2 ABI they support (given by the soname), so it would be nice to avoid changing the soname when there haven't been actual ABI changes.

I'm (happily) surprised but you're right, there were no abi changes between 1.0.0...1.1.0.  Our release scripts always bump the SOVERSION for major/minor releases.  We keep API compatibility for minor and teeny releases but ABI only for teeny releases.

(This is probably something that we should spend some effort to fix, but that summarizes the status quo, and have had few complaints.  Knowing that this is a friction point for you is helpful for prioritization.)

**Comment by ericonr** [comment]
> I've been wanting to do a 1.2.0 soon - there are a few things to review and merge that I've been waiting for, and I've been busy at home with a new baby.

Hope it's being fun, enjoy :)

> I don't mind doing a 1.1.1 in the meantime. What other bug fixes would you want to see in that release?

I traipsed through the issues in this repo, couldn't find anything else as important. I would appreciate a 1.1.1 release.

> This certainly seems like a reasonable approach - we go to great pains to keep main releasable and stable, and this is the approach I take instead of trying to maintain my own patches. But of course I understand wanting to have a proper official release.

From a distro standpoint we want to be able to delegate the "update point" to upstreams instead of having to track changes ourselves. If we had to choose the "update point" for every package, we'd quickly go mad :)

Releases let us know that not only things are tested, but that at this point the package is likely to contain new things we are interested in, and it's a single point in time where we check all the new things in bulk instead of having to wonder at every commit if we should update our `libgit2` package. In keeping with that, you could get a nice cozy place in packagers' hearts by making small bug fixes releases for things like #5745; most distros have scripts to warn them about releases, and they can just grab the new one instead of having to figure out what patch fixes their problems.

>Our release scripts always bump the SOVERSION for major/minor releases. We keep API compatibility for minor and teeny releases but ABI only for teeny releases.

Uncoupling the SOVERSION from the package's version can be a great help in avoiding rebuilds (this is mostly only relevant for rolling distros), but it also manifests in dealing with rust's `libgit2-sys`. Anyhow, I also understand that properly tracking ABI can be a big pain and it's definitely a lot simpler to allow yourselves to break it for minor releases, so I would put this item under "wishlist" category rather than something urgent :)

**Comment by pde-cds** [comment]
#5857 would be nice for a 1.1.1 or 1.2.0

**Comment by ethomson** [comment]
> #5857 would be nice for a 1.1.1 or 1.2.0

That will land in v1.2.0 - in fact, it will be the most important part of v1.2.0, in my opinion.  But it's much too massive a change to bring into a point release.

I've opened #5921 for a v1.1.1 in the meantime.

**Comment by ethomson** [comment]
libgit2 v1.1.1 is released!  https://github.com/libgit2/libgit2/releases/tag/v1.1.1

**Comment by ericonr** [comment]
Much appreciated :)
