### ISSUE TITLE
git_remote_fetch returns -1 for token-based clones

### ISSUE THREAD

**Issue by mikasoukhov** [libgit2/libgit2#5967]
The issue related to that one https://github.com/libgit2/libgit2sharp/issues/1898

As I've investigated, the following code for token-based URLs returns -1

### Reproduction steps

int res = NativeMethods.git_remote_fetch(remote, ref array.Array, fetchOptions, logMessage);
Ensure.ZeroResult(res);

### Expected behavior

res == 0

### Actual behavior

res == -1

### Version of libgit2 (release number or SHA1)

0.28.0 (git2-6777db8.dll)

### Operating system(s) tested

Windows 10 x64

**Comment by ethomson** [comment]
What's a "token based url"?  Do you have repro steps against libgit2 (not LibGit2Sharp)?

**Comment by mikasoukhov** [comment]
Token-based urls - https://stackoverflow.com/a/66156992

Do you have an example for git_remote_fetch? Can try directly.

**Comment by mikasoukhov** [comment]
DIrect call of libgit has the same issue

```
var res = git_repository_open(out var repo, args[0]);
Console.WriteLine(res);
res = git_remote_lookup(out var remote, repo, "origin");
 Console.WriteLine(res);
res = git_remote_fetch(remote, null, null, null);
Console.WriteLine(res);
```

Output as 

```
0
0
-1
```

Can create test repo with an access token url (if need).

**Comment by mikasoukhov** [comment]
Checked on https://github.com/libgit2/libgit2/releases/tag/v1.1.1 - same behavior. Seems from some period libgit2 stopped support access tokens.

**Comment by ethomson** [comment]
This looks like you're still using LibGit2Sharp:

```
var res = git_repository_open(out var repo, args[0]);
Console.WriteLine(res);
```

LibGit2Sharp has a custom https transport layer, which may be the culprit here.

libgit2 tests clones with username and password inside a URL: https://github.com/libgit2/libgit2/blob/main/tests/online/clone.c#L430 - however the other variable is that we're testing clone, not loading a remote on-disk and doing a fetch.

My questions would be:

1. Does `git_clone` work with a URL that includes credentials using LibGit2Sharp like you were doing above?  If not, this suggests that the problem is in LibGit2Sharp and the custom https transport.
2. What does that `remote` look like that you're loading?  Can you inspect the native memory and see the URL that's being loaded?

**Comment by mikasoukhov** [comment]
1) No, I copied DLL import code into my project and leaved only necessary code. It is pure C# without any dependencies. Can share if need.

2) The thing is token based urls do not contains any credentials (except them self) and do not required any login and password. Maybe I can create some url for you and you need for reproduce on your environment?

**Comment by ethomson** [comment]
> No, I copied DLL import code into my project and leaved only necessary code. It is pure C# without any dependencies. Can share if need.

Okay, good to know.

> The thing is token based urls do not contains any credentials (except them self) and do not required any login and password. Maybe I can create some url for you and you need for reproduce on your environment?

Right, sorry - to be clear, I was talking about the token as the username/password.  From an http perspective, that's just a username and password even though it's a token, not your actual username and password.

I suspect that we're only handling username/password in a URL when both are specified - so I would expect `https://user:token@github.com/name/repo` to work.  But I suspect that we're looking at `https://token@github.com/name/repo` and assuming that the creds are incomplete.

**Comment by mikasoukhov** [comment]
The url [https://user:token@github.com/name/repo](https://user:token@github.com/name/repo) is exactly what I try to use.

Did you try fetch remote with url like that?

**Comment by ethomson** [comment]
Not fetch, only clone.

**Comment by mikasoukhov** [comment]
Will you check it?

**Comment by carlosmn** [comment]
A clone and a fetch are the the same network-wise. There is no specific token support anywhere in git or curl or anything else. These tokens for e.g. GitHub are what you use instead of a password. Your comment

>The thing is token based urls do not contains any credentials (except them self) and do not required any login and password. Maybe I can create some url for you and you need for reproduce on your environment?

suggests you're misunderstanding what these tokens are.

Have you tried specifying your username and token like specified in the documentation, e.g. at the end of https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token ?

**Comment by mikasoukhov** [comment]
Here is the example (I've already posted it above) - https://stackoverflow.com/a/66156992

**Comment by mikasoukhov** [comment]
I think you can just try to run the test and you will get the error.

**Comment by ethomson** [comment]
> The url https://user:token@github.com/name/repo is exactly what I try to use.

Everything you're pointing to is documentation about presenting the token as a username with no password - in other words `https://token@github.com/name/repo` instead of `https://user:token@github.com/name/repo`.

Like I said, we have many tests around `https://user:pass@host/path`.  And yes, like I said, I tested this.

And I suspect that the problem is that we're not parsing `https://something@host/path` as a complete authentication that we should present.  In other words, we're not sending an empty password when it's omitted from the userinfo portion of the URI.  If so, this is a bug that we should fix, but in the meantime, you can workaround it by specifying `user:token` as the userinfo instead of just `token`.

Is this _not_ what you're seeing?  What does your remote configuration look like?

**Comment by mikasoukhov** [comment]
I use that type of URL

[](https://user:token@github.com/name/repo)

Only that and no any other formats.

**Comment by ethomson** [comment]
What does your remote configuration look like?

**Comment by ethomson** [comment]
Yes.

**Comment by mikasoukhov** [comment]
Possible to share (upload) a new test code? To reproduce on my environment.

**Comment by ethomson** [comment]
Like I said, we have tests for this.  Here's the extraction of one of them:

```
git_repository_init(&repo, "./fetch", 0);
git_remote_create(&remote, repo, "test", "https://libgit3:libgit3@bitbucket.org/libgit2/testgitrepository.git");
git_remote_fetch(remote, NULL, NULL, NULL);
```

**Comment by mikasoukhov** [comment]
Let me try to check everything.

**Comment by ethomson** [comment]
Thanks - let me know what you discover.  It's clear that `https://token@host` is not supported, but if there are other problems, I cannot reproduce them yet.

**Comment by mikasoukhov** [comment]
My bad, my bad.

I've put the code as a unit test into the same proj as LibGit2Sharp. For some reason, the last one does some global changes that were affected on any other test.

I've removed LibGit2Shart tests and it is working fine now.

Also, I've removed the custom HTTP/HTTPS transport layer and my and original test now works as well. Don't know the reason of that customization but I believe it is wrong.

**Comment by ethomson** [comment]
> I've put the code as a unit test into the same proj as LibGit2Sharp. For some reason, the last one does some global changes that were affected on any other test.

Excellent, that definitely makes a lot of sense.

> Also, I've removed the custom HTTP/HTTPS transport layer and my and original test now works as well. Don't know the reason of that customization but I believe it is wrong.

Yeah, this one was my fault.  Distributing a `libgit2.so` on Linux that's linked against openssl is very problematic.  I added a managed HTTPS transport in LibGit2Sharp to avoid this.

This introduced a whole different set of problems.  We should have `dlopen`ed OpenSSL instead.  Future improvement.

**Comment by mikasoukhov** [comment]
1. NativeBinaries updated to 1.1.1. Some pull requests (can explain what exactly if need) contain a workable solution - don't know why no one wanna merge it.
2. Determines OS at the runtime - https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=net-5.0
3. .netcodeapp2.1 is useless to support - .netstandard2.0 cover it.

I've seen in your comment some commented line - git_openssl_set_locking It works without that function call. And frankly speaking that function (like lock SSL for a whole app) looks not like the best solution at all.

C# wrapper works like a charm. That logic can works for many years. I've reviewed the code. Not ideal but nothing serious that can cause problems. I've seen your call in contributors. Looks ok for me - but should be started from NativeBinaries. Who can merge it without owner's permission.
