### ISSUE TITLE
revwalk find childs of root reference

### ISSUE THREAD

**Issue by albfan** [libgit2/libgit2#6283]
### Reproduction steps

Using mesa repo to see history for tag `mesa_texman_20060210` (a6f78d4eee85ccda42384ebfcc956bc8e6444c36) it tries to find parents for commit e3312644cbc which is not in any ancestor of that tag but is a child.

```
git clone https://gitlab.freedesktop.org/mesa/mesa
cd mesa
$ /path/to/libgit2/build/examples/lg2 log --git-dir . a6f78d4eee85ccda42384ebfcc956bc8e6444c36 | head 
a6f78d4eee85ccda42384ebfcc956bc8e6444c36 | head
commit e3312644cbc8a74c262e35672547d5cce83fd1bc
Author: Jason Ekstrand <jason.ekstrand@intel.com>
Date:   Wed Mar 30 20:31:25 2016 -0700

    anv/blit2d: Add support for W-tiled destinations
    
    Reviewed-by: Nanley Chery <nanley.g.chery@intel.com>
    Reviewed-by: Chad Versace <chad.versace@intel.com>

commit 0a6842c1bd18e1b2b7ef5e969b9f5df891604815
```

### Expected behavior

revwalk to list only ancestors of root reference.

### Actual behavior

For some repositories it list unexpected commits.

### Version of libgit2 (release number or SHA1)

tested from current main

### Operating system(s) tested

fedora

first reported on https://gitlab.gnome.org/GNOME/gitg/-/issues/374

**Comment by ethomson** [comment]
🤔  I'm a bit puzzled.

So one problem here is that some of our example code - this in particular - could use some love. Our examples try overly hard to emulate git and end up... not being great examples of how to invoke our APIs. It looks like there are some bugs with how this code is taking revspecs as arguments. 😩

```
/path/to/libgit2/build/examples/lg2 log --git-dir . a6f78d4eee85ccda42384ebfcc956bc8e6444c36
```

☝️ looks like it ends up ignoring the id on the command line, and only pushes `HEAD` on the revwalk. I haven't debugged this to know why, but it behaves differently from:

```
/path/to/libgit2/build/examples/lg2 log a6f78d4eee85ccda42384ebfcc956bc8e6444c36
```

☝️ is buggy in a different way. It looks at the return value from `add_revision` as if it were a `bool`, but it's not, it returns `0` on success and `-1` on error. It interprets the successful addition of `0`. 

It looks like it's failing because the repo was not opened (perhaps that's why you're using the `--git-dir .` in the initial example?)

I'm actually rather stumped about how to get the example to reproduce this (unless `e3312644cbc8a74c262e35672547d5cce83fd1bc ` was at HEAD, which it's not unless your reproducer has elided a step). In fact, I'm pretty frustrated with the whole example, but I'm going to chalk that up as a problem for later, once I've figured out what's going on with revwalk.

---

Using this as a reproducer:

```c
#include <git2.h>
#include <stdio.h>

#define do(x) if ((x) < 0) { fprintf(stderr, "failed: %s\n", git_error_last()->message); exit(1); }

int main(int argc, char **argv)
{
	git_repository *repo;
	git_revwalk *revwalk;
	git_oid id;
	int error;

	do(git_libgit2_init());
	do(git_repository_open(&repo, "/Users/ethomson/Temp/mesa"));

	do(git_oid_fromstr(&id, "a6f78d4eee85ccda42384ebfcc956bc8e6444c36"));

	do(git_revwalk_new(&revwalk, repo));
	do(git_revwalk_push(revwalk, &id));

	while ((error = git_revwalk_next(&id, revwalk)) == 0) {
		printf("%s\n", git_oid_tostr_s(&id));
	}

	if (error != GIT_ITEROVER)
		fprintf(stderr, "failed: %s\n", git_error_last()->message);
}
```

I do _not_ see `e3312644cbc8a74c262e35672547d5cce83fd1bc` anywhere in the output (in fact, my output emulates the `git log` output for that.

Can you reproduce this with the code that I posted? Can you step through or add some debugging output to instrument precisely what you're pushing and / or hiding on to the revwalk? Is it possible that peeling the tag is the problem? What is your `HEAD` at when you run this example? 🤔

**Comment by albfan** [comment]
I tried to debug a bit to understand what's happening, but fail so  I tried this hacky way.

We basically follow the examples to implement revwalk so I will review that and check our code in https://gitlab.gnome.org/GNOME/libgit2-glib/-/blob/master/libgit2-glib/ggit-revision-walker.c

I tried:

    /path/to/libgit2/build/examples/lg2 log a6f78d4eee85ccda42384ebfcc956bc8e6444c36

it takes a while to run and the do not output anything.

I reworked your example like:

```
#include <git2.h>
#include <stdio.h>

#define do(x) if ((x) < 0) { fprintf(stderr, "failed: %s\n", git_error_last()->message); exit(1); }

int main(int argc, char **argv)
{
	git_repository *repo;
	git_revwalk *revwalk;
	git_oid id;
	int error;

	do(git_libgit2_init());
	do(git_repository_open(&repo, "."));

	do(git_oid_fromstr(&id, argv[1]));

	do(git_revwalk_new(&revwalk, repo));
	do(git_revwalk_push(revwalk, &id));

	while ((error = git_revwalk_next(&id, revwalk)) == 0) {
		printf("%s\n", git_oid_tostr_s(&id));
	}

	if (error != GIT_ITEROVER)
		fprintf(stderr, "failed: %s\n", git_error_last()->message);
}
```

added a meson config:

```
project('git2-log', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

executable('git2-log',
           'main.c',
           dependencies: [dependency('libgit2')],
           install : true)
```
and it runs as expected:

```
[alberto@fedora mesa]$ ../git2-log/build/git2-log a6f78d4eee85ccda42384ebfcc956bc8e6444c36 | head
a6f78d4eee85ccda42384ebfcc956bc8e6444c36
ae695e3566a0fd4e55e813bc6911a5c53bc57580
c82c3335e1ff25777f9275eff0db292af4f1c89b
f8246f504b0ec1e112951980d339908992abc6bb
499458bcdb3879c5a7088be14e0fd75ea29d0be1
37a53fd6a0dd7f74bccbdce2a90120898952f30f
5ec38fb2ea68e1bedbf85101843b92eacbd1af66
11c0215bf8afcb8c578f0b5eb850d3ef28c619b5
6a13b6c346402c4c3fe79157ae8b2f7870b7372d
a103097ee5974d8b05490bbd673fbfff2990679a
```

So whatever is wrong in the example is wrong for us too, if you can tweak the example I can follow that and fix our wrapper.

Thanks for looking into this!

**Comment by albfan** [comment]
I found why I need `--git-dir` for lg2 example. So we can remove that from equation

**Comment by albfan** [comment]
Looks to me when repo used to create walker is different from repo to lookup a commit from an oid, this strange commits are retrieved.

Probably we are doing something like that on gitg.

**Comment by albfan** [comment]
So I get what's going on here.

without this fix https://github.com/libgit2/libgit2/pull/6359/commits/6b86332465b8740b8845043acf377f7d383f6014

$ /home/alberto/projects/c/libgit2/build/examples/lg2 log --git-dir . a6f78d4eee85ccda42384ebfcc956bc8e6444c36 | head

start parsing `--git-dir` but breaking anyway, so lg2 log acts like if no rev is set, then it uses HEAD which here is set as the commit e3312644cbc8a74c262e35672547d5cce83fd1bc

with that fix all works as expected. So #6359 is the fix for this example

**Comment by albfan** [comment]
the only thing related with gitg issue https://gitlab.gnome.org/GNOME/gitg/-/issues/374, is it is listing HEAD commit so we need to fix that (probably hide other refs when we try to see history), so closing this and leaving the PR to merge
