### ISSUE TITLE
Donating Funds to Libgit2

### ISSUE THREAD

**Issue by Lfada** [libgit2/libgit2#6653]
Hi Libgit 2, I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

[[Radicle](http://www.radicle.xyz/)](http://www.radicle.xyz) has been using https://github.com/libgit2/libgit2. It's in fact one of our most critical dependencies!

All Radicle’s core-contributors really appreciate the work you all do and we want to make sure that you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [[Drips](https://www.drips.network/)](https://www.drips.network/) (an initiative that is coming out of our organization for funding FOSS).

Who can I talk to about it?

cc:@ethomson @carlosmn @pks-t

**Comment by Lfada** [comment]
Hi @ethomson @carlosmn @pks-t  (and all the other maintainers)  just wanted to follow up on this as I haven't gotten a response. 

Is there anyone from Libgit2 that I can discuss this with? 

Thank you,
Lucas

**Comment by ethomson** [comment]
Hi @Lfada 👋 

Appreciate the kindness. I'm a fan of [Radicle](http://www.radicle.xyz/)](http://www.radicle.xyz/) as well, I happened to see Alexis' talk at FOSDEM in 2020.

Here's the rub: we don't have a proper framework set up for this at the moment, although we should. (Especially since at the moment, we _do_ have expenses, and that's coming out of my bank account right now. Yikes!)

In any case, I'm the person to discuss with. If you'd like to drop me a line, I'm `ethomson@edwardthomson.com` and we can try to figure out the best way to move forward.

**Comment by Lfada** [comment]
hi @ethomson, wanted to follow up on this. 

Happy to bring some of our more technical people into a conversation to answer any questions you might have. 

We also have resources that can help you pick the right wallet for your needs. 

But most importantly, what's blocking or stopping you from starting the claim process?

**Comment by ethomson** [comment]
We are very thankful for the generous donation from the [Radicle](http://www.radicle.xyz/)](http://www.radicle.xyz/) project; and we're very thankful for the support by [Drips](https://www.drips.network/)]([https://www.drips.network/) (an](https://www.drips.network/) and [Open Collective](https://opencollective.com).

We're planning a bigger announcement with the next version 🔜  - in the meantime, I'm closing this!
