### ISSUE TITLE
git_error_set_str removed from public API in 1.8.0?

### ISSUE THREAD

**Issue by wshanks** [libgit2/libgit2#6776]
### Reproduction steps

Compile a program using `#include <git2.h>` and `git_error_set_str`.

### Expected behavior

Program compiles successfully.

### Actual behavior

`error: ‘git_error_set_str’ was not declared in this scope; did you mean ‘giterr_set_str’?`

### Version of libgit2 (release number or SHA1)

1.8.0

### Operating system(s) tested

Linux. I am not sure of the exact version. This was a flathub buildbot ([log](https://buildbot.flathub.org/#/builders/7/builds/13377)) (I think it uses CentOS).

### Context

In https://github.com/libgit2/libgit2/pull/6625, `git_error_set_str` (along with some other functions) was moved from `include/git2/errors.h` to `include/git2/sys/errors.h` which is not included in the main `include/git2.h`. I noticed this while trying to rebuild [KLayout](https://github.com/KLayout/klayout) with libgit2 1.8.0 which failed [here](https://github.com/flathub/de.klayout.KLayout/pull/69) (for reference, KLayout uses `git_error_set_str` [here](https://github.com/KLayout/klayout/blob/master/src/tl/tl/tlGit.cc)). I don't see `git_error_set_str` in the public API listed [here](https://libgit2.org/libgit2/#HEAD) but also don't see the removal mentioned in the 1.8.0 release notes, so I wondered if this was an oversight?

Sorry if I missed something obvious. I maintain the KLayout flatpak, but I am not a C++ developer.

**Comment by ethomson** [comment]
Sorry - I should have called that out more explicitly in the release notes. I'll update them. The move into the `sys` api represents that most users do not (probably _should not_) be using the api. But maybe my expectation was wrong here.

In any case, you can fix this by:

```
#include <git2.h>
#include <git2/sys/errors.h>
```

I'll have another think about whether moving this was really the smart thing to do and whether it should move back out of the systems API definitions.

**Comment by wshanks** [comment]
Thanks! That makes sense. I am not that familiar with namespacing conventions in C++, so I was not sure if it not showing up on the public API page meant it shouldn't be used any more.

**Comment by RonOnGithub** [comment]
@ethomson Just to add some context to this, I just hit this too - I'm using `git_error_set*` in callbacks so that things handling the errors from the `git_*` functions which call them can safely and unconditionally report `git_error_last()->message` without needing to test if it's NULL (or segfaulting on callback signaled failures if they don't).

But I'm also ok with adding this extra include where I'm going to do that - and this change is out in the wild now in stable distro releases, so changing it back again will probably just cause even more pain for code that tries to be widely buildable.  It does need to remain available to user code in some form though.
