### ISSUE TITLE
Unable to completely override User-Agent

### ISSUE THREAD

**Issue by wfjsw** [libgit2/libgit2#6780]
I want to make libgit2 use standard git-for-windows UA so that the firewall do not complain.
#3448 apparently prohibits me from doing this.

### Reproduction steps

```
GlobalSettings.SetUserAgent("git/2.43.0.windows.1");
```

### Expected behavior

```
User-Agent: git/2.43.0.windows.1
```

### Actual behavior

```
User-Agent: git/2.0 (git/2.43.0.windows.1)
```

### Version of libgit2 (release number or SHA1)

```
git2-e632535
```

### Operating system(s) tested

Windows with LibGit2Sharp

**Comment by ethomson** [comment]
🤔  Right. As you can see, this is by design. But I understand your motivation here. That's an obnoxious firewall.

I'm okay with adding an API that lets you override the _entire_ user-agent string. Probably the best thing to do is to have an API to change the compatibility version (eg you can set it to `2.43.0.windows.1`), so you set the user agent version to `2.43.0.windows.1` and then can clear rest of the user agent string to get simply `git/2.43.0.windows.1`.
