### ISSUE TITLE
Could the 1.8.2 release be made final?

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#6910]
I maintain some R bindings. Debian [pushed the libgit2 v1.8.2-rc](https://packages.debian.org/source/trixie/libgit2) into their repositories, to avoid users from adapting their bindings to the API change that was introduced in 1.8.0 and then reverted in 1.8.2.

However the 1.8.2 tag is still set to prerelease. Would it be possible to make this tag final to make the new-old API official?

As binding author I am now in the awkward situation where the latest version has a different API on different Linux distro's.

**Comment by ethomson** [comment]
Thanks @jeroen - we need to figure this out. Here's the situation:

v1.8.0: was not const correct, but had the same APIs that they'd had for years.

v1.8.1: was made const correct, but rather thoughtlessly. I didn't really think through the impact of making that change; mea culpa.

v1.8.2rc: reverted the change in v1.8.1.

For people bundling libgit2 or otherwise building against a particular version, I probably annoyed them, but there's an obvious path to resolution. Either they skipped v1.8.1 and went to v1.8.2rc, or they went to v1.8.1 and updated their code. Maybe they went to v1.8.1, changed their code, then went to v1.8.2, then changed their code back. Maybe they live with warnings. Hard to say, and they might hate me, but they're not "stuck". And I can imagine some things to maek their lives better.

For people who link against a system libgit2, though, I've made a mess of this. Because you can't predict whether somebody will rock up with v1.8.1 or not. I guess you could do version detection but... yuck.

I've been meaning to do two things:
* do a relatively comprehensive audit of who's using / shipping what versions of libgit2
* potentially introduce some sort of relatively straightforward back/forward compatibility here so that people could set a `define` before `include <git2.h>` so that they don't have to do any code changes

**Comment by ethomson** [comment]
It looks like:

* [Ubuntu](https://launchpad.net/ubuntu/+source/libgit2): no versions use v1.8.1
* [Debian](https://packages.debian.org/search?searchon=sourcenames&keywords=libgit2): no versions use v1.8.1, although I don't know if sid or trixie ever _did_ ship v1.8.1. Looking at http://deb.debian.org/debian/pool/main/libg/libgit2/, the answer might be _no_.
* [Various RPM distributions](https://rpmfind.net/linux/rpm2html/search.php?query=libgit2(x86-64)) - looks like only OpenMandriva (?) ships v1.8.1.

So probably the best path forward is to commit to keeping the APIs that exist in v1.8.0 and v1.8.2rc, and calling v1.8.1 an oopsie. Then ship v1.8.2 and v1.9.

I'm thinking about adding some sort of `#ifdef I_WANT_THE_CONST_CORRECT_COMMIT_APIS` or something so that people who _did_ make the change for v1.8.1 can keep it. 🤔

**Comment by jeroen** [comment]
Fortunately I think most of the "mess" was mostly mitigated by the distros holding back on 1.8.x in stable channels because they noticed the breakage.

Debian did have 1.8.1 in their testing repo for a bit, but never in a release branch. It [never made it to Ubuntu](https://packages.ubuntu.com/oracular/libgit2-dev) either. They now quickly bumped to 1.8.2-rc to skip over the breakage. 

Looks like the folks at redhat/fedora [have done the same](https://src.fedoraproject.org/rpms/libgit2).

As binding author I prefer not to have a `I_WANT_THE_CONST_CORRECT_COMMIT_APIS` and just decide on a single API. So I would think to just bite the bullet and make the reversal official by tagging 1.8.2, so that everyone is on the same page again :) 

Authors of bindings that really want to support the 1.8.1 version can do something like:

```c
#if LIBGIT2_VER_MAJOR == 1 && LIBGIT2_VER_MINOR == 8 && LIBGIT2_VER_REVISION ==1 2
#define no_const_workaround (git_commit **)
#else
#define no_const_workaround
#endif
```

**Comment by ethomson** [comment]
> As binding author I prefer not to have a I_WANT_THE_CONST_CORRECT_COMMIT_APIS and just settle on a single API. So I would recommend to just bite the bullet and make the reversal official by tagging 1.8.2, so that everyone is on the same page again. I don't think it's worth your time doing an audit, just move on, mistakes happen.

OK, thanks, that's what I'm leaning towards as well.

**Comment by ethomson** [comment]
![It is decided](https://github.com/user-attachments/assets/9ce72a84-1027-4046-bca6-f224452e8c84)

**Comment by petefwalter** [comment]
Thanks!
